### ISSUE TITLE
[llgo] Building error: argument of incompatible type

### ISSUE THREAD

**Issue by xaionaro** [llvm/llvm-project#100]
Hello.
```
cd /home/experiment0/llvm-project/build
cmake ../llvm -DLLVM_ENABLE_PROJECTS='clang;llgo' -DCMAKE_INSTALL_PREFIX=/opt/llvm
make -j 6
```
Results into:
```
llgo: /home/experiment0/llvm-project/llvm/include/llvm/Support/Casting.h:264: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::ConstantInt; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::ConstantInt*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
SIGABRT: abort
PC=0x7f4899a98081 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f4899a98081
stack: frame={sp:0x7fffa9259e20, fp:0x0} stack=[0x7fffa8a5c568,0x7fffa925b5a0)
00007fffa9259d20:  0000000004db0140  0000000000000001 
00007fffa9259d30:  0000000000000001  00000000024793eb 
00007fffa9259d40:  00007fffa925af30  0000000000000000 
00007fffa9259d50:  0000000000000000  0000ffff00001fa0 
00007fffa9259d60:  00007fffa925aed0  00007fffa925af30 
00007fffa9259d70:  00007fffa9259d80  0000000400000000 
00007fffa9259d80:  00007fffa9259db0  00000000096479f8 
00007fffa9259d90:  00007fffa9259db0  00007fffa9259f30 
00007fffa9259da0:  00007fffa925af30  0000000000000000 
00007fffa9259db0:  00007fffa9259ba0  0000000003e34652 
00007fffa9259dc0:  00007fffa925af30  00007fffa925af30 
00007fffa9259dd0:  00007fffa9259de0  0000000000000013 
00007fffa9259de0:  0000000000000148  9648aaf6e7e88d00 
00007fffa9259df0:  0000000000000148  00007fffa925a080 
00007fffa9259e00:  0000000000000147  0000000000000147 
00007fffa9259e10:  0000000000000148  000000000963d590 
00007fffa9259e20: <0000000000000000  00007f4899ad8d2e 
00007fffa9259e30:  fffffffffbad8000  000000000963d590 
00007fffa9259e40:  000000000963d6bd  000000000963d590 
00007fffa9259e50:  000000000963d590  000000000963d6d7 
00007fffa9259e60:  000000000963d84c  000000000963d590 
00007fffa9259e70:  000000000963d84c  0000000000000000 
00007fffa9259e80:  0000000000000000  0000000000000000 
00007fffa9259e90:  0000000000000000  0000000000000000 
00007fffa9259ea0:  fffffffe7fffffff  ffffffffffffffff 
00007fffa9259eb0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ec0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ed0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ee0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ef0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259f00:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259f10:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f4899a98081
stack: frame={sp:0x7fffa9259e20, fp:0x0} stack=[0x7fffa8a5c568,0x7fffa925b5a0)
00007fffa9259d20:  0000000004db0140  0000000000000001 
00007fffa9259d30:  0000000000000001  00000000024793eb 
00007fffa9259d40:  00007fffa925af30  0000000000000000 
00007fffa9259d50:  0000000000000000  0000ffff00001fa0 
00007fffa9259d60:  00007fffa925aed0  00007fffa925af30 
00007fffa9259d70:  00007fffa9259d80  0000000400000000 
00007fffa9259d80:  00007fffa9259db0  00000000096479f8 
00007fffa9259d90:  00007fffa9259db0  00007fffa9259f30 
00007fffa9259da0:  00007fffa925af30  0000000000000000 
00007fffa9259db0:  00007fffa9259ba0  0000000003e34652 
00007fffa9259dc0:  00007fffa925af30  00007fffa925af30 
00007fffa9259dd0:  00007fffa9259de0  0000000000000013 
00007fffa9259de0:  0000000000000148  9648aaf6e7e88d00 
00007fffa9259df0:  0000000000000148  00007fffa925a080 
00007fffa9259e00:  0000000000000147  0000000000000147 
00007fffa9259e10:  0000000000000148  000000000963d590 
00007fffa9259e20: <0000000000000000  00007f4899ad8d2e 
00007fffa9259e30:  fffffffffbad8000  000000000963d590 
00007fffa9259e40:  000000000963d6bd  000000000963d590 
00007fffa9259e50:  000000000963d590  000000000963d6d7 
00007fffa9259e60:  000000000963d84c  000000000963d590 
00007fffa9259e70:  000000000963d84c  0000000000000000 
00007fffa9259e80:  0000000000000000  0000000000000000 
00007fffa9259e90:  0000000000000000  0000000000000000 
00007fffa9259ea0:  fffffffe7fffffff  ffffffffffffffff 
00007fffa9259eb0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ec0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ed0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ee0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259ef0:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259f00:  ffffffffffffffff  ffffffffffffffff 
00007fffa9259f10:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x1ab1190, 0xc0001b5630, 0xc0001b5638)
        /home/experiment0/.gimme/versions/go1.13.linux.amd64/src/runtime/cgocall.go:128 +0x5b fp=0xc0001b5600 sp=0xc0001b55c8 pc=0x17a77ab
llvm.org/llvm/bindings/go/llvm._Cfunc_LLVMRunFunctionPassManager(0x9629510, 0x9641d18, 0x0)
        _cgo_gotypes.go:8712 +0x4d fp=0xc0001b5630 sp=0xc0001b5600 pc=0x19f762d
llvm.org/llvm/bindings/go/llvm.PassManager.RunFunc.func1(0x9629510, 0x9641d18, 0x9641d18)
        /tmp/gopath264257107/src/llvm.org/llvm/bindings/go/llvm/ir.go:2004 +0x8f fp=0xc0001b5668 sp=0xc0001b5630 pc=0x1a223bf
llvm.org/llvm/bindings/go/llvm.PassManager.RunFunc(0x9629510, 0x9641d18, 0x9629501)
        /tmp/gopath264257107/src/llvm.org/llvm/bindings/go/llvm/ir.go:2004 +0x35 fp=0xc0001b5690 sp=0xc0001b5668 pc=0x1a07895
main.runPasses(0xc0001b5e00, 0x96125f0, 0x9613ed0)
        /tmp/gopath264257107/src/llvm.org/llgo/cmd/gllgo/gllgo.go:513 +0x277 fp=0xc0001b5780 sp=0xc0001b5690 pc=0x1aa7597
main.performAction(0xc0001b5e00, 0x1, 0xc0000d6080, 0x6, 0x8, 0x7fffa925c263, 0x12, 0x0, 0x0)
        /tmp/gopath264257107/src/llvm.org/llgo/cmd/gllgo/gllgo.go:629 +0x17d2 fp=0xc0001b5b98 sp=0xc0001b5780 pc=0x1aa9512
main.performActions(0xc0001b5e00, 0x0, 0x0)
        /tmp/gopath264257107/src/llvm.org/llgo/cmd/gllgo/gllgo.go:808 +0x35a fp=0xc0001b5c88 sp=0xc0001b5b98 pc=0x1aaa1ba
main.main()
        /tmp/gopath264257107/src/llvm.org/llgo/cmd/gllgo/gllgo.go:832 +0xe0 fp=0xc0001b5f60 sp=0xc0001b5c88 pc=0x1aaa650
runtime.main()
        /home/experiment0/.gimme/versions/go1.13.linux.amd64/src/runtime/proc.go:203 +0x21e fp=0xc0001b5fe0 sp=0xc0001b5f60 pc=0x17d35be
runtime.goexit()
        /home/experiment0/.gimme/versions/go1.13.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001b5fe8 sp=0xc0001b5fe0 pc=0x17fe161

rax    0x0
rbx    0x7f4899fb4000
rcx    0x7f4899a98081
rdx    0x0
rdi    0x2
rsi    0x7fffa9259e20
rbp    0x7f4899be56e0
rsp    0x7fffa9259e20
r8     0x0
r9     0x7fffa9259e20
r10    0x8
r11    0x246
r12    0x4db00f8
r13    0x108
r14    0x4db0140
r15    0x200
rip    0x7f4899a98081
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
make[5]: *** [Makefile:4998: runtime-go.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:4303: all-recursive] Error 1
make[3]: *** [Makefile:2555: all] Error 2
```
On Debian Buster.
```
$ git branch
* (HEAD detached at llvmorg-9.0.1)
  master
```
The failed command is:
```
/home/experiment0/llvm-project/build/bin/llgo -no-prefix -fcompilerrt-prefix=/home/experiment0/llvm-project/build -minline-all-stringops -g -O2 -I . -c -fgo-pkgpath=runtime /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/runtime/compiler.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/runtime/debug.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/runtime/error.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/runtime/extern.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/runtime/mem.go version.go  -fPIC -o .libs/runtime-go.o
```

It would've been nice to know which code-line (of the `runtime` package) causes this error.

**Comment by xaionaro** [comment]
If I remove `-O2` then the command works fine.

**Comment by xaionaro** [comment]
When I work-around this stuff a face problems with undefined constants and:
```
/usr/bin/ld: ../../lib/libgo-llgo.a(subtle.o): relocation R_X86_64_32 against symbol `__go_tdn_string' can not be used when making a PIE object; recompile with -fPIE
```
It looks like `llgo` is not supported in `llvm` at all :(

**Comment by xaionaro** [comment]
Seems to be a duplicate of: https://groups.google.com/forum/#!topic/llgo-dev/e_qUcEzTgXs

**Comment by xaionaro** [comment]
```
~/llvm-project/build/tools/llgo$ cd /home/experiment0/llvm-project/build/tools/llgo && ../../bin/llgo -static-libgo -o /home/experiment0/llvm-project/build/lib/go/llgo-11.0.0/cgo /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/ast.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/doc.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/gcc.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/godefs.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/main.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/out.go /home/experiment0/llvm-project/llgo/third_party/gofrontend/libgo/go/cmd/cgo/util.go /home/experiment0/llvm-project/llgo/cmd/cgo/zdefaultcc.go
/usr/bin/ld: /tmp/llgo357321268.o: relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(bytes.o): relocation R_X86_64_32 against symbol `__go_tdn_string' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(errors.o): relocation R_X86_64_32 against symbol `__go_tdn_errors.errorString' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(flag.o): relocation R_X86_64_32 against symbol `__go_tdn_bool' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(fmt.o): relocation R_X86_64_32 against symbol `__go_td_pN7_fmt.fmt' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(io.o): relocation R_X86_64_32 against symbol `__go_td_S0_pN10_sync.Mutexe' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(math.o): relocation R_X86_64_32S against `.rodata.cst16' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(os.o): relocation R_X86_64_32 against symbol `__go_tdn_os.PathError' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(reflect-go.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(runtime-go.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(sort.o): relocation R_X86_64_32 against symbol `__go_tdn_sort.Float64Slice' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(strconv.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(strings.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(sync.o): relocation R_X86_64_32 against symbol `__go_tdn_string' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(syscall.o): relocation R_X86_64_32 against symbol `__go_td_AN5_uint8e' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(time-go.o): relocation R_X86_64_32 against symbol `__go_td_AN5_uint832e' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(unicode.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(md5.o): relocation R_X86_64_32 against symbol `__go_tdn_crypto_md5.digest' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(dwarf.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(elf.o): relocation R_X86_64_32 against symbol `__go_td_pN14_debug_elf.File' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(macho.o): relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(pe.o): relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(binary.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(ast.o): relocation R_X86_64_32 against symbol `__go_td_AN6_stringe' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(parser.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(printer.o): relocation R_X86_64_32 against symbol `__go_map_MN11_go_ast.Node__N3_int' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(scanner.o): relocation R_X86_64_32 against symbol `__go_tdn_go_scanner.Error' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(token.o): relocation R_X86_64_32 against symbol `__go_td_S0_pN12_sync.RWMutexe' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(ioutil.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(exec.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(filepath.o): relocation R_X86_64_32 against symbol `__go_td_AN5_uint8e' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(atomic.o): relocation R_X86_64_32 against symbol `__go_tdn_string' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(tabwriter.o): relocation R_X86_64_32 against symbol `__go_tdn_error' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(crypto.o): relocation R_X86_64_32 against `.data' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: ../../lib/libgo-llgo.a(path.o): relocation R_X86_64_32 against symbol `__go_td_AN5_uint8e' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
gllgo: error: exit status 1
```

**Comment by asl** [comment]
I don't think llgo is alive for a while. So, I would suggest you either fix these issues and submit patches or not spend your time on this. Maybe we'd need to remove llgo sooner than later :)

**Comment by xaionaro** [comment]
> I don't think llgo is alive for a while. So, I would suggest you either fix these issues and submit patches or not spend your time on this. Maybe we'd need to remove llgo sooner than later :)

Before considering fixing it I need to understand how useful llgo could be. If it will help to essentially reduce the size of a binary (compiled from Go source codes) then may be. Right now I just need to get it work somehow just to make measurements.

**Comment by asl** [comment]
Note that last non-trivial commit there was more than 2 years ago. 
So, some fixes might be needed :)

**Comment by xgupta** [comment]
llgo is not in the repo anymore.
