### ISSUE TITLE
`auto-subscribe` job from `Issue Subscriber` workflow failed with "401 Bad credentials"

### ISSUE THREAD

**Issue by firewave** [llvm/llvm-project#101183]
I just adjusted the labels of some tickets and got notifications about failed workflows.

```
[llvm/llvm-project] Issue Subscriber workflow run

Repository: llvm/llvm-project
Workflow: Issue Subscriber
Duration: 16.0 seconds
Finished: 2024-07-30 13:13:40 UTC

View results:
https://github.com/llvm/llvm-project/actions/runs/10163066135

Jobs:
  * auto-subscribe failed (1 annotation)
```

```
Traceback (most recent call last):
  File "/home/runner/work/llvm-project/llvm-project/llvm/utils/git/./github-automation.py", line 747, in <module>
    issue_subscriber = IssueSubscriber(
  File "/home/runner/work/llvm-project/llvm-project/llvm/utils/git/./github-automation.py", line 68, in __init__
    self.repo = github.Github(token).get_repo(repo)
  File "/home/runner/.local/lib/python3.10/site-packages/github/MainClass.py", line 363, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/home/runner/.local/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/home/runner/.local/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest", "status": "401"}
```

Additional failures:
https://github.com/llvm/llvm-project/actions/runs/10163063301
https://github.com/llvm/llvm-project/actions/runs/10163063341

**Comment by tstellar** [comment]
This was caused by an expired access token.  I've fixed this and also re-run all the failed jobs.
