### ISSUE TITLE
`run-clang-tidy` does not accept `-p compile_commands.json`, only directories, unlike `clang-tidy` itself

### ISSUE THREAD

**Issue by lf-** [llvm/llvm-project#101440]
Observe the following: clang-tidy accepts a path to a compilation database:
```
lix/lix3 » clang-tidy --checks='-*,bugprone-*' -p build/meson/clang-tidy/compile_commands.json src/libutil/args.cc
38307 warnings generated.
../src/libutil/args.cc:91:37: warning: narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'typename iterator_tr
aits<_List_iterator<basic_string<char>>>::difference_type' (aka 'long') is implementation-defined [bugprone-narrowing-conversions]
   91 |         *std::next(cmdline.begin(), n - 1) += completionMarker;
      |                                     ^
Suppressed 38314 warnings (38306 in non-user code, 8 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as we
ll.
```

Oops, this is another bug in run-clang-tidy I hit by accident: the arg parsing cannot accept double dashes in args. But back to the main program.
```
lix/lix3 » run-clang-tidy --checks='-*,bugprone-*' -p build/meson/clang-tidy/compile_commands.json src/libutil/args.cc
usage: run-clang-tidy [-h] [-allow-enabling-alpha-checkers] [-clang-tidy-binary PATH] [-clang-apply-replacements-binary PATH]
                      [-checks CHECKS] [-config CONFIG | -config-file CONFIG_FILE] [-header-filter HEADER_FILTER]
                      [-line-filter LINE_FILTER] [-export-fixes filename] [-j J] [-fix] [-format] [-style STYLE]
                      [-use-color [USE_COLOR]] [-p BUILD_PATH] [-extra-arg EXTRA_ARG] [-extra-arg-before EXTRA_ARG_BEFORE]
                      [-quiet] [-load PLUGINS] [-warnings-as-errors WARNINGS_AS_ERRORS]
                      [files ...]
run-clang-tidy: error: unrecognized arguments: --checks=-*,bugprone-*
```

However, with run-clang-tidy, this is not the case, which is busted:

```
lix/lix3 » run-clang-tidy -checks='-*,bugprone-*' -p build/meson/clang-tidy/compile_commands.json src/libutil/args.cc
Enabled checks:
    bugprone-argument-comment
    ... more elided ...
    bugprone-virtual-near-miss

Traceback (most recent call last):
  File "/nix/store/cmxvjk0wx47kznqs0ny84axypsajk08v-clang-17.0.6/bin/run-clang-tidy", line 505, in <module>
    main()
  File "/nix/store/cmxvjk0wx47kznqs0ny84axypsajk08v-clang-17.0.6/bin/run-clang-tidy", line 428, in main
    database = json.load(open(os.path.join(build_path, db_path)))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'build/meson/clang-tidy/compile_commands.json/compile_commands.json'
```

clang version: 17.0.6 from nixpkgs

**Comment by vbvictor** [comment]
We should add support for direct .json file.
As for `--` vs `-`, if python can do that we should enable it too
