### ISSUE TITLE
[clang-tidy] add_new_check.py fails with "TypeError: 'type' object is not subscriptable"

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#107846]
```cpp
$ ./clang-tools-extra/clang-tidy/add_new_check.py bugprone bit-cast-pointers --standard=c++20
Updating ./clang-tools-extra/clang-tidy/bugprone/CMakeLists.txt...
Creating ./clang-tools-extra/clang-tidy/bugprone/BitCastPointersCheck.h...
Creating ./clang-tools-extra/clang-tidy/bugprone/BitCastPointersCheck.cpp...
Updating ./clang-tools-extra/clang-tidy/bugprone/BugproneTidyModule.cpp...
Updating clang-tools-extra/docs/ReleaseNotes.rst...
Creating clang-tools-extra/test/clang-tidy/checkers/bugprone/bit-cast-pointers.cpp...
Creating clang-tools-extra/docs/clang-tidy/checks/bugprone/bit-cast-pointers.rst...
Traceback (most recent call last):
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 795, in <module>
    main()
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 790, in main
    update_checks_list(clang_tidy_path)
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 514, in update_checks_list
    def process_doc(doc_file: Tuple[str, str]) -> Tuple[str, Optional[re.Match[str]]]:
TypeError: 'type' object is not subscriptable
```

**Comment by 5chmidti** [comment]
This will have been caused by #106801. It looks like python 3.8 (which is the LLVM minimum), does also not support subscripting the `Tuple` type.
CC @nicovank

**Comment by h-vetinari** [comment]
FWIW, python 3.8 is [EOL](https://peps.python.org/pep-0569/) in October, so probably worth discussing a move to 3.9 soonish.

**Comment by nicovank** [comment]
> Python 3.8 does also not support subscripting the Tuple type.

I think the problem is not the Tuple type but the `re.Match` type, woops missed that.
https://docs.python.org/3/library/re.html#match-objects

![image](https://github.com/user-attachments/assets/aacea064-3895-49e7-bf88-e5c33ab96055)
