### ISSUE TITLE
Could not cast value of type 'Swift.String' (0x7ff8556a6848) to 'Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>'

### ISSUE THREAD

**Issue by david-hm-morgan** [llvm/llvm-project#108938]
```
Could not cast value of type 'Swift.String' (0x7ff8556a6848) to 'Swift.Dictionary<Swift.String, SourceKittenFramework.SourceKitRepresentable>' (0x7ff855e42708).

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/sourcekitten.rb:229:in `run_sourcekitten'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/doc_builder.rb:83:in `block (2 levels) in build'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/doc_builder.rb:81:in `chdir'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/doc_builder.rb:81:in `block in build'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/doc_builder.rb:71:in `map'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/lib/jazzy/doc_builder.rb:71:in `build'
	from /Users/jenkins/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jazzy-0.15.1/bin/jazzy:16:in `<top (required)>'
	from /Users/jenkins/.rbenv/versions/3.2.2/bin/jazzy:25:in `load'
	from /Users/jenkins/.rbenv/versions/3.2.2/bin/jazzy:25:in `<main>'
```

Using:
- Xcode 16.0
- Sourcekitten 0.36.0
- rbenv 3.2.2
- jazzy version: 0.15.1

**Comment by serajahmad01** [comment]
Facing the same issue while generating Jazzy Docs for an iOS Frameworks

**Comment by johnny-liang-gd** [comment]
Got the same error generating the iOS static lib, any solution yet? Thanks.

**Comment by johnny-liang-gd** [comment]
OK, turned out it's a jazzy lib issue which is resolved with the latest version 0.15.3
@david-hm-morgan @serajahmad01

**Comment by serajahmad01** [comment]
Thanks @johnny-liang-gd . Got it working after update to 0.15.3 of jazzy

**Comment by Endilll** [comment]
If this is still an issue, it should be reported to https://github.com/swiftlang/swift first.
