### ISSUE TITLE
libcxx fails to build with `__cxx03/__algorithm/adjacent_find.h: Header cxx03 is not a valid header`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#110808]
On Ubuntu jammy:

```
FAILED: /build/source/build-llvm/include/c++/v1/libcxx.imp
cd /build/source/build-llvm/runtimes/runtimes-bins/libcxx/include && /usr/bin/python3.10 /build/source/libcxx/utils/generate_iwyu_mapping.py -o /build/source/build-llvm/include/c++/v1/libcxx.imp
Traceback (most recent call last):
  File "/build/source/libcxx/utils/generate_iwyu_mapping.py", line 92, in <module>
    main(sys.argv[1:])
  File "/build/source/libcxx/utils/generate_iwyu_mapping.py", line 82, in main
    raise RuntimeError(f"{header}: Header {public} is not a valid header")
RuntimeError: __cxx03/__algorithm/adjacent_find.h: Header cxx03 is not a valid header
```

Log: https://llvm-jenkins.debian.net/job/llvm-toolchain-jammy-binaries/architecture=amd64,distribution=jammy,label=amd64/1696/

**Comment by sylvestre** [comment]
seems to be caused by 67432f20491a0fa6b05f8a3a91f88e26175453d6 cc @philnik777

**Comment by Michael137** [comment]
Seeing this also on the buildbots: https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/as-lldb-cmake/12720/execution/node/45/log/

```
[9/1232] Generate the mapping file for include-what-you-use
FAILED: /Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/lldb-build/include/c++/v1/libcxx.imp 
cd /Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/lldb-build/runtimes/runtimes-bins/libcxx/include && /Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/venv/bin/python3.9 /Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/libcxx/utils/generate_iwyu_mapping.py -o /Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/lldb-build/include/c++/v1/libcxx.imp
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/libcxx/utils/generate_iwyu_mapping.py", line 92, in <module>
    main(sys.argv[1:])
  File "/Users/ec2-user/jenkins/workspace/llvm.org/as-lldb-cmake/llvm-project/libcxx/utils/generate_iwyu_mapping.py", line 82, in main
    raise RuntimeError(f"{header}: Header {public} is not a valid header")
```

**Comment by sylvestre** [comment]
ok, thanks for the confirmation. I reverted the change in 68c04b0ae62d8431d72d8b47fc13008002ee4387

**Comment by ldionne** [comment]
This patch was indeed checked in with a CI failure on our side too. Thanks for reverting!

**Comment by sylvestre** [comment]
Happy to help :)
