### ISSUE TITLE
TypeError in DExTer when Running Debugger with LLDB

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#111161]
I encountered a bug while using DExTer (version 1.0.0) with LLDB as the debugger. The error occurs when attempting to run a test using the command below:
`python3 dexter.py test --binary demoO0 --debugger lldb -- demo.cpp`

my demo.cpp is same with [testcase](https://github.com/llvm/llvm-project/blob/main/cross-project-tests/debuginfo-tests/dexter/README.md#an-example-test-case).
**Error Output:**
Upon execution, I received the following error message:
```
****************************************
****************************************
****************************************
**                                    **
** This is a bug in DExTer.           **
**                                    **
**                  Please report it. **
****************************************
****************************************
****************************************

system:
linux

version:
DExTer 1.0.0 [main b520ca9e37bdf921c0ed0cda888c34381629bd60] (https://gitee.com/shi-jinrui/huawei-llvm-bolt.git)
  using Python 3.10.15 (main, Oct  4 2024, 20:55:46) [GCC 10.3.1]

args:
['/home/sjr/install/python/bin/python3', '/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/../dexter.py', 'run-debugger-internal-', '/tmp/dexter/tmpweme3m52/tmp1udn3_pe', '--working-directory=/tmp/dexter/tmpweme3m52', '--unittest=off', '--indent-timer-level=3']

Traceback (most recent call last):
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/../dexter.py", line 20, in <module>
    return_code = main()
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/tools/Main.py", line 209, in main
    return tool_main(context, module.Tool(context), args)
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/tools/Main.py", line 176, in tool_main
    return_code = tool.go()
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/tools/run_debugger_internal_/Tool.py", line 61, in go
    self.debugger_controller.run_debugger(debugger)
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/debugger/DebuggerControllers/DebuggerControllerBase.py", line 39, in run_debugger
    self._run_debugger_custom(the_cmdline)
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/debugger/DebuggerControllers/DefaultController.py", line 92, in _run_debugger_custom
    self.watches.update(command_obj.get_watches())
  File "/home/sjr/llvm-huawei/cross-project-tests/debuginfo-tests/dexter/dex/command/commands/DexExpectWatchBase.py", line 144, in get_watches
    self.expression, self.path, 0, range(self._from_line, self._to_line + 1)
TypeError: can only concatenate str (not "int") to str

```

**Comment by asl** [comment]
Please report it here:
```
DExTer 1.0.0 [main b520ca9e37bdf921c0ed0cda888c34381629bd60] (https://gitee.com/shi-jinrui/huawei-llvm-bolt.git)
```

Reopen if you can reproduce using LLVM tools

**Comment by Thrrreeee** [comment]
This problem can reproduce using LLVM tools.

```
$ python3 dexter.py test --binary demoO0 --debugger lldb -- demo.cpp


****************************************
****************************************
****************************************
**                                    **
** This is a bug in DExTer.           **
**                                    **
**                  Please report it. **
**                                    **
****************************************
****************************************
****************************************

system:
linux

version:
DExTer 1.0.0 [main bf895c714e1f8a51c1e565a75acf60bf7197be51] (https://github.com/llvm/llvm-project.git)
  using Python 3.10.15 (main, Oct  4 2024, 20:55:46) [GCC 10.3.1]

args:
['/home/sjr/install/python/bin/python3', '/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/../dexter.py', 'run-debugger-internal-', '/tmp/dexter/tmpwqhdak4s/tmpyj2h1mw7', '--working-directory=/tmp/dexter/tmpwqhdak4s', '--unittest=off', '--indent-timer-level=3']

Traceback (most recent call last):
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/../dexter.py", line 20, in <module>
    return_code = main()
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/tools/Main.py", line 206, in main
    return tool_main(context, module.Tool(context), args)
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/tools/Main.py", line 175, in tool_main
    return_code = tool.go()
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/tools/run_debugger_internal_/Tool.py", line 61, in go
    self.debugger_controller.run_debugger(debugger)
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/debugger/DebuggerControllers/DebuggerControllerBase.py", line 39, in run_debugger
    self._run_debugger_custom(the_cmdline)
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/debugger/DebuggerControllers/DefaultController.py", line 89, in _run_debugger_custom
    self.debugger.launch(cmdline)
  File "/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/debugger/lldb/LLDB.py", line 180, in launch
    assert num_resolved_breakpoints > 0
AssertionError
demo.cpp: nan/nan (nan) [Command '['/home/sjr/install/python/bin/python3', '/home/sjr/llvm-project/cross-project-tests/debuginfo-tests/dexter/dex/../dexter.py', 'run-debugger-internal-', '/tmp/dexter/tmpwqhdak4s/tmpyj2h1mw7', '--working-directory=/tmp/dexter/tmpwqhdak4s', '--unittest=off', '--indent-timer-level=3']' returned non-zero exit status 1.]

```
