### ISSUE TITLE
Failures in LLDB TestProcessSaveCoreMinidump on fresh x86_64 build

### ISSUE THREAD

**Issue by asb** [llvm/llvm-project#111974]
I've been trying to see what the maximum subset of the LLVM project is I can build and test without hard to resolve failures, but I'm running into issues with some of these LLDB tests.

Build config (running on a current Arch Linux x86_64 host):
```
    mkdir -p build/release.max && cd build/release.max
    cmake -G Ninja \
      -DCMAKE_BUILD_TYPE="Release" \
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;libclc;lld;lldb;mlir;polly" \
      -DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind;openmp;pstl" \
      -DLLVM_ENABLE_ASSERTIONS=ON \
      -DLLVM_CCACHE_BUILD=ON \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DLLVM_ENABLE_LLD=True \
      -DLLVM_TARGETS_TO_BUILD="all" \
      -DLLVM_BUILD_TESTS=True \
      -DLLVM_APPEND_VC_REV=False \
      -DCOMPILER_RT_INCLUDE_TESTS=ON \
      -DCOMPILER_RT_BUILD_SANITIZERS=False \
      ../../llvm
      cmake --build .
```

Then `ninja check-lldb` and I get the failure below. I'm posting as an issue on the hope the issue obvious to an LLDB dev familiar with this test logic. User error is of course popular, but I don't think the build setup or host is overly exotic:

```
FAIL: lldb-api :: functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py (14 of 2512)
******************** TEST 'lldb-api :: functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py' FAILED ********************
Script:
--
/usr/bin/python3.12 /home/asb/llvm-project/lldb/test/API/dotest.py -u CXXFLAGS -u CFLAGS --env ARCHIVER=/usr/bin/ar --env OBJCOPY=/usr/bin/objcopy --env LLVM_LIBS_DIR=/home/asb/llvm-project/build/release.max/./lib --env LLVM_INCLUDE_DIR=/home/asb/llvm-project/build/release.max/include --env LLVM_TOOLS_DIR=/home/asb/llvm-project/build/release.max/./bin --libcxx-include-dir /home/asb/llvm-project/build/release.max/include/c++/v1 --libcxx-include-target-dir /home/asb/llvm-project/build/release.max/include/x86_64-unknown-linux-gnu/c++/v1 --libcxx-library-dir /home/asb/llvm-project/build/release.max/./lib/x86_64-unknown-linux-gnu --arch x86_64 --build-dir /home/asb/llvm-project/build/release.max/lldb-test-build.noindex --lldb-module-cache-dir /home/asb/llvm-project/build/release.max/lldb-test-build.noindex/module-cache-lldb/lldb-api --clang-module-cache-dir /home/asb/llvm-project/build/release.max/lldb-test-build.noindex/module-cache-clang/lldb-api --executable /home/asb/llvm-project/build/release.max/./bin/lldb --compiler /home/asb/llvm-project/build/release.max/./bin/clang --dsymutil /home/asb/llvm-project/build/release.max/./bin/dsymutil --make /usr/bin/make --llvm-tools-dir /home/asb/llvm-project/build/release.max/./bin --lldb-obj-root /home/asb/llvm-project/build/release.max/tools/lldb --lldb-libs-dir /home/asb/llvm-project/build/release.max/./lib /home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump -p TestProcessSaveCoreMinidump.py
--
Exit Code: 1

Command Output (stdout):
--
lldb version 20.0.0git
Skipping the following test categories: ['dsym', 'gmodules', 'debugserver', 'objc']
Error: None
Error: None

--
Command Output (stderr):
--
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_default_options_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_default_options_dsym) (test case does not fall in any category of interest for this run) 
FAIL: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_default_options_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_default_options_dwarf)
FAIL: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_default_options_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_default_options_dwo)
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_dsym) (test case does not fall in any category of interest for this run) 
FAIL: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_dwarf)
FAIL: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_dwo)
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_thread_options_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_thread_options_dsym) (test case does not fall in any category of interest for this run) 
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_thread_options_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_thread_options_dwarf)
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_mini_dump_thread_options_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_thread_options_dwo)
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_minidump_one_region_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_minidump_one_region_dsym) (test case does not fall in any category of interest for this run) 
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_minidump_one_region_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_minidump_one_region_dwarf)
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_linux_minidump_one_region_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_minidump_one_region_dwo)
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_dsym) (test case does not fall in any category of interest for this run) 
UNSUPPORTED: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_duplicated_regions_dsym (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_duplicated_regions_dsym) (test case does not fall in any category of interest for this run) 
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_duplicated_regions_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_duplicated_regions_dwarf)
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_duplicated_regions_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_duplicated_regions_dwo)
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_dwarf)
PASS: LLDB (/home/asb/llvm-project/build/release.max/bin/clang-x86_64) :: test_save_minidump_custom_save_style_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_minidump_custom_save_style_dwo)
======================================================================
FAIL: test_save_linux_mini_dump_default_options_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_default_options_dwarf)
    Test that we can save a Linux mini dump with default SBSaveCoreOptions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1769, in test_method
    return attrvalue(self)
           ^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 334, in test_save_linux_mini_dump_default_options
    self.verify_core_file(
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 41, in verify_core_file
    self.assertEqual(module_file_name, expected_file_name)
AssertionError: 'libstdc++.so.6' != 'libc++abi.so.1'
- libstdc++.so.6
+ libc++abi.so.1

Config=x86_64-/home/asb/llvm-project/build/release.max/bin/clang
======================================================================
FAIL: test_save_linux_mini_dump_default_options_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_default_options_dwo)
    Test that we can save a Linux mini dump with default SBSaveCoreOptions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1769, in test_method
    return attrvalue(self)
           ^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 334, in test_save_linux_mini_dump_default_options
    self.verify_core_file(
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 41, in verify_core_file
    self.assertEqual(module_file_name, expected_file_name)
AssertionError: 'libstdc++.so.6' != 'libc++abi.so.1'
- libstdc++.so.6
+ libc++abi.so.1

Config=x86_64-/home/asb/llvm-project/build/release.max/bin/clang
======================================================================
FAIL: test_save_linux_mini_dump_dwarf (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_dwarf)
    Test that we can save a Linux mini dump.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1769, in test_method
    return attrvalue(self)
           ^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 135, in test_save_linux_mini_dump
    self.verify_core_file(
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 41, in verify_core_file
    self.assertEqual(module_file_name, expected_file_name)
AssertionError: 'libstdc++.so.6' != 'libc++abi.so.1'
- libstdc++.so.6
+ libc++abi.so.1

Config=x86_64-/home/asb/llvm-project/build/release.max/bin/clang
======================================================================
FAIL: test_save_linux_mini_dump_dwo (TestProcessSaveCoreMinidump.ProcessSaveCoreMinidumpTestCase.test_save_linux_mini_dump_dwo)
    Test that we can save a Linux mini dump.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1769, in test_method
    return attrvalue(self)
           ^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 135, in test_save_linux_mini_dump
    self.verify_core_file(
  File "/home/asb/llvm-project/lldb/test/API/functionalities/process_save_core_minidump/TestProcessSaveCoreMinidump.py", line 41, in verify_core_file
    self.assertEqual(module_file_name, expected_file_name)
AssertionError: 'libstdc++.so.6' != 'libc++abi.so.1'
- libstdc++.so.6
+ libc++abi.so.1

Config=x86_64-/home/asb/llvm-project/build/release.max/bin/clang
----------------------------------------------------------------------
Ran 18 tests in 9.629s

FAILED (failures=4, skipped=6)
```

CC @Jlalond @jeffreytan81

**Comment by Jlalond** [comment]
@asb Interesting. I'm going to guess this is related to the most recent changes I landed related to the dynamic loader. As it's failing on an module mismatch, I'll look into this today.

**Comment by Jlalond** [comment]
@asb Would you mind reverting [this commit](https://github.com/llvm/llvm-project/commit/e9c8f75d45ababe7f805078bbf7bda2e7425f1b7) and reporting back?

**Comment by asb** [comment]
> @asb Would you mind locally reverting [this commit](https://github.com/llvm/llvm-project/commit/e9c8f75d45ababe7f805078bbf7bda2e7425f1b7) and reporting back?

I'll try a fresh build just in case there's anything funky going on, but reverting that patch, doing `cmake --build` and `ninja check-lldb` seems to show the same issue still.
