### ISSUE TITLE
[lldb-dap] TestDAP_evaluate.py test is flakey

### ISSUE THREAD

**Issue by Michael137** [llvm/llvm-project#116041]
This has been failing occasionally on Linux during PR testing. E.g., most recently in https://github.com/llvm/llvm-project/pull/115517: https://buildkite.com/llvm-project/github-pull-requests/builds/118902#0193226e-5c0a-42ad-93ad-a29d91edbe26

Example failure:
```
FAIL: LLDB (/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang-x86_64) :: test_repl_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
FAIL: LLDB (/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang-x86_64) :: test_repl_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
PASS: LLDB (/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang-x86_64) :: test_variable_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
PASS: LLDB (/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang-x86_64) :: test_watch_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
======================================================================
ERROR: test_repl_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/test/API/tools/lldb-dap/evaluate/TestDAP_evaluate.py", line 220, in test_repl_evaluate_expressions
    self.run_test_evaluate_expressions("repl", enableAutoVariableSummaries=False)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/test/API/tools/lldb-dap/evaluate/TestDAP_evaluate.py", line 104, in run_test_evaluate_expressions
    self.assertEvaluate("var", r"\(lldb\) var\n.*")
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/test/API/tools/lldb-dap/evaluate/TestDAP_evaluate.py", line 17, in assertEvaluate
    self.dap_server.request_evaluate(expression, context=self.context)["body"][
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 721, in request_evaluate
    return self.send_recv(command_dict)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 326, in send_recv
    raise ValueError(desc)
ValueError: no response for "evaluate"
Config=x86_64-/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang
======================================================================
ERROR: test_repl_evaluate_expressions (TestDAP_evaluate.TestDAP_evaluate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2030, in tearDown
    Base.tearDown(self)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1100, in tearDown
    hook()  # try the plain call and hope it works
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/lldbdap_testcase.py", line 401, in cleanup
    self.dap_server.request_disconnect(terminateDebuggee=True)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 674, in request_disconnect
    return self.send_recv(command_dict)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 320, in send_recv
    self.send_packet(command)
  File "/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/lldb/packages/Python/lldbsuite/test/tools/lldb-dap/dap_server.py", line 275, in send_packet
    self.send.flush()
BrokenPipeError: [Errno 32] Broken pipe
Config=x86_64-/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-chnxh-1/llvm-project/github-pull-requests/build/bin/clang
----------------------------------------------------------------------
Ran 5 tests in 884.999s
```

The last couple of failures I looked at all fail when running `self.assertEvaluate("var", r"\(lldb\) var\n.*")`.

Just going off of the git log CCing  @ashgti @walter-erquinigo. Mind taking a look? We really don't want to be flakey on the pre-commit CI

**Comment by Michael137** [comment]
Attached example build/test failure:

[github-pull-requests_build_118902_linux-linux-x64.log](https://github.com/user-attachments/files/17732809/github-pull-requests_build_118902_linux-linux-x64.log)

**Comment by ashgti** [comment]
I did see this running the test on my linux VM. I think attached to the process at the time and it was using a large amount of memory with a stack trace of:

```
* thread #1, name = 'lldb-dap', stop reason = signal SIGSTOP                                                                                                                                         13:11:29 [24/181]
  * frame #0: 0x00007f4d1b371180 libc.so.6`__memcpy_avx_unaligned_erms at memmove-vec-unaligned-erms.S:490                                                                                                            
    frame #1: 0x00007f4d1ce61a27 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11]() const [inlined] std::char_traits<char>::copy(__s1=<unavailable>, __s2=<unavailable>, __n=<unavailable>) at char_traits.h:435:33     
    frame #2: 0x00007f4d1ce61a19 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11]() const [inlined] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_S_copy(__d="", __s="parent failed t
o evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed
 to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent fail
ed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent fa
iled to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent 
failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate"..., __n=561506) at basic_string.h:430:4                    
    frame #3: 0x00007f4d1ce61a19 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11]() const [inlined] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_S_copy_chars(__p="", __k1="parent f
ailed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent
 failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: pare
nt failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: pa
rent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: 
parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate"..., __k2="") at basic_string.h:478:9                
    frame #4: 0x00007f4d1ce61a19 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11]() const [inlined] void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_construct<char*>(this=""...,
 __beg="parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to 
evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed t
o evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed
 to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent fail
ed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate: parent failed to evaluate"..., __end="", (null)=<unavailable>) 
at basic_string.tcc:247:2                                                                                                                                                                                             
    frame #5: 0x00007f4d1ce61a19 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11]() const [inlined] std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::basic_string(this=""..., __str=<unav
ailable>) at basic_string.h:551:2                                                                                                                                                                                     
    frame #6: 0x00007f4d1ce61a19 liblldb.so.20.0git`llvm::Twine::str[abi:cxx11](this=<unavailable>) const at Twine.cpp:20:12                                                                                          
    frame #7: 0x00007f4d1ca4c466 liblldb.so.20.0git`lldb_private::Status::Status(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>) [inlined] llvm::createStringError(EC=(_M_value = 3, _M_cat = 0x00007f4d26fe55a8), S=0x00007ffe05577ac0) at Error.h:1300:30
    frame #8: 0x00007f4d1ca4c45e liblldb.so.20.0git`lldb_private::Status::Status(this=0x00007ffe055780a0, err_str=<unavailable>) at Status.cpp:97:11
    frame #9: 0x00007f4d1ca4c96c liblldb.so.20.0git`lldb_private::Status::FromErrorStringWithFormat(format=<unavailable>) at Status.cpp:116:10
    frame #10: 0x00007f4d1ca6b6b6 liblldb.so.20.0git`lldb_private::ValueObjectChild::UpdateValue(this=<unavailable>) at ValueObjectChild.cpp:209:17
    frame #11: 0x00007f4d1ca5adb8 liblldb.so.20.0git`lldb_private::ValueObject::UpdateValueIfNeeded(this=0x000055cd4b65bcb0, update_format=false) at ValueObject.cpp:169:22
    frame #12: 0x00007f4d1ca5becb liblldb.so.20.0git`lldb_private::ValueObject::GetError(this=<unavailable>) at ValueObject.cpp:281:3
    frame #13: 0x00007f4d1c6dedf3 liblldb.so.20.0git`ValueImpl::GetSP(this=0x000055cd3fbc1b70, stop_locker=0x00007ffe05578350, lock=0x00007ffe05578358, error=0x00007ffe05578368) at SBValue.cpp:118:19
    frame #14: 0x00007f4d1c6d1a2c liblldb.so.20.0git`lldb::SBValue::GetSP(ValueLocker&) const [inlined] ValueLocker::GetLockedSP(this=0x00007ffe05578350, in_value=<unavailable>) at SBValue.cpp:209:21
    frame #15: 0x00007f4d1c6d1a19 liblldb.so.20.0git`lldb::SBValue::GetSP(this=0x000055cd3fcdeca0, locker=0x00007ffe05578350) const at SBValue.cpp:1101:17
    frame #16: 0x00007f4d1c6d9a61 liblldb.so.20.0git`lldb::SBValue::GetValueAsUnsigned(this=0x000055cd3fcdeca0, fail_value=0) at SBValue.cpp:939:32
    frame #17: 0x00007f4d1c7aa026 liblldb.so.20.0git`_wrap_SBValue_GetValueAsUnsigned(_object*, _object*) [inlined] _wrap_SBValue_GetValueAsUnsigned__SWIG_2(self=<unavailable>, nobjs=2, swig_obj=0x00007ffe05578410) at LLDBWrapPython.cpp:89161:32
    frame #18: 0x00007f4d1c7aa013 liblldb.so.20.0git`_wrap_SBValue_GetValueAsUnsigned(self=<unavailable>, args=<unavailable>) at LLDBWrapPython.cpp:89239:16
    frame #19: 0x00007f4d1abb5495 libpython3.11.so.1.0`___lldb_unnamed_symbol3965 + 69
    frame #20: 0x00007f4d1ab655c8 libpython3.11.so.1.0`_PyObject_Call + 88
    frame #21: 0x00007f4d1ab0c117 libpython3.11.so.1.0`_PyEval_EvalFrameDefault + 23895
    frame #22: 0x00007f4d1ac5f438 libpython3.11.so.1.0`___lldb_unnamed_symbol4856 + 216
    frame #23: 0x00007f4d1ab68498 libpython3.11.so.1.0`___lldb_unnamed_symbol3206 + 216
    frame #24: 0x00007f4d1cd17d8b liblldb.so.20.0git`lldb_private::python::PythonCallable::operator()(this=0x00007ffe05578730, args=<unavailable>) at PythonDataObjects.cpp:927:23
    frame #25: 0x00007f4d1c6eb15a liblldb.so.20.0git`lldb_private::python::SWIGBridge::LLDBSwigPython_GetChildAtIndex(_object*, unsigned int) [inlined] lldb_private::python::PythonObject lldb_private::python::Pytho
nCallable::operator()<lldb_private::python::PythonInteger>(this=0x00007ffe05578730, arg=0x00007ffe05578738) at PythonDataObjects.h:639:12
    frame #26: 0x00007f4d1c6eb125 liblldb.so.20.0git`lldb_private::python::SWIGBridge::LLDBSwigPython_GetChildAtIndex(implementor=<unavailable>, idx=1) at LLDBWrapPython.cpp:5212:25
    frame #27: 0x00007f4d1cd279f7 liblldb.so.20.0git`lldb_private::ScriptInterpreterPythonImpl::GetChildAtIndex(this=<unavailable>, implementor_sp=<unavailable>, idx=1) at ScriptInterpreterPython.cpp:2040:9
    frame #28: 0x00007f4d1c869349 liblldb.so.20.0git`lldb_private::ScriptedSyntheticChildren::FrontEnd::GetChildAtIndex(this=<unavailable>, idx=<unavailable>) at TypeSynthetic.cpp:184:25
    frame #29: 0x00007f4d1ca75369 liblldb.so.20.0git`lldb_private::ValueObjectSynthetic::GetChildAtIndex(this=0x000055cd3fc351b0, idx=1, can_create=true) at ValueObjectSyntheticFilter.cpp:273:58
    frame #30: 0x00007f4d1c86d11a liblldb.so.20.0git`lldb_private::ValueObjectPrinter::PrintChildren(bool, bool, lldb_private::DumpValueObjectOptions::PointerDepth const&) [inlined] lldb_private::ValueObjectPrinter
::GenerateChild(this=0x00007ffe055789d8, synth_valobj=0x000055cd3fc351b0, idx=1) at ValueObjectPrinter.cpp:717:25
    frame #31: 0x00007f4d1c86d0c8 liblldb.so.20.0git`lldb_private::ValueObjectPrinter::PrintChildren(this=0x00007ffe055789d8, value_printed=false, summary_printed=true, curr_ptr_depth=0x00007ffe05578940) at ValueOb
jectPrinter.cpp:737:36
    frame #32: 0x00007f4d1c86b6f9 liblldb.so.20.0git`lldb_private::ValueObjectPrinter::PrintChildrenIfNeeded(this=0x00007ffe055789d8, value_printed=false, summary_printed=true) at ValueObjectPrinter.cpp:860:7
    frame #33: 0x00007f4d1c86a7d7 liblldb.so.20.0git`lldb_private::ValueObjectPrinter::PrintValueObject(this=0x00007ffe055789d8) at ValueObjectPrinter.cpp:94:12
    frame #34: 0x00007f4d1ca65b85 liblldb.so.20.0git`lldb_private::ValueObject::Dump(this=<unavailable>, s=<unavailable>, options=<unavailable>) at ValueObject.cpp:2745:18
    frame #35: 0x00007f4d1eb09b41 liblldb.so.20.0git`CommandObjectFrameVariable::DoExecute(this=0x000055cd3f90c9d0, command=<unavailable>, result=0x000055cd3fbe6360) at CommandObjectFrame.cpp:679:36
    frame #36: 0x00007f4d1c8b834d liblldb.so.20.0git`lldb_private::CommandObjectParsed::Execute(this=<unavailable>, args_string=<unavailable>, result=0x000055cd3fbe6360) at CommandObject.cpp:826:9
    frame #37: 0x00007f4d1c8ab91c liblldb.so.20.0git`lldb_private::CommandInterpreter::HandleCommand(this=0x000055cd3f754880, command_line=<unavailable>, lazy_add_to_history=<unavailable>, result=0x000055cd3fbe6360
, force_repeat_command=<unavailable>) at CommandInterpreter.cpp:2087:14
    frame #38: 0x00007f4d1c5f241c liblldb.so.20.0git`lldb::SBCommandInterpreter::HandleCommand(this=0x00007ffe05579258, command_line="var", override_context=0x00007ffe055791d8, result=0x00007ffe05579228, add_to_his
tory=<unavailable>) at SBCommandInterpreter.cpp:194:21
    frame #39: 0x00007f4d1c5f21e8 liblldb.so.20.0git`lldb::SBCommandInterpreter::HandleCommand(this=0x00007ffe05579258, command_line=<unavailable>, result=0x00007ffe05579228, add_to_history=<unavailable>) at SBComm
andInterpreter.cpp:176:10
    frame #40: 0x000055cd19b883e6 lldb-dap`lldb_dap::RunLLDBCommands(prefix=(Data = 0x0000000000000000, Length = 0), commands=0x00007ffe05579388, strm=0x00007ffe055792c8, parse_command_directives=false) at LLDBUtil
s.cpp:50:14
    frame #41: 0x000055cd19b8883e lldb-dap`lldb_dap::RunLLDBCommandsVerbatim(llvm::StringRef, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const&) [inlined] lldb_da
p::RunLLDBCommands(prefix=(Data = 0x0000000000000000, Length = 0), commands=0x00007ffe05579388, required_command_failed=<unavailable>, parse_command_directives=false) at LLDBUtils.cpp:89:8
    frame #42: 0x000055cd19b887c9 lldb-dap`lldb_dap::RunLLDBCommandsVerbatim(prefix=(Data = 0x0000000000000000, Length = 0), commands=0x00007ffe05579388) at LLDBUtils.cpp:97:10
    frame #43: 0x000055cd19b5bf56 lldb-dap`(anonymous namespace)::request_evaluate(request=<unavailable>) at lldb-dap.cpp:1618:9
    frame #44: 0x000055cd19b927f7 lldb-dap`lldb_dap::DAP::HandleObject(this=0x000055cd19c091c0, object=0x00007ffe05579720) at DAP.cpp:697:7
    frame #45: 0x000055cd19b92a1b lldb-dap`lldb_dap::DAP::Loop(this=0x000055cd19c091c0) at DAP.cpp:758:10
    frame #46: 0x000055cd19b58613 lldb-dap`main(argc=<unavailable>, argv=<unavailable>) at lldb-dap.cpp:5065:24
    frame #47: 0x00007f4d1b243b8a libc.so.6`__libc_start_call_main(main=(lldb-dap`main at lldb-dap.cpp:4945), argc=1, argv=0x00007ffe0557a0c8) at libc_start_call_main.h:58:16
    frame #48: 0x00007f4d1b243c45 libc.so.6`__libc_start_main_impl(main=(lldb-dap`main at lldb-dap.cpp:4945), argc=1, argv=0x00007ffe0557a0c8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_
end=0x00007ffe0557a0b8) at libc-start.c:360:3
    frame #49: 0x000055cd19b56441 lldb-dap`_start + 33
```

I'll see if I can figure out why this test is triggering this.
