### ISSUE TITLE
Address sanitizer reporting alloc-dealloc-mismatch on std::runtime_error when using libc++

### ISSUE THREAD

**Issue by Harry-George** [llvm/llvm-project#117561]
Running the following code

```c++
#include <stdexcept>

int main() {
	std::runtime_error("Badger");
	return 0;
}
```

When run with `clang++-19 -fsanitize=address -stdlib=libc++ /tmp/test.cpp` I get the following error

```
0.217 =================================================================                                                                                                                                      
0.217 ==7==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x503000000040
0.238     #0 0x607718cc3efa in free (/a.out+0xcbefa) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.238     #1 0x7af1b7ec1eb4 in std::range_error::~range_error() (/lib/x86_64-linux-gnu/libc++abi.so.1+0x28eb4) (BuildId: 2f464e339fcd8e0b207a4b1fe2f39d4cb76b393e)
0.238     #2 0x607718d07d39 in main (/a.out+0x10fd39) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.238     #3 0x7af1b7b771c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
0.238     #4 0x7af1b7b7728a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
0.238     #5 0x607718c24364 in _start (/a.out+0x2c364) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.238 
0.238 0x503000000040 is located 0 bytes inside of 30-byte region [0x503000000040,0x50300000005e)
0.238 allocated by thread T0 here:
0.239     #0 0x607718d057f1 in operator new(unsigned long) (/a.out+0x10d7f1) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.239     #1 0x7af1b7f28bac in std::runtime_error::runtime_error(char const*) (/lib/x86_64-linux-gnu/libc++.so.1+0x53bac) (BuildId: b31db19d06890cde77ca90e984eeb93c5a896573)
0.239     #2 0x607718d07d30 in main (/a.out+0x10fd30) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.239     #3 0x7af1b7b771c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
0.239     #4 0x7af1b7b7728a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
0.239     #5 0x607718c24364 in _start (/a.out+0x2c364) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2)
0.239 
0.239 SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/a.out+0xcbefa) (BuildId: 377d2fc5145128bc6bf8483523e5bfd9f3f9fce2) in free
0.239 ==7==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
0.239 ==7==ABORTING
```

I have written a reproducer using the following docker file

```Dockerfile
FROM ubuntu:24.04 AS adapdix_base

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	software-properties-common \
    gpg \
    gnupg \
    wget 

ARG CLANG_VERSION=19

RUN wget https://apt.llvm.org/llvm.sh --no-check-certificate
RUN chmod +x llvm.sh
RUN ./llvm.sh $CLANG_VERSION
RUN apt-get install -y --no-install-recommends \
    libc++-$CLANG_VERSION-dev \
    libc++abi-$CLANG_VERSION-dev

RUN cat <<EOF > /tmp/test.cpp
#include <stdexcept>

int main() {
    std::runtime_error("Error");
    return 0;
}
EOF

RUN clang++-$CLANG_VERSION -fsanitize=address -stdlib=libc++ /tmp/test.cpp
RUN ./a.out
```
I have verified it fails on ubuntu 22.04 clang 13, 15, 17, 19 and 20
And ubuntu 24.04 on clang 19 and 20

The host machine was running ubuntu 22.04 on x64

**Comment by LucianBuzzo** [comment]
I can replicate this issue on my OSX machine with docker version 27.1.1

**Comment by chrchr-github** [comment]
Looks like a duplicate of https://github.com/llvm/llvm-project/issues/59432

**Comment by philnik777** [comment]
Yes, this is a duplicate.
