### ISSUE TITLE
Crash Report - Arch Linux

### ISSUE THREAD

**Issue by ancientjpeg** [llvm/llvm-project#118577]
Reporting a crash I've encountered in LLDB. Seems to only occur when I exit LLDB. I'm running LLDB using `lldb-dap` through neovim on Arch Linux. Here's the stack trace:

```
free(): invalid pointer
PLEASE submit a bug report to  and include the crash backtrace.
 #0 0x0000770c517c4d90 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /usr/src/debug/llvm/llvm-18.1.8.src/lib/Support/Unix/Signals.inc:723:22
 #1 0x0000770c517c1d4d llvm::sys::RunSignalHandlers() /usr/src/debug/llvm/llvm-18.1.8.src/lib/Support/Signals.cpp:105:20
 #2 0x0000770c517c1d4d SignalHandler /usr/src/debug/llvm/llvm-18.1.8.src/lib/Support/Unix/Signals.inc:403:31
 #3 0x0000770c50a4c1d0 (/usr/lib/libc.so.6+0x3d1d0)
 #4 0x0000770c50aa53f4 __pthread_kill_implementation /usr/src/debug/glibc/glibc/nptl/pthread_kill.c:44:76
 #5 0x0000770c50a4c120 raise /usr/src/debug/glibc/glibc/signal/../sysdeps/posix/raise.c:27:6
 #6 0x0000770c50a334c3 abort /usr/src/debug/glibc/glibc/stdlib/abort.c:81:7
 #7 0x0000770c50a34354 _IO_acquire_lock_fct /usr/src/debug/glibc/glibc/libio/libioP.h:979:6
 #8 0x0000770c50a34354 _IO_peekc_locked /usr/src/debug/glibc/glibc/libio/peekc.c:37:3
 #9 0x0000770c50aaf765 /usr/src/debug/glibc/glibc/malloc/malloc.c:5772:3
#10 0x0000770c50ab1c4c _int_free /usr/src/debug/glibc/glibc/malloc/malloc.c:4507:5
#11 0x0000770c50ab45ce cfree /usr/src/debug/glibc/glibc/malloc/malloc.c:3401:3
#12 0x0000770c5928362a std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:347:18
#13 0x0000770c5928362a std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:317:5
#14 0x0000770c592b6d14 lldb_private::CommandObjectParsed::~CommandObjectParsed() /usr/src/debug/lldb/lldb-18.1.8.src/include/lldb/Interpreter/CommandObject.h:399:3
#15 0x0000770c592b6d14 lldb_private::CommandPluginInterfaceImplementation::~CommandPluginInterfaceImplementation() /usr/src/debug/lldb/lldb-18.1.8.src/source/API/SBCommandInterpreter.cpp:37:7
#16 0x0000770c59283566 __gnu_cxx::__is_single_threaded() /usr/include/c++/14.1.1/ext/atomicity.h:52:14
#17 0x0000770c59283566 __gnu_cxx::__exchange_and_add_dispatch(int*, int) /usr/include/c++/14.1.1/ext/atomicity.h:98:29
#18 0x0000770c59283566 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:187:44
#19 0x0000770c59283566 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:199:28
#20 0x0000770c59aa5872 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_data() const /usr/include/c++/14.1.1/bits/basic_string.h:228:28
#21 0x0000770c59aa5872 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_is_local() const /usr/include/c++/14.1.1/bits/basic_string.h:269:13
#22 0x0000770c59aa5872 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_dispose() /usr/include/c++/14.1.1/bits/basic_string.h:287:18
#23 0x0000770c59aa5872 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::~basic_string() /usr/include/c++/14.1.1/bits/basic_string.h:809:0
#24 0x0000770c59aa5872 lldb_private::ScriptedMetadata::~ScriptedMetadata() /usr/src/debug/lldb/lldb-18.1.8.src/include/lldb/Utility/ScriptedMetadata.h:16:0
#25 0x0000770c59aa5872 void std::__new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>*) /usr/include/c++/14.1.1/bits/new_allocator.h:198:13
#26 0x0000770c59aa5872 void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>>::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>(std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>*) /usr/include/c++/14.1.1/bits/alloc_traits.h:554:15
#27 0x0000770c59aa5872 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::_M_destroy_node(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>*) /usr/include/c++/14.1.1/bits/stl_tree.h:621:24
#28 0x0000770c59aa5872 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::_M_drop_node(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>*) /usr/include/c++/14.1.1/bits/stl_tree.h:629:17
#29 0x0000770c59aa5872 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>*) /usr/include/c++/14.1.1/bits/stl_tree.h:1934:16
#30 0x0000770c59aa5872 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::~_Rb_tree() /usr/include/c++/14.1.1/bits/stl_tree.h:982:17
#31 0x0000770c59aa5872 std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::shared_ptr<lldb_private::CommandObject>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::~map() /usr/include/c++/14.1.1/bits/stl_map.h:314:7
#32 0x0000770c59aa5872 lldb_private::CommandObjectMultiword::~CommandObjectMultiword() /usr/src/debug/lldb/lldb-18.1.8.src/source/Commands/CommandObjectMultiword.cpp:28:1
#33 0x0000770c59aa5872 lldb_private::CommandObjectMultiword::~CommandObjectMultiword() /usr/src/debug/lldb/lldb-18.1.8.src/source/Commands/CommandObjectMultiword.cpp:28:1
#34 0x0000770c59283566 __gnu_cxx::__is_single_threaded() /usr/include/c++/14.1.1/ext/atomicity.h:52:14
#35 0x0000770c59283566 __gnu_cxx::__exchange_and_add_dispatch(int*, int) /usr/include/c++/14.1.1/ext/atomicity.h:98:29
#36 0x0000770c59283566 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:187:44
#37 0x0000770c59283566 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold() /usr/include/c++/14.1.1/bits/shared_ptr_base.h:199:28
#38 0x0000770c59522790 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_data() const /usr/include/c++/14.1.1/bits/basic_string.h:228:28
#39 0x0000770c59522790 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_is_local() const /usr/include/c++/14.1.1/bits/basic_string.h:269:13
#40 0x0000770c59522790 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_dispose() /usr/include/c++/14.1.1/bits/basic_string.h:287:18
#41 0x0000770c59522790 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::~basic_string() /usr/include/c++/14.1.1/bits/basic_string.h:809:0
#42 0x0000770c59522790 lldb_private::ScriptedMetadata::~ScriptedMetadata() /usr/src/debug/lldb/lldb-18.1.8.src/include/lldb/Utility/ScriptedMetadata.h:16:0
#43 0x0000770c59522790 void std::__new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>*) /usr/include/c++/14.1.1/bits/new_allocator.h:198:13
#44 0x0000770c59522790 void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>>::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>(std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>&, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>*) /usr/include/c++/14.1.1/bits/alloc_traits.h:554:15
#45 0x0000770c59522790 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>>::_M_destroy_node(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>*) /usr/include/c++/14.1.1/bits/stl_tree.h:621:24
#46 0x0000770c59522790 std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, std::shared_ptr<lldb_private::CommandObject>>>,
```

**Comment by EugeneZelenko** [comment]
Could you please try 19 or `main` branch?

**Comment by ancientjpeg** [comment]
Thanks for your reply Eugene. At the moment I’m using the LLVM distributed through the AUR, which does not yet have a version for clangd-19 available. If I get the time I’ll attempt to build from source and report back.

**Comment by foonathan** [comment]
I have a minimal reproducer for this, also clang 18.

Source file:

```cpp
int main() {
    auto ptr = new int[10];
    ptr[11] = 11;
}
```

Commandline:

```
$ clang -fsanitize=address test.cpp
$ lldb ./a.out
(lldb) target create "./a.out"
Current executable set to '/home/foonathan/Downloads/a.out' (x86_64).
(lldb) r
Process 619715 launched: '/home/foonathan/Downloads/a.out' (x86_64)
=================================================================
==619715==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50400000003c at pc 0x5555556b6707 bp 0x7fffffffe2f0 sp 0x7fffffffe2e8
WRITE of size 4 at 0x50400000003c thread T0
    #0 0x5555556b6706 in main (/home/foonathan/Downloads/a.out+0x162706) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b)
    #1 0x7ffff7a06e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #2 0x7ffff7a06ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #3 0x55555557f064 in _start (/home/foonathan/Downloads/a.out+0x2b064) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b)

0x50400000003c is located 4 bytes after 40-byte region [0x504000000010,0x504000000038)
allocated by thread T0 here:
    #0 0x5555556b3cf2 in operator new[](unsigned long) (/home/foonathan/Downloads/a.out+0x15fcf2) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b)
    #1 0x5555556b66c1 in main (/home/foonathan/Downloads/a.out+0x1626c1) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b)
    #2 0x7ffff7a06e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7ffff7a06ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #4 0x55555557f064 in _start (/home/foonathan/Downloads/a.out+0x2b064) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/foonathan/Downloads/a.out+0x162706) (BuildId: 4b5f2950d396ee243bdc309059841fa94d8f631b) in main
Shadow bytes around the buggy address:
  0x503ffffffd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x503ffffffe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x503ffffffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x503fffffff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x503fffffff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x504000000000: fa fa 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa
  0x504000000080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x504000000100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x504000000180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x504000000200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x504000000280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==619715==ABORTING
(lldb) PLEASE submit a bug report to  and include the crash backtrace.
 #0 0x00007fce45fc4d90 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7c4d90)
 #1 0x00007fce45fc1d4d (/usr/lib/libLLVM.so.18.1+0x7c1d4d)
 #2 0x00007fce4524c1d0 (/usr/lib/libc.so.6+0x3d1d0)
 #3 0x00007fce4e237c2a (/usr/lib/liblldb.so.18.1+0x837c2a)
 #4 0x00007fce4dfc5dce (/usr/lib/liblldb.so.18.1+0x5c5dce)
 #5 0x00007fce4deadea6 (/usr/lib/liblldb.so.18.1+0x4adea6)
 #6 0x00007fce4de7def5 (/usr/lib/liblldb.so.18.1+0x47def5)
 #7 0x00007fce4de831c1 (/usr/lib/liblldb.so.18.1+0x4831c1)
 #8 0x00007fce4df0cd41 (/usr/lib/liblldb.so.18.1+0x50cd41)
 #9 0x00007fce4e48883c (/usr/lib/liblldb.so.18.1+0xa8883c)
#10 0x00007fce4df0a8e7 (/usr/lib/liblldb.so.18.1+0x50a8e7)
#11 0x00007fce4dd2ea30 (/usr/lib/liblldb.so.18.1+0x32ea30)
#12 0x00007fce4ddca51b (/usr/lib/liblldb.so.18.1+0x3ca51b)
#13 0x00007fce452a339d start_thread /usr/src/debug/glibc/glibc/nptl/pthread_create.c:447:8
#14 0x00007fce4532849c __GI___clone3 /usr/src/debug/glibc/glibc/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:80:0
LLDB diagnostics will be written to /tmp/diagnostics-044da9
Please include the directory content when filing a bug report
```

The diagnostics file is empty.
