### ISSUE TITLE
signext on vector parameter raises assertion

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#15763]
|  |  |
| --- | --- |
| Bugzilla Link | [15391](https://llvm.org/bz15391) |
| Version | trunk |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |
| CC | @RKSimon |

## Extended Description 
This:
```llvm
define <4 x float> @&#8203;masked_add_1(<4 x i1> signext %mask, <4 x float> %a, <4 x float> %b) { ... }
```
or this: 
```llvm
define <4 x float> @&#8203;masked_add_32(<4 x i32> signext %mask, <4 x float> %a, <4 x float> %b) { ... }
```

will raise an assertion due to the `signext` attribute.

backtrace:
```
#0  0x00007ffff6e2d2c5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6e2e748 in abort () from /usr/lib/libc.so.6
#2  0x000000000137e601 in (anonymous namespace)::Verifier::abortIfBroken (this=0x1e161a0) at /home/roland/projects/sierra/llvm/lib/IR/Verifier.cpp:226
#3  0x000000000137e2f9 in (anonymous namespace)::Verifier::runOnFunction (this=0x1e161a0, F=...) at /home/roland/projects/sierra/llvm/lib/IR/Verifier.cpp:179
#4  0x0000000001352d1d in llvm::FPPassManager::runOnFunction (this=0x1e16af0, F=...) at /home/roland/projects/sierra/llvm/lib/IR/PassManager.cpp:1530
#5  0x0000000001352f0e in llvm::FPPassManager::runOnModule (this=0x1e16af0, M=...) at /home/roland/projects/sierra/llvm/lib/IR/PassManager.cpp:1550
#6  0x00000000013532a0 in llvm::MPPassManager::runOnModule (this=0x1e06110, M=...) at /home/roland/projects/sierra/llvm/lib/IR/PassManager.cpp:1608
#7  0x00000000013538c5 in llvm::PassManagerImpl::run (this=0x1e03be0, M=...) at /home/roland/projects/sierra/llvm/lib/IR/PassManager.cpp:1703
#8  0x0000000001353ad7 in llvm::PassManager::run (this=0x7fffffffdfb0, M=...) at /home/roland/projects/sierra/llvm/lib/IR/PassManager.cpp:1738
#9  0x00000000008e0307 in compileModule (argv=0x7fffffffe398, Context=...) at /home/roland/projects/sierra/llvm/tools/llc/llc.cpp:376
#10 0x00000000008df372 in main (argc=2, argv=0x7fffffffe398) at /home/roland/projects/sierra/llvm/tools/llc/llc.cpp:194
```

**Comment by widberg** [comment]
It looks like this is now handled by a pretty error message instead of an assertion. First, 043949d4465f1c49557e4ac1b9a1646ed6c80312 causes the following to be printed instead of the assertion backtrace.

```console
Wrong types for attribute: nest noalias nocapture nonnull readnone readonly signext zeroext byref(<4 x i1>) byval(<4 x i1>) inalloca(<4 x i1>) preallocated(<4 x i1>) sret(<4 x i1>) align 1 dereferenceable(1) dereferenceable_or_null(1)
void (<4 x i1>, <4 x float>, <4 x float>)* @masked_add_1
llc: error: 'test.ll': input module cannot be verified
```

Next, 5e4b33fe9218703f0b29e2446159bcf4202d15fa made the error message prettier.

```console
Attribute 'signext' applied to incompatible type!
void (<4 x i1>, <4 x float>, <4 x float>)* @masked_add_1
llc: error: 'test.ll': input module cannot be verified
```

https://godbolt.org/z/M1hqYrPTY
