### ISSUE TITLE
TestMiInterpreterExec is flaky on linux

### ISSUE THREAD

**Issue by labath** [llvm/llvm-project#25844]
|  |  |
| --- | --- |
| Bugzilla Link | [25470](https://llvm.org/bz25470) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
ERROR: test_lldbmi_thread_continue (TestMiInterpreterExec.MiInterpreterExecTestCase)
   Test that 'lldb-mi --interpreter' can continue execution by "thread continue" command.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/packages/Python/lldbsuite/test/tools/lldb-mi/interpreter/TestMiInterpreterExec.py", line 227, in test_lldbmi_thread_continue
    self.expect("@\"argc=1\\\\r\\\\n")
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/packages/Python/lldbsuite/test/tools/lldb-mi/lldbmi_testcase.py", line 54, in expect
    return self.child.expect(pattern, *args, **kwargs)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1316, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1330, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1414, in expect_loop
    raise TIMEOUT (str(e) + '\n' + str(self))
TIMEOUT: Timeout exceeded in read_nonblocking().
<pexpect.spawn object at 0x7fa3bae85ad0>
version: 2.4 ($Revision: 516 $)
command: /lldb-buildbot/lldbSlave/buildWorkingDir/scripts/../build/bin/lldb-mi
args: ['/lldb-buildbot/lldbSlave/buildWorkingDir/scripts/../build/bin/lldb-mi', '--interpreter']
searcher: searcher_re:
    0: re.compile("@"argc=1\\r\\n")
buffer (last 100 chars): roup-id="i1"
=thread-group-exited,id="i1",exit-code="0"
*stopped,reason="exited-normally"
(gdb)

before (last 100 chars): roup-id="i1"
=thread-group-exited,id="i1",exit-code="0"
*stopped,reason="exited-normally"
(gdb)

**Comment by DavidSpickett** [comment]
Test is no longer in tree, neither is the machine interface (https://github.com/lldb-tools/lldb-mi).
