### ISSUE TITLE
TestMiGdbSetShow.test_lldbmi_gdb_set_target_async_on is flaky on linux

### ISSUE THREAD

**Issue by labath** [llvm/llvm-project#26402]
|  |  |
| --- | --- |
| Bugzilla Link | [26028](https://llvm.org/bz26028) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Fails about 1% of the time. See builds 9866, 9933 and 9967 on the ubuntu builder <http://lab.llvm.org:8011/builders/lldb-x86_64-ubuntu-14.04-cmake>.

Error message:
======================================================================
ERROR: test_lldbmi_gdb_set_target_async_on (TestMiGdbSetShow.MiGdbSetShowTestCase)
   Test that 'lldb-mi --interpreter' can execute commands in async mode.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 608, in wrapper
    func(*args, **kwargs)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/packages/Python/lldbsuite/test/tools/lldb-mi/TestMiGdbSetShow.py", line 62, in test_lldbmi_gdb_set_target_async_on
    self.expect("@\"argc=1")
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/packages/Python/lldbsuite/test/tools/lldb-mi/lldbmi_testcase.py", line 54, in expect
    return self.child.expect(pattern, *args, **kwargs)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1316, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1330, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/lldb-buildbot/lldbSlave/buildWorkingDir/llvm/tools/lldb/third_party/Python/module/pexpect-2.4/pexpect.py", line 1414, in expect_loop
    raise TIMEOUT (str(e) + '\n' + str(self))
TIMEOUT: Timeout exceeded in read_nonblocking().
<pexpect.spawn object at 0x7f62bba8a890>
version: 2.4 ($Revision: 516 $)
command: /lldb-buildbot/lldbSlave/buildWorkingDir/scripts/../build/bin/lldb-mi
args: ['/lldb-buildbot/lldbSlave/buildWorkingDir/scripts/../build/bin/lldb-mi', '--interpreter']
searcher: searcher_re:
    0: re.compile("@"argc=1")
buffer (last 100 chars): roup-id="i1"
=thread-group-exited,id="i1",exit-code="0"
*stopped,reason="exited-normally"
(gdb)

before (last 100 chars): roup-id="i1"
=thread-group-exited,id="i1",exit-code="0"
*stopped,reason="exited-normally"
(gdb)

after: <class 'pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 2838
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: <open file 'child.log', mode 'w' at 0x7f62bba7eb70>
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

**Comment by DavidSpickett** [comment]
lldb-mi is now out of tree (https://github.com/lldb-tools/lldb-mi).
