### ISSUE TITLE
TestShowLocationDwarf5.py fails on AArch64 Ubuntu

### ISSUE THREAD

**Issue by rovka** [llvm/llvm-project#43525]
|  |  |
| --- | --- |
| Bugzilla Link | [44180](https://llvm.org/bz44180) |
| Version | unspecified |
| OS | Linux |
| CC | @dwblaikie,@JDevlieghere |

## Extended Description 
ERROR: test_source_map_dwo (TestShowLocationDwarf5.TestTargetSourceMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diana.picus/llvm-envs/lldb/llvm/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1851, in setUp
    Base.setUp(self)
  File "/home/diana.picus/llvm-envs/lldb/llvm/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 825, in setUp
    self.darwinWithFramework = self.platformIsDarwin()
  File "/home/diana.picus/llvm-envs/lldb/llvm/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1299, in platformIsDarwin
    return lldbplatformutil.platformIsDarwin()
  File "/home/diana.picus/llvm-envs/lldb/llvm/lldb/packages/Python/lldbsuite/test/lldbplatformutil.py", line 142, in platformIsDarwin
    return getPlatform() in getDarwinOSTriples()
  File "/home/diana.picus/llvm-envs/lldb/llvm/lldb/packages/Python/lldbsuite/test/lldbplatformutil.py", line 132, in getPlatform
    platform = lldb.DBG.GetSelectedPlatform().GetTriple().split('-')[2]
AttributeError: 'NoneType' object has no attribute 'split'
Config=aarch64-/home/diana.picus/llvm-envs/lldb/build/bin/clang-10

Strangely enough, this only happens for dwo (dwarf passes).

**Comment by DavidSpickett** [comment]
Passes locally for me now, re-enabled it so it'll run on the bots.
