### ISSUE TITLE
LLVM ERROR: out of memory

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#47116]
|  |  |
| --- | --- |
| Bugzilla Link | [47772](https://llvm.org/bz47772) |
| Version | trunk |
| OS | All |
| Attachments | [Clang crash reproducer](https://user-images.githubusercontent.com/283696/143761284-05913113-a903-49f0-954b-85b438d0f2fa.gz) |
| CC | @dwblaikie,@zygoloid |

## Extended Description 

This was caught on Fuchsia builders. What's interesting is that this error was triggered by a removal of a single line, see https://fuchsia-review.googlesource.com/c/fuchsia/+/434277

```
/b/s/w/ir/k/fuchsia/prebuilt/third_party/goma/linux-x64/gomacc  ../../prebuilt/third_party/clang/linux-x64/bin/clang++ -MD -MF host_x64-asan/obj/src/storage/volume_image/fvm/fvm-sparse-image.fvm_sparse_image_reader.cc.o.d -DTOOLCHAIN_VERSION=AuHm25kuOn_5pmla8_UrQwqDU3OfmjJIiM-yL2y960UC -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -DNDEBUG=1 -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_NOEXCEPT -I../.. -Ihost_x64-asan/gen -I../../zircon/system/ulib/fit/include -I../../zircon/system/public -I../../zircon/system/ulib/fbl/include -I../../zircon/third_party/rapidjson -I../../zircon/third_party/rapidjson/include -I../../zircon/system/ulib/fvm/include -I../../zircon/system/ulib/zxc/include -I../../zircon/system/ulib/digest/include -I../../zircon/system/ulib/gpt/include -I../../zircon/third_party/ulib/lz4/include -I../../zircon/system/ulib/zircon/include -fexperimental-new-pass-manager -fcolor-diagnostics -fcrash-diagnostics-dir=clang-crashreports -fPIE --sysroot=../../prebuilt/third_party/sysroot/linux --target=x86_64-unknown-linux-gnu -fdebug-compilation-dir . -no-canonical-prefixes -fomit-frame-pointer -fdata-sections -ffunction-sections -O3 -g3 -Wall -Wextra -Wnewline-eof -Wconversion -Wno-unused-parameter -Wno-unknown-warning-option -Wno-sign-conversion -Wno-unknown-warning-option -Wno-c99-designator -Wno-int-in-bool-context -Wno-address-of-packed-member -Wno-range-loop-analysis -Wno-deprecated-declarations -fvisibility=hidden -Werror -Wno-error=deprecated-declarations -fPIE --sysroot=../../prebuilt/third_party/sysroot/linux --target=x86_64-unknown-linux-gnu -fsanitize=address -fno-omit-frame-pointer -fno-sanitize=undefined -Wno-conversion -Wno-conversion -fvisibility-inlines-hidden -stdlib=libc++ -std=c++17 -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-unknown-warning-option -Wno-suggest-override -fno-exceptions -fno-rtti -stdlib=libc++ -c ../../src/storage/volume_image/fvm/fvm_sparse_image_reader.cc -o host_x64-asan/obj/src/storage/volume_image/fvm/fvm-sparse-image.fvm_sparse_image_reader.cc.o
LLVM ERROR: out of memory
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Fuchsia clang version 12.0.0 (https://llvm.googlesource.com/a/llvm-project 7a34dca0f3918ab1c0397e56dd64a3c04164c8b6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ../../prebuilt/third_party/clang/linux-x64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: clang-crashreports/fvm_sparse_image_reader-39d2a5.cpp
clang++: note: diagnostic msg: clang-crashreports/fvm_sparse_image_reader-39d2a5.sh
clang++: note: diagnostic msg: 

********************
```

**Comment by Endilll** [comment]
Appears to be fixed in Clang 13.
Clang 12 is indeed slowly eating up all the memory. Couple of backtraces of that:
```
#0  0x00000000052b9980 in clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) ()
#1  0x00000000052bb124 in clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) ()
#2  0x00000000053c02b8 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) ()
#3  0x00000000053c0492 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCompoundAssignOperator(clang::CompoundAssignOperator*) ()
#4  0x00000000053c0178 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) ()
#5  0x000000000538521b in (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) ()
#6  0x000000000538634a in clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) ()
#7  0x0000000005387971 in clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) ()
#8  0x0000000004f0e6b1 in clang::Parser::ParseForStatement(clang::SourceLocation*) ()
#9  0x0000000004f09e12 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#10 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#11 0x0000000004f0fbc1 in clang::Parser::ParseCompoundStatementBody(bool) ()
#12 0x0000000004f10124 in clang::Parser::ParseCompoundStatement(bool, unsigned int) ()
#13 0x0000000004f09a46 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#14 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#15 0x0000000004f0a702 in clang::Parser::ParseStatement(clang::SourceLocation*, clang::Parser::ParsedStmtContext) ()
#16 0x0000000004f0cd0f in clang::Parser::ParseIfStatement(clang::SourceLocation*) ()
#17 0x0000000004f09f02 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#18 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#19 0x0000000004f0fbc1 in clang::Parser::ParseCompoundStatementBody(bool) ()
#20 0x0000000004f11e1a in clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) ()
#21 0x0000000004e5c473 in clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) ()
#22 0x0000000004e5c16d in clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) ()
#23 0x0000000004e9f79b in clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) ()
#24 0x0000000004ea188d in clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) ()
#25 0x0000000004e7dc81 in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) ()
#26 0x0000000004e52c6f in clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) ()
#27 0x0000000004e53411 in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.0] ()
#28 0x0000000004e599b0 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#29 0x0000000004e99489 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#30 0x0000000004e99fba in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
#31 0x0000000004e84c13 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) ()
#32 0x0000000004e593d3 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#33 0x0000000004e99489 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#34 0x0000000004e993c4 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#35 0x0000000004e99fba in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
#36 0x0000000004e84c13 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) ()
#37 0x0000000004e593d3 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#38 0x0000000004e5a838 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) ()
#39 0x0000000004e4dc69 in clang::ParseAST(clang::Sema&, bool, bool) ()
#40 0x0000000003ec92e8 in clang::CodeGenAction::ExecuteAction() ()
#41 0x00000000037f06a9 in clang::FrontendAction::Execute() ()
#42 0x0000000003791f8e in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#43 0x00000000038c17f0 in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) ()
#44 0x0000000000a3f494 in cc1_main(llvm::ArrayRef<char const*>, char const*, void*) ()
#45 0x0000000000a3bca8 in ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) ()
#46 0x0000000000976c06 in main ()
```
```
#0  0x0000000005b4a9c1 in clang::Decl::isUsed(bool) const ()
#1  0x0000000005b4aa43 in clang::Decl::markUsed(clang::ASTContext&) ()
#2  0x00000000052916e4 in MarkVarDeclODRUsed(clang::VarDecl*, clang::SourceLocation, clang::Sema&, unsigned int const*) ()
#3  0x0000000005292194 in DoMarkVarDeclReferenced(clang::Sema&, clang::SourceLocation, clang::VarDecl*, clang::Expr*) ()
#4  0x00000000053b9a39 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformDeclRefExpr(clang::DeclRefExpr*) ()
#5  0x00000000053c0178 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) ()
#6  0x00000000053c0492 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformCompoundAssignOperator(clang::CompoundAssignOperator*) ()
#7  0x00000000053c0178 in clang::TreeTransform<(anonymous namespace)::TransformTypos>::TransformBinaryOperator(clang::BinaryOperator*) ()
#8  0x000000000538521b in (anonymous namespace)::TransformTypos::RecursiveTransformLoop(clang::Expr*, bool&) ()
#9  0x000000000538634a in clang::Sema::CorrectDelayedTyposInExpr(clang::Expr*, clang::VarDecl*, bool, llvm::function_ref<clang::ActionResult<clang::Expr*, true> (clang::Expr*)>) ()
#10 0x0000000005387971 in clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) ()
#11 0x0000000004f0e6b1 in clang::Parser::ParseForStatement(clang::SourceLocation*) ()
#12 0x0000000004f09e12 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#13 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#14 0x0000000004f0fbc1 in clang::Parser::ParseCompoundStatementBody(bool) ()
#15 0x0000000004f10124 in clang::Parser::ParseCompoundStatement(bool, unsigned int) ()
#16 0x0000000004f09a46 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#17 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#18 0x0000000004f0a702 in clang::Parser::ParseStatement(clang::SourceLocation*, clang::Parser::ParsedStmtContext) ()
#19 0x0000000004f0cd0f in clang::Parser::ParseIfStatement(clang::SourceLocation*) ()
#20 0x0000000004f09f02 in clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) ()
#21 0x0000000004f0a428 in clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) ()
#22 0x0000000004f0fbc1 in clang::Parser::ParseCompoundStatementBody(bool) ()
#23 0x0000000004f11e1a in clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) ()
#24 0x0000000004e5c473 in clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) ()
#25 0x0000000004e5c16d in clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) ()
#26 0x0000000004e9f79b in clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) ()
#27 0x0000000004ea188d in clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) ()
#28 0x0000000004e7dc81 in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) ()
#29 0x0000000004e52c6f in clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) ()
#30 0x0000000004e53411 in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) [clone .part.0] ()
#31 0x0000000004e599b0 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#32 0x0000000004e99489 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#33 0x0000000004e99fba in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
#34 0x0000000004e84c13 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) ()
#35 0x0000000004e593d3 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#36 0x0000000004e99489 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#37 0x0000000004e993c4 in clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) ()
#38 0x0000000004e99fba in clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ()
#39 0x0000000004e84c13 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) ()
#40 0x0000000004e593d3 in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) ()
#41 0x0000000004e5a838 in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) ()
#42 0x0000000004e4dc69 in clang::ParseAST(clang::Sema&, bool, bool) ()
#43 0x0000000003ec92e8 in clang::CodeGenAction::ExecuteAction() ()
#44 0x00000000037f06a9 in clang::FrontendAction::Execute() ()
#45 0x0000000003791f8e in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#46 0x00000000038c17f0 in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) ()
#47 0x0000000000a3f494 in cc1_main(llvm::ArrayRef<char const*>, char const*, void*) ()
#48 0x0000000000a3bca8 in ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) ()
#49 0x0000000000976c06 in main ()
```
