### ISSUE TITLE
Clang14/RISCV64 backend segfaults compiling glib-2.0

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#53662]
Attached is the testcase which is causing the compiler to segfault when cross compiling to RISCV64 target

```

0.      Program arguments: /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0/recipe-sysroot-native/usr/bin/clang-14 -cc1 -triple riscv64-yoe-linux-musl -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name gtyp
e.c -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -relaxed-aliasing -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +m -target-feature +a -target-feature +f -target-feature +d -target-feature +c -target-feature -relax -target-feature -save-restore -target-abi lp64d -msmall-data-limit 0 -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0/build -sys-header-deps -D _FORTIFY_SOURCE=2 -D _FILE_O
FFSET_BITS=64 -D _GNU_SOURCE -D G_LOG_DOMAIN=\"GLib-GObject\" -D GOBJECT_COMPILATION -fmacro-prefix-map=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-mu
sl/glib-2.0/1_2.70.3-r0=/usr/src/debug/glib-2.0/1_2.70.3-r0 -O2 -Wformat -Wformat-security -Werror=format-security -Wall -Winvalid-pch -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wno-unused-parameter -Wno-bad-function-cast -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Werror=declaration-after-statement -Werror=format=2 -Werror=implicit-function-declaration -Werror=init-self -Werror=missing-include-dirs -Werror=missin
g-prototypes -Werror=pointer-arith -Wno-format-nonliteral -std=gnu99 -fdebug-compilation-dir=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0/build -fdebug-prefix-map=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0=/usr/src/debug/glib-2.0/1_2.70.3-r0 -fdebu
g-prefix-map=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0/recipe-sysroot= -fdebug-prefix-map=/mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux-musl/glib-2.0/1_2.70.3-r0/recipe-sysroot-native= -ferror-limit 19 -fvisibility hidden -stack-protector 2 -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c gtype-2924c3.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'gtype-2924c3.c'.
4.      Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@g_type_check_class_is_a'

````
[gtype-2924c3.tar.gz](https://github.com/llvm/llvm-project/files/8027500/gtype-2924c3.tar.gz)

**Comment by DimitryAndric** [comment]
FWIW, assertion and stack trace:

```
Assertion failed: (!NodePtr->isKnownSentinel()), function operator*, file /usr/src/contrib/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h, line 138.

Program received signal SIGABRT, Aborted.
Sent by thr_kill() from pid 63471 and user 1000.
thr_kill () at thr_kill.S:4
4       thr_kill.S: No such file or directory.
(gdb) bt
#0  thr_kill () at thr_kill.S:4
#1  0x000000080691bfd4 in __raise (s=s@entry=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x00000008069cd089 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x00000008068feea1 in __assert (func=<optimized out>, file=<optimized out>, line=<optimized out>, failedexpr=<optimized out>) at /usr/src/lib/libc/gen/assert.c:51
#4  0x0000000005a798f2 in emitEpilogue () at /usr/src/contrib/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h:138
#5  0x0000000004ace3e1 in insertPrologEpilogCode () at /usr/src/contrib/llvm-project/llvm/lib/CodeGen/PrologEpilogInserter.cpp:1146
#6  runOnMachineFunction () at /usr/src/contrib/llvm-project/llvm/lib/CodeGen/PrologEpilogInserter.cpp:252
#7  0x00000000048a419e in runOnFunction () at /usr/src/contrib/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:72
#8  0x0000000004d0f39f in runOnFunction () at /usr/src/contrib/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1434
#9  0x0000000004d15a91 in runOnModule () at /usr/src/contrib/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1480
#10 0x0000000004d0f9bb in runOnModule () at /usr/src/contrib/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1549
#11 run () at /usr/src/contrib/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:539
#12 0x0000000002cafdd4 in RunCodegenPipeline () at /usr/src/contrib/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1535
#13 EmitAssembly () at /usr/src/contrib/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1565
#14 EmitBackendOutput () at /usr/src/contrib/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1728
#15 0x0000000002f9e1e3 in HandleTranslationUnit () at /usr/src/contrib/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:370
#16 0x00000000034d3e84 in ParseAST () at /usr/src/contrib/llvm-project/clang/lib/Parse/ParseAST.cpp:171
#17 0x0000000002eda72f in Execute () at /usr/src/contrib/llvm-project/clang/lib/Frontend/FrontendAction.cpp:967
#18 0x0000000002e6ea2f in ExecuteAction () at /usr/src/contrib/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1036
#19 0x0000000002f97726 in ExecuteCompilerInvocation () at /usr/src/contrib/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:263
#20 0x000000000246a1a5 in cc1_main () at /usr/src/contrib/llvm-project/clang/tools/driver/cc1_main.cpp:248
#21 0x00000000024776e5 in ExecuteCC1Tool () at /usr/src/contrib/llvm-project/clang/tools/driver/driver.cpp:317
#22 0x00000000024774a0 in main () at /usr/src/contrib/llvm-project/clang/tools/driver/driver.cpp:388
```

**Comment by DimitryAndric** [comment]
@tstellar I think we should consider reverting 5ebdb07e7eb366c20fa2d914e07a4d380975f266 for 14.0.0, if this does not get fixed soon?

**Comment by tstellar** [comment]
@DimitryAndric Was this reverted in main already?

**Comment by DimitryAndric** [comment]
Hmm, not to my knowledge; it probably should be...

**Comment by tstellar** [comment]
@DimitryAndric Yeah, if you can revert it from trunk then we can just cherry-pick that commit back.

**Comment by asb** [comment]
Sorry for the slow response, I've been a bit out of action this week. I think reverting from trunk and the 14.x branch is a reasonable move for the time being.

**Comment by DimitryAndric** [comment]
Reverted in 7af3d4ab3d5da07256e1a7a0438e7308e14b9fd5. I'm letting this bake for a little while to look for bot feedback, then we can cherry-pick it.

**Comment by tstellar** [comment]
Backport request in #53830
