### ISSUE TITLE
Scalarizer assert failure "Inconsistent vector sizes", with minimal testcase

### ISSUE THREAD

**Issue by bjacob** [llvm/llvm-project#54469]
**Testcase:** [inconsistent-vector-sizes-bug.ll](https://gist.github.com/bjacob/47c1fa440b8d0f470e435f660c1036ba). Inlined here:

```
; RUN: opt %s -passes='function(scalarizer,dce)' -scalarize-load-store -S | FileCheck %s
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"

define <64 x i32> @f1(<16 x <64 x i32>*> %src, i32 %index) {
  %1 = extractelement <16 x <64 x i32>*> %src, i32 %index
  %2 = load <64 x i32>, <64 x i32>* %1, align 4
  ret <64 x i32> %2
}
```

**Steps to reproduce:**

1. Configure LLVM *with assertions enabled* (`cmake -DLLVM_ENABLE_ASSERTIONS=ON`).
2. Build `opt` (`cmake --build . --target opt`).
3. Run: `./bin/opt -passes='function(scalarizer,dce)' -scalarize-load-store -S inconsistent-vector-sizes-bug.ll`

**Expected:** should succeed.
**Actual:** assertion failure,
```
opt: /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:296: (anonymous namespace)::Scatterer::Scatterer(llvm::BasicBlock *, BasicBlock::iterator, llvm::Value *, llvm::Type *, (anonymous namespace)::ValueVector *): Assertion `Size == CachePtr->size() && "Inconsistent vector sizes"' failed.
```

**GDB session:**

```
# Starting the testcase in GDB

$ gdb --args ./bin/opt -passes='function(scalarizer,dce)' -scalarize-load-store -S /tmp/inconsistent-vector-sizes-bug.ll 

# Setting my breakpoints. My git state is at commit 8361c5da30588d3d4a48eae648f53be1feb5cfad
# so the line numbers is Scalarizer.cpp correspond to this:
# https://sourcegraph.com/github.com/llvm/llvm-project@8361c5da30588d3d4a48eae648f53be1feb5cfad/-/blob/llvm/lib/Transforms/Scalar/Scalarizer.cpp

# Set breakpoint 1 in ScalarizerVisitor::gather just where it's updating its cache.
# https://sourcegraph.com/github.com/llvm/llvm-project@8361c5da30588d3d4a48eae648f53be1feb5cfad/-/blob/llvm/lib/Transforms/Scalar/Scalarizer.cpp?L435
(gdb) b Scalarizer.cpp:435
Breakpoint 1 at 0x4b6b130: file /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp, line 435.

# Set Breakpoint 2 in ScalarizerVisitor::scatter just where it's going to construct a new Scatterer
# https://sourcegraph.com/github.com/llvm/llvm-project@8361c5da30588d3d4a48eae648f53be1feb5cfad/-/blob/llvm/lib/Transforms/Scalar/Scalarizer.cpp?L403
(gdb) b 403
Breakpoint 2 at 0x4b6a988: file /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp, line 403.


(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/local/google/home/benoitjacob/mlir-build/bin/opt -passes=function\(scalarizer,dce\) -scalarize-load-store -S /tmp/inconsistent-vector-sizes-bug.ll
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, (anonymous namespace)::ScalarizerVisitor::gather (this=0x7fffffffa2e0, Op=0x5fc8070, CV=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:435
435	  SV = CV;
(gdb) bt 4
#0  (anonymous namespace)::ScalarizerVisitor::gather (this=0x7fffffffa2e0, Op=0x5fc8070, CV=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:435
#1  0x0000000004b7080f in (anonymous namespace)::ScalarizerVisitor::visitExtractElementInst (this=0x7fffffffa2e0, EEI=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:845
#2  0x0000000004b6a05d in llvm::InstVisitor<(anonymous namespace)::ScalarizerVisitor, bool>::visitExtractElement (
    this=0x7fffffffa2e0, I=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/IR/Instruction.def:214
#3  0x0000000004b69460 in llvm::InstVisitor<(anonymous namespace)::ScalarizerVisitor, bool>::visit (this=0x7fffffffa2e0, 
    I=...) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/IR/Instruction.def:214

# OK so we are handling the 'extractelement' instruction. At line 845 (frame #1) we are doing
# https://sourcegraph.com/github.com/llvm/llvm-project@8361c5da30588d3d4a48eae648f53be1feb5cfad/-/blob/llvm/lib/Transforms/Scalar/Scalarizer.cpp?L845
#   gather(&EEI, {Res});
# so we are hardcoding the fact that an extractelement extracts something of 'size 1' (that {Res} ValueVector) even if that thing has itself a nested vector length (see testcase).


(More stack frames follow...)
(gdb) p Op
$6 = (llvm::Instruction *) 0x5fc8070
(gdb) p &SV
$7 = ((anonymous namespace)::ValueVector *) 0x5fcf6d8
(gdb) p CV.size()
$8 = 1

# OK so we are associating, to the key 0x5fc8070, the value 0x5fcf6d8 which is a vector of size 1.

(gdb) c
Continuing.

Breakpoint 2, (anonymous namespace)::ScalarizerVisitor::scatter (this=0x7fffffffa2e0, Point=0x5fc8100, V=0x5fc8070, 
    PtrElemTy=0x5fc68b0)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:403
403	    return Scatterer(
(gdb) bt 4
#0  (anonymous namespace)::ScalarizerVisitor::scatter (this=0x7fffffffa2e0, Point=0x5fc8100, V=0x5fc8070, 
    PtrElemTy=0x5fc68b0)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:403
#1  0x0000000004b6bcc8 in (anonymous namespace)::ScalarizerVisitor::visitLoadInst (this=0x7fffffffa2e0, LI=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:911
#2  0x0000000004b69aed in llvm::InstVisitor<(anonymous namespace)::ScalarizerVisitor, bool>::visitLoad (
    this=0x7fffffffa2e0, I=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/IR/Instruction.def:172
#3  0x0000000004b691c5 in llvm::InstVisitor<(anonymous namespace)::ScalarizerVisitor, bool>::visit (this=0x7fffffffa2e0, 
    I=...) at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/IR/Instruction.def:172
(More stack frames follow...)

# OK so we are now handling the 'load' instruction in the testcase.

(gdb) p V
$9 = (llvm::Value *) 0x5fc8070

# OK, that is the same key 0x5fc8070 that we had inserted a cache entry for, earlier. 

(gdb) p &Scattered[V]
$10 = (std::map<llvm::Value*, llvm::SmallVector<llvm::Value*, 8>, std::less<llvm::Value*>, std::allocator<std::pair<llvm::Value* const, llvm::SmallVector<llvm::Value*, 8> > > >::mapped_type *) 0x5fcf6d8

# OK, the cached entry is still 0x5fcf6d8 that we had inserted earlier.

(gdb) p Scattered[V].size()
$11 = 1

# OK, that still has size 1 like it had earlier.

(gdb) c
Continuing.
opt: /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:296: (anonymous namespace)::Scatterer::Scatterer(llvm::BasicBlock *, BasicBlock::iterator, llvm::Value *, llvm::Type *, (anonymous namespace)::ValueVector *): Assertion `Size == CachePtr->size() && "Inconsistent vector sizes"' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt 8
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7a1e536 in __GI_abort () at abort.c:79
#2  0x00007ffff7a1e41f in __assert_fail_base (fmt=0x7ffff7b84998 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0xfc261a "Size == CachePtr->size() && \"Inconsistent vector sizes\"", 
    file=0x1424451 "/usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp", line=296, function=<optimized out>) at assert.c:92
#3  0x00007ffff7a2d212 in __GI___assert_fail (
    assertion=0xfc261a "Size == CachePtr->size() && \"Inconsistent vector sizes\"", 
    file=0x1424451 "/usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp", line=296, 
    function=0x1583778 "(anonymous namespace)::Scatterer::Scatterer(llvm::BasicBlock *, BasicBlock::iterator, llvm::Value *, llvm::Type *, (anonymous namespace)::ValueVector *)") at assert.c:101
#4  0x0000000004b6b36e in (anonymous namespace)::Scatterer::Scatterer (this=0x7fffffff9fa8, bb=0x5fc7fa0, bbi=..., 
    v=0x5fc8070, PtrElemTy=0x5fc68b0, cachePtr=0x5fcf6d8)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:296
#5  0x0000000004b6a991 in (anonymous namespace)::ScalarizerVisitor::scatter (this=0x7fffffffa2e0, Point=0x5fc8100, 
    V=0x5fc8070, PtrElemTy=0x5fc68b0)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:403
#6  0x0000000004b6bcc8 in (anonymous namespace)::ScalarizerVisitor::visitLoadInst (this=0x7fffffffa2e0, LI=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:911
#7  0x0000000004b69aed in llvm::InstVisitor<(anonymous namespace)::ScalarizerVisitor, bool>::visitLoad (
    this=0x7fffffffa2e0, I=...)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/include/llvm/IR/Instruction.def:172
(More stack frames follow...)
(gdb) frame 4
#4  0x0000000004b6b36e in (anonymous namespace)::Scatterer::Scatterer (this=0x7fffffff9fa8, bb=0x5fc7fa0, bbi=..., 
    v=0x5fc8070, PtrElemTy=0x5fc68b0, cachePtr=0x5fcf6d8)
    at /usr/local/google/home/benoitjacob/iree/third_party/llvm-project/llvm/lib/Transforms/Scalar/Scalarizer.cpp:296
296	    assert(Size == CachePtr->size() && "Inconsistent vector sizes");
(gdb) p v
$12 = (llvm::Value *) 0x5fc8070
(gdb) p CachePtr
$13 = ((anonymous namespace)::ValueVector *) 0x5fcf6d8
(gdb) p CachePtr->size()
$14 = 1

# OK, all is still as cached earlier: key=0x5fc8070 ==> value 0x5fcf6d8, ValueVector of size 1.

# So what's wrong?

(gdb) p Size
$15 = 64
(gdb) call Ty->dump()
<64 x i32>
```

**Conclusion:** There seems to be an inconsistency in the notion of 'vector size':

- `visitExtractElement` considers that whatever is being extracted, is of size 1
- `visitLoad` considers that what when a vector is being loaded, its vector size is to be honored (here 64).

**Comment by bjacob** [comment]
@bjope @nikic @LebedevRI
