### ISSUE TITLE
llvm-ar fails to handle long paths on Windows

### ISSUE THREAD

**Issue by bgamari** [llvm/llvm-project#54559]
It appears that `llvm-ar.exe` (version 13.0.1) fails to accept [long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) on Windows. For instance, `clang` can output to a long path without any trouble:

```python
#!/usr/bin/env python
from pathlib import Path
tmp = Path('/'.join('a'*32 for j in range(16)))
tmp.mkdir(True, True)
Path('hi.c').write_text('int main() { return 0; }')

import subprocess
subprocess.run(['clang', '-o', tmp / 'out.o', 'hi.c'])
```

whereas asking `ar` to write an archive to a long path fails:
```python
#!/usr/bin/env python
from pathlib import Path
tmp = Path('/'.join('a'*32 for j in range(16)))
tmp.mkdir(True, True)
Path('hi.c').write_text('int main() { return 0; }')

import subprocess
subprocess.run(['llvm-ar', 'rc', tmp / 'out.a', 'hi.c'])
```

```
$ python test.py
Traceback (most recent call last):
  File "C:\msys64\home\ben\ghc-2\test2.py", line 4, in <module>
    tmp.mkdir(True, True)
  File "C:/msys64/mingw64/lib/python3.9/pathlib.py", line 1325, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

**Comment by bgamari** [comment]
It appears that long paths are also not handled for input paths.

**Comment by RyanGlScott** [comment]
@bgamari, do the test scripts in https://github.com/llvm/llvm-project/issues/54559#issue-1181044197 actually demonstrate the bug? If I use the second, `llvm-ar`-based script, then it succeeds without any issues (using `llvm-ar-14.0.6`). I think the `Cannot create a file when that file already exists` error occurs if you run the script a second time after `out.a` has been created, which seems be an issue with Python's `pathlib` rather than anything to do with `llvm-ar`.

**Comment by bgamari** [comment]
Oh dear, good catch @RyanGlScott !

Good news that this is already fixed.

**Comment by oltolm** [comment]
Can this be closed?
