### ISSUE TITLE
memsan doesn't handle getdirentries()

### ISSUE THREAD

**Issue by ojwb** [llvm/llvm-project#54987]
It seems memsan doesn't mark the buffer which getdirentries() returns results in as initialised.

I can reproduce this with the clang-15 package in Debian experimental which is a recent snapshot:

```
Debian clang version 15.0.0-++20220309105819+8bef17ed59aa-1~exp1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Reproducer:

```
$ cat getdirentriestest.c 
#include <errno.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>

int main() {
    off_t base = 0;
    char buf[1024];
    int dir = open("/proc/self/fd", O_RDONLY|O_DIRECTORY);
    if (dir < 0) return 1;
    errno = 0;
    ssize_t c = getdirentries(dir, buf, sizeof(buf), &base);
    if (c < 0) return 2;
    ssize_t pos = 0;
    while (pos < c) {
	struct dirent *d = (struct dirent *)(buf + pos);
	printf("%s\n", d->d_name);
	pos += d->d_reclen;
    }
    return 0;
}
$ clang-15 -Wall -W -g -fsanitize=memory getdirentriestest.c
$ ./a.out 
.
==1727340==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55bc49354aa0 in main /tmp/scratch/getdirentriestest.c:17:5
    #1 0x7fee76e047fc in __libc_start_main csu/../csu/libc-start.c:332:16
    #2 0x55bc492ce2c9 in _start (/tmp/scratch/a.out+0x212c9) (BuildId: c47086e0b8c95295b0012f67c32a50c9a129ae22)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/scratch/getdirentriestest.c:17:5 in main
Exiting
```

Line 17 is `while (pos < c) {` so memsan seems to understand `d->d_name` is initialised but not `d->d_reclen`.

(If you're wondering why use `getdirentries()` at all, POSIX doesn't currently require `readdir()` to be thread-safe.)

**Comment by davidbolvansky** [comment]
readdir_r is thread safe variant of readdir.
