### ISSUE TITLE
Slow optimization of global array of structs on 32-bit architectures

### ISSUE THREAD

**Issue by jfgoog** [llvm/llvm-project#55798]
This bug was originally reported in the Android NDK as https://github.com/android/ndk/issues/1418. I have tried to significantly reduce the code compared to the original report.

[slow-compile.tar.gz](https://github.com/llvm/llvm-project/files/8807399/slow-compile.tar.gz)
[settings.ll.txt](https://github.com/llvm/llvm-project/files/8807436/settings.ll.txt)

The attached code declares a global array of structs in table/settings.h, containing about 400 elements: `const SettingDesc _settings[] = { ... }`

The code is extremely slow to compile on several architectures, but particularly bad on 32-bit ARM and x86:

```
clang++ --target=aarch64-linux-android21

real    0m19.253s
user    0m19.206s
sys     0m0.044s


clang++ --target=x86_64-linux-android21

real    0m20.832s
user    0m20.642s
sys     0m0.188s


clang++ --target=armv7a-linux-android21

real    4m53.908s
user    4m53.748s
sys     0m0.088s


clang++ --target=i686-linux-android21

real    1m22.726s
user    1m22.565s
sys     0m0.149s
```

The slowness only occurs when optimizing. It appears to be related to trying to optimize the special function `__cxx_global_var_init`. Unfortunately, because this function does exist explicitly in the code, there is no way to set the `optnone` attribute on it.

I collected the following timing data for arm32 (for brevity, only including the parts that account for the huge amount of time):

```
===-------------------------------------------------------------------------===
                         Miscellaneous Ungrouped Timers
===-------------------------------------------------------------------------===

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  296.1065 (100.0%)   0.0817 ( 95.7%)  296.1882 (100.0%)  296.2507 (100.0%)  Code Generation Time
   0.0427 (  0.0%)   0.0036 (  4.3%)   0.0463 (  0.0%)   0.0470 (  0.0%)  LLVM IR Generation Time
  296.1492 (100.0%)   0.0854 (100.0%)  296.2346 (100.0%)  296.2977 (100.0%)  Total

===-------------------------------------------------------------------------===
                      Instruction Selection and Scheduling
===-------------------------------------------------------------------------===
  Total Execution Time: 295.7564 seconds (295.8187 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  292.1253 ( 98.8%)   0.0280 ( 87.5%)  292.1533 ( 98.8%)  292.2149 ( 98.8%)  DAG Combining after legalize types
   1.3959 (  0.5%)   0.0000 (  0.0%)   1.3959 (  0.5%)   1.3961 (  0.5%)  DAG Combining 1
   1.3061 (  0.4%)   0.0040 ( 12.5%)   1.3101 (  0.4%)   1.3105 (  0.4%)  Instruction Scheduling
   0.8146 (  0.3%)   0.0000 (  0.0%)   0.8146 (  0.3%)   0.8147 (  0.3%)  DAG Combining 2
   0.0390 (  0.0%)   0.0000 (  0.0%)   0.0390 (  0.0%)   0.0390 (  0.0%)  Type Legalization
   0.0200 (  0.0%)   0.0000 (  0.0%)   0.0200 (  0.0%)   0.0201 (  0.0%)  Instruction Selection
   0.0094 (  0.0%)   0.0000 (  0.0%)   0.0094 (  0.0%)   0.0094 (  0.0%)  Instruction Creation
   0.0079 (  0.0%)   0.0000 (  0.0%)   0.0079 (  0.0%)   0.0079 (  0.0%)  Vector Legalization
   0.0060 (  0.0%)   0.0000 (  0.0%)   0.0060 (  0.0%)   0.0060 (  0.0%)  DAG Legalization
   0.0003 (  0.0%)   0.0000 (  0.0%)   0.0003 (  0.0%)   0.0003 (  0.0%)  Instruction Scheduling Cleanup
  295.7244 (100.0%)   0.0320 (100.0%)  295.7564 (100.0%)  295.8187 (100.0%)  Total

===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 295.9915 seconds (296.0539 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  295.7507 ( 99.9%)   0.0358 ( 49.8%)  295.7864 ( 99.9%)  295.8489 ( 99.9%)  ARM Instruction Selection
<everything else in this section deleted>
  295.9198 (100.0%)   0.0717 (100.0%)  295.9915 (100.0%)  296.0539 (100.0%)  Total

===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 296.3532 seconds (296.4156 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  296.2545 (100.0%)   0.0986 (100.0%)  296.3532 (100.0%)  296.4156 (100.0%)  Clang front-end timer
  296.2545 (100.0%)   0.0986 (100.0%)  296.3532 (100.0%)  296.4156 (100.0%)  Total
```

**Comment by jfgoog** [comment]
One possibility is that the compiler is failing to properly inline an overloaded `operator |`, even though it is marked `inline`:

```C++
inline SettingGuiFlag operator | (SettingGuiFlag m1, SettingGuiFlag m2) {return (SettingGuiFlag)(m1 | m2);}
```

If I remove this, and instead put the cast in `#define NSD_GENERAL`, by replacing `guiflags` with `(SettingGuiFlag)(guiflags)`, then the LLVM IR no longer has the `__cxx_global_var_init` function and compilation is fast:

```
clang++ --target=aarch64-linux-android21

real    0m19.253s
user    0m19.206s
sys     0m0.044s


clang++ --target=x86_64-linux-android21

real    0m20.832s
user    0m20.642s
sys     0m0.188s


clang++ --target=armv7a-linux-android21

real    4m53.908s
user    4m53.748s
sys     0m0.088s


clang++ --target=i686-linux-android21

real    1m22.726s
user    1m22.565s
sys     0m0.149s
```

**Comment by nikic** [comment]
> One possibility is that the compiler is failing to properly inline an overloaded `operator |`, even though it is marked `inline`:
> 
> ```c++
> inline SettingGuiFlag operator | (SettingGuiFlag m1, SettingGuiFlag m2) {return (SettingGuiFlag)(m1 | m2);}
> ```
> 
> If I remove this, and instead put the cast in `#define NSD_GENERAL`, by replacing `guiflags` with `(SettingGuiFlag)(guiflags)`, then the LLVM IR no longer has the `__cxx_global_var_init` function and compilation is fast:

In your IR, this function is compiled to:
```
; Function Attrs: inlinehint mustprogress
define linkonce_odr dso_local noundef zeroext i16 @_Zor14SettingGuiFlagS_(i16 noundef zeroext %0, i16 noundef zeroext %1) local_unnamed_addr #2 comdat {
  %3 = call noundef zeroext i16 @_Zor14SettingGuiFlagS_(i16 noundef zeroext %0, i16 noundef zeroext %1)
  ret i16 %3
}
```
That is, a call to itself. And indeed, doesn't your `operator|` recurse infinitely? Is it missing a cast of `m1`/`m2` to an integer type?

**Comment by jfgoog** [comment]
In the original code, there was a helper for enum bitsets:

```C++
# define DECLARE_ENUM_AS_BIT_SET(mask_t) \
	inline mask_t operator | (mask_t m1, mask_t m2) {return (mask_t)((std::underlying_type<mask_t>::type)m1 | m2);} \
	inline mask_t operator & (mask_t m1, mask_t m2) {return (mask_t)((std::underlying_type<mask_t>::type)m1 & m2);} \
	inline mask_t operator ^ (mask_t m1, mask_t m2) {return (mask_t)((std::underlying_type<mask_t>::type)m1 ^ m2);} \
	inline mask_t& operator |= (mask_t& m1, mask_t m2) {m1 = m1 | m2; return m1;} \
	inline mask_t& operator &= (mask_t& m1, mask_t m2) {m1 = m1 & m2; return m1;} \
	inline mask_t& operator ^= (mask_t& m1, mask_t m2) {m1 = m1 ^ m2; return m1;} \
	inline mask_t operator ~(mask_t m) {return (mask_t)(~(std::underlying_type<mask_t>::type)m);}
```

and then `DECLARE_ENUM_AS_BIT_SET(SettingGuiFlag)`

In trying to streamline the code, I was trying to preserve the slow compile. I've never actually executed it.

I changed `operator |` as follows to be more faithful to the original bug report:

`inline SettingGuiFlag operator | (SettingGuiFlag m1, SettingGuiFlag m2) {return (SettingGuiFlag)((uint16)m1 | m2);}`

When I do this, the function definition for `_Zor14SettingGuiFlagS_` goes away in the IR, and `__cxx_global_var_init` changes so as to not call it. But the compile performance is still slow.

**Comment by efriedma-quic** [comment]
Given all the time is spent in "DAG Combining after legalize types", it's probably some quadratic-time algorithm.  I would guess trying to form post-increment stores; we've had issues with that in the past, and I'm not sure it was ever properly fixed.

**Comment by jfgoog** [comment]
I did a very rough analysis of the time dependence of the number of array elements. Above ~150 elements, it was N^5 or N^6. I can post some graphs if you're interested.

**Comment by yurai007** [comment]
Indeed CodeGen stuck in stores visiting, more precisely in DAGCombiner::mergeConsecutiveStores call:

#3  0x00005618ca19ea35 in (anonymous namespace)::DAGCombiner::mergeConsecutiveStores (this=0x7ffe4954e968, St=0x5618cc340f88) at /home/yurai/programs/llvm-project/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:18677
#4  0x00005618ca132d10 in (anonymous namespace)::DAGCombiner::visitSTORE (this=0x7ffe4954e968, N=0x5618cc340f88) at /home/yurai/programs/llvm-project/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:19014
#5  0x00005618ca0e67c5 in (anonymous namespace)::DAGCombiner::visit (this=0x7ffe4954e968, N=0x5618cc340f88) at /home/yurai/programs/llvm-project/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1733
#6  0x00005618ca0e5891 in (anonymous namespace)::DAGCombiner::combine (this=0x7ffe4954e968, N=0x5618cc340f88) at /home/yurai/programs/llvm-project/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1773
#7  0x00005618ca0e4d9c in (anonymous namespace)::DAGCombiner::Run (this=0x7ffe4954e968, AtLevel=llvm::AfterLegalizeTypes) at /home/yurai/programs/llvm-project/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1572

With -combiner-store-merging=0 DAGCombiner finish (almost) immediately. I thought it could be about https://github.com/llvm/llvm-project/issues/53826. But in fact, that excessive compile time issue may be more related to https://github.com/llvm/llvm-project/issues/52858. After reverting d6351340bb9bf7703fb79629efdba5886d434694 locally combining time drops to normal level and llc quickly finish his job.

**Comment by dwblaikie** [comment]
For the original code, making the array constexpr (& making whatever's necessary, like op| constexpr too) might solve the issue by forcing the compiler frontend to do all the work in turning things into a constant.

Still, slow compile might be worth addressing anyway.
