### ISSUE TITLE
Failed to submit result to LNT server

### ISSUE THREAD

**Issue by yinyangsx** [llvm/llvm-project#55981]
I got the an error as below after I updated os of my bot from Ubuntu1604 to Ubuntu 2004. I really don't know how to fix it. Anyone can help me? thanks!

```console
2022-06-10 12:07:26: submitting result to 'http://lnt.llvm.org/submitRun'
error: lnt server: import failure: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.
Traceback (most recent call last):
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/util/ImportData.py", line 109, in import_and_report
    merge_run=merge_run)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 1077, in importDataFromDict
    select_machine)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 866, in _getOrCreateMachine
    name))
MachineInfoChanged: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.
Note: Use --select-machine=update to update the existing machine information.
2022-06-10 12:07:27 CRITICAL: Results were not obtained from submission.
```

**Comment by fhahn** [comment]
> Note: Use --select-machine=update to update the existing machine information.


I think you need to use the above to update the machine info.

**Comment by fhahn** [comment]
@yinyangsx please re-open the issue with additional info if the above doesn't work

**Comment by yinyangsx** [comment]
Hi @fhahn , thank you for replying. I tried to run command with option "--select-machine=update" manually, but it doesn't work.
Here is the command I used
/var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/python /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/lnt runtest nt --no-timestamp --sandbox /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox --test-suite /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/test-suite --cc /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang --cxx /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang++ --cflag -march=broadwell --threads=1 --build-threads=80 --use-perf --benchmarking-only --multisample=4 --exclude-stat-from-submission=compile --submit http://lnt.llvm.org/submitRun --no-machdep-info LNT-Broadwell-AVX2-O3 --select-machine=update

**Comment by fhahn** [comment]
> , but it doesn't work.

@yinyangsx can you provide details what doesn't work?

**Comment by yinyangsx** [comment]
This is my build from staging master, https://lab.llvm.org/staging/#/builders/6/builds/1554
From this build we can see the build failed to upload result with below errors,
2022-06-12 21:50:05: submitting result to 'http://lnt.llvm.org/submitRun'
error: lnt server: import failure: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.
Traceback (most recent call last):
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/util/ImportData.py", line 109, in import_and_report
    merge_run=merge_run)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 1077, in importDataFromDict
    select_machine)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 866, in _getOrCreateMachine
    name))
MachineInfoChanged: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.
Note: Use --select-machine=update to update the existing machine information.

Then according to above error prompt, I tried to run command with option "--select-machine=update" manually, but it failed with the same error
Here is the command I run manually,
/var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/python /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/lnt runtest nt --no-timestamp --sandbox /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox --test-suite /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/test-suite --cc /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang --cxx /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang++ --cflag -march=broadwell --threads=1 --build-threads=80 --use-perf --benchmarking-only --multisample=4 --exclude-stat-from-submission=compile --submit http://lnt.llvm.org/submitRun --no-machdep-info LNT-Broadwell-AVX2-O3 --select-machine=update

Here is the error
2022-06-13 01:18:38: submitting result to 'http://lnt.llvm.org/submitRun'
error: lnt server: import failure: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.
Traceback (most recent call last):
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/util/ImportData.py", line 109, in import_and_report
    merge_run=merge_run)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 1077, in importDataFromDict
    select_machine)
  File "/srv/lnt/sandbox/local/lib/python2.7/site-packages/LNT-0.4.2.dev0-py2.7-linux-x86_64.egg/lnt/server/db/testsuitedb.py", line 866, in _getOrCreateMachine
    name))
MachineInfoChanged: 'os' on machine 'LNT-Broadwell-AVX2-O3__clang_DEV__x86_64' changed.


Note: Use --select-machine=update to update the existing machine information.

**Comment by yinyangsx** [comment]
Currently my bot submits results to LNT server with testerName "LNT-Broadwell-AVX2-O3" and it will fail with above error. Then I tried to submit result with a new testerName "LNT-Broadwell-AVX2-**O5**" manually, it works well. See http://lnt.llvm.org/db_default/v4/nts/machine/1380
Here is the command I run manually,
/var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/python /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox/bin/lnt runtest nt --no-timestamp --sandbox /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/sandbox --test-suite /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/test/test-suite --cc /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang --cxx /var/lib/buildbot/workers/default/clang-cmake-x86_64-avx2-linux-perf/stage1.install/bin/clang++ --cflag -march=broadwell --threads=1 --build-threads=80 --use-perf --benchmarking-only --multisample=4 --exclude-stat-from-submission=compile --submit http://lnt.llvm.org/submitRun --no-machdep-info **LNT-Broadwell-AVX2-O5**

So, in order to fix this issue, can I submit results to LNT server with a new testerName? if so, I will change the configuration of my build, https://github.com/llvm/llvm-zorg/blob/c744ef8bd3629a023a3958525aaf41b0be906528/buildbot/osuosl/master/config/builders.py#L703

**Comment by yinyangsx** [comment]
@fhahn , any comments?

**Comment by fhahn** [comment]
@yinyangsx sorry for the silence, has this been fixed by your patch?
