### ISSUE TITLE
[clang]print in run-find-all-symbols.py file does not support python3

### ISSUE THREAD

**Issue by nora-pxh** [llvm/llvm-project#55996]
```console
Error compiling /usr/share/clang/run-find-all-symbols.py'...
  File "/usr/share/clang/run-find-all-symbols.py", line 42
    print 'Error: could not find compilation database.'

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Error: could not find compilation database.')?
```

**Comment by willcharlton** [comment]
I am experiencing the same issue:

```
***   File "~/.buildozer/android/app/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/share/clang/run-find-all-symbols.py", line 42
    print 'Error: could not find compilation database.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Error: could not find compilation database.')?
```

**Comment by PatriotRossii** [comment]
Phabricator: https://reviews.llvm.org/D131789

**Comment by christian-heusel** [comment]
I think this issue is not yet fully done:
```
$ python run-find-all-symbols.py
Traceback (most recent call last):
  File "/tmp/tmp.fIZhGgcvNO/run-find-all-symbols.py", line 29, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
```

Running `2to3` on the file still gives the following diff:
```diff
--- run-find-all-symbols3.py	(original)
+++ run-find-all-symbols3.py	(refactored)
@@ -26,7 +26,7 @@
 import json
 import multiprocessing
 import os
-import Queue
+import queue
 import shutil
 import subprocess
 import sys
@@ -49,7 +49,7 @@
     """Merge all symbol files (yaml) in a given directory into a single file."""
     invocation = [args.binary, "-merge-dir=" + directory, args.saving_path]
     subprocess.call(invocation)
-    print("Merge is finished. Saving results in " + args.saving_path)
+    print(("Merge is finished. Saving results in " + args.saving_path))
 
 
 def run_find_all_symbols(args, tmpdir, build_path, queue):
@@ -105,7 +105,7 @@
 
     try:
         # Spin up a bunch of tidy-launching threads.
-        queue = Queue.Queue(max_task)
+        queue = queue.Queue(max_task)
         for _ in range(max_task):
             t = threading.Thread(
                 target=run_find_all_symbols, args=(args, tmpdir, build_path, queue)
```
