### ISSUE TITLE
LLDB: test_target_modules_type fails on FreeBSD

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#56079]
```pytb
======================================================================
FAIL: test_target_modules_type (TestTargetCommand.targetCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/mgorny/llvm-project/lldb/packages/Python/lldbsuite/test/decorators.py", line 367, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/home/mgorny/llvm-project/lldb/test/API/commands/target/basic/TestTargetCommand.py", line 477, in test_target_modules_type
    self.expect("target modules lookup --type int",
  File "/usr/home/mgorny/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 2395, in expect
    self.fail(log_msg)
AssertionError: Ran command:
"target modules lookup --type int"

Got output:
4 matches found in /home/mgorny/llvm-project/build/lldb-test-build.noindex/commands/target/basic/TestTargetCommand.test_target_modules_type/b.out:
id = {0x0000013b}, name = "int", byte-size = 4, compiler_type = "int"id = {0x000007ac}, name = "int", byte-size = 4, compiler_type = "int"id = {0x00000814}, name = "int", byte-size = 4, compiler_type = "int"id = {0x000008fa}, name = "int", byte-size = 4, compiler_type = "int"


Expecting sub string: "1 match found" (was not found)
Config=x86_64-/home/mgorny/llvm-project/build/bin/clang
```

**Comment by labath** [comment]
Could this be because you have debug info for some of the code that gets linked in to the application (crt_begin and friends). The test probably needs to be relaxed to account for that.
