### ISSUE TITLE
LLDB: test_breakpoint_set_restart failure on FreeBSD

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#56082]
```pytb
======================================================================
FAIL: test_breakpoint_set_restart_dwarf (TestBreakpointSetRestart.BreakpointSetRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/mgorny/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1676, in test_method
    return attrvalue(self)
  File "/usr/home/mgorny/llvm-project/lldb/test/API/functionalities/breakpoint/breakpoint_set_restart/TestBreakpointSetRestart.py", line 47, in test_breakpoint_set_restart
    self.fail(
AssertionError: Setting a breakpoint generated an unexpected event: stopped
Config=x86_64-/home/mgorny/llvm-project/build/bin/clang
======================================================================
FAIL: test_breakpoint_set_restart_dwo (TestBreakpointSetRestart.BreakpointSetRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/mgorny/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1676, in test_method
    return attrvalue(self)
  File "/usr/home/mgorny/llvm-project/lldb/test/API/functionalities/breakpoint/breakpoint_set_restart/TestBreakpointSetRestart.py", line 47, in test_breakpoint_set_restart
    self.fail(
AssertionError: Setting a breakpoint generated an unexpected event: stopped
Config=x86_64-/home/mgorny/llvm-project/build/bin/clang
----------------------------------------------------------------------
```

IIUC correctly it's failing because it's getting a stop without a flag to automatically restart.

**Comment by mgorny** [comment]
Ok, it actually seems to be very flaky.
