### ISSUE TITLE
[OpenMP] Build failure on Ubuntu derivative (PopOS)

### ISSUE THREAD

**Issue by markdewing** [llvm/llvm-project#56594]
I get a build error on PopOS 18.04 (which is a derivative of Ubuntu)
```pytb
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

There's special code for the pip install in `openmp/libompd/gdb-plugins/CMakeLists.txt` for Ubuntu/Debian.  The OS is detected with the following code:
https://github.com/llvm/llvm-project/blob/55b556e60c06e0556f52163fd99e8779d606194e/openmp/libompd/gdb-plugin/CMakeLists.txt#L18-L20

The `/etc/os-release` file in PopOS has these strings in all uppercase or all lowercase
```desktop
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by shiltian** [comment]
Is it still an issue?

**Comment by markdewing** [comment]
This is no longer an issue.
