### ISSUE TITLE
[libcxx] libcxx.test.dsl.ConfigurationCompilationError are quite unhelpful without the compile command

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#56829]
For example, consider the following error:

```pytb
lit: /usr/lib/python3.10/site-packages/lit/TestingConfig.py:136: fatal: unable to parse config file '/tmp/portage/sys-libs/libcxx-15.0.
0.9999/work/runtimes_build-abi_x86_64.amd64/libcxx/test/lit.site.cfg', traceback: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/lit/TestingConfig.py", line 125, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/runtimes_build-abi_x86_64.amd64/libcxx/test/lit.site.cfg", line 22, in <module>
    libcxx.test.newconfig.configure(
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/newconfig.py", line 32, in configure
    actions = feature.getActions(config)
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/dsl.py", line 562, in getActions
    if not self._isSupported(config):
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/features.py", line 110, in <lambda>
    when=lambda cfg: not '_LIBCPP_HAS_NO_LOCALIZATION' in compilerMacros(cfg) and not programSucceeds(cfg, """
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/dsl.py", line 64, in f
    cache[cacheKey] = function(config, *args, **kwargs)
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/dsl.py", line 190, in programSucceeds
    programOutput(config, program, args)
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/dsl.py", line 64, in f
    cache[cacheKey] = function(config, *args, **kwargs)
  File "/tmp/portage/sys-libs/libcxx-15.0.0.9999/work/libcxx/utils/libcxx/test/dsl.py", line 169, in programOutput
    raise ConfigurationCompilationError("Failed to build program, stderr is:\n{}".format(err))
libcxx.test.dsl.ConfigurationCompilationError: Failed to build program, stderr is:
# command stderr:
/usr/bin/x86_64-pc-linux-gnu-ld: cannot find l: No such file or directory
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)

error: command failed with exit status: 1
```

It's really hard to figure out what the problem is without seeing the failing command. Could you please include the command in the error output?

**Comment by ldionne** [comment]
We've been capturing the build command and printing it for a while, so this should be resolved now.
