### ISSUE TITLE
Mismatch in retrieved floating point type across the IR

### ISSUE THREAD

**Issue by AldrinMathew** [llvm/llvm-project#57045]
The following statements always returns `Constant*` of type `FP128` instead of the provided type
```cpp
llvm::ConstantFP::get(llvm::Type::getFloatTy(ctx->llvmCtx), std::stof(strvalue));
llvm::ConstantFP::get(llvm::Type::getDoubleTy(ctx->llvmCtx), std::stod(strvalue));
```
> `strvalue` is a string representation of the floating point number.

In fact, for all variants of floating point numbers provided to the `get` function, including `BFloat`, `Half`, `X86_FP80`, `PPC_FP128` and `FP128`, the returned `Constant*` is of type `FP128`.

In order to circumvent this, I tried to cast the obtained `Constant*` using `llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateFPCast`, but that also fails

**OS**: Ubuntu 20.04 LTS
**LLVM Version**: `14.0.6`

@lattner Any comments?

**Comment by efriedma-quic** [comment]
Either your code doesn't do what you say it does, or you have a memory corruption issue.

Does your build of LLVM have assertions enabled?

**Comment by AldrinMathew** [comment]
I have two builds of LLVM. Debug build with all assertions enabled. And release build without them. Debug is used for development and release for well, releases. Assertions are enabled in the build that the above code was run on.

`ctx->llctx` is a default initialised instance of `llvm::LLVMContext`. `std::stof` and `std::stod` are standard library functions. `strvalue` is an instance of `std::string`.

I noticed the issue while handling local declarations in my language. The code generation phase has it's own type tracking system. So the variable is declared as having `f32` type in the codegen and IR phase. But the value generated by ConstantFP is of `FP128` type, so I am getting the following assertion:

```console
qat: ../lib/IR/Instructions.cpp:1488: void llvm::StoreInst::AssertOK(): Assertion `cast<PointerType>(getOperand(1)->getType()) ->isOpaqueOrPointeeTypeMatches(getOperand(0)->getType()) && "Ptr must be a pointer to Val type!"' failed.
./run: line 1: 43105 Aborted                 (core dumped) qat run test/ten.qat -o test/result
```

**Comment by AldrinMathew** [comment]
@efriedma-quic 
Then when I called the `llvm::Type::getTypeID()` function on the Constant* generated, to find the problem, it gave the output of 5 which corresponds to `llvm::Type::TypeID::FP128TyID`

**Comment by efriedma-quic** [comment]
Maybe try stepping through ConstantFloat::get() in a debugger.

**Comment by AldrinMathew** [comment]
I went through function through a debugger and it went on for 61000 lines of output (For just getting a floating point number). At that point, I got fed up and ran `finish` in lldb repeatedly. I can't attach the entire log here because the character limit is 65536, so I am attaching the file with the debug log:

https://drive.google.com/file/d/17ghdK_zRbJV9SfDA-DhNbCLht0e_7cOv/view?usp=sharing

**Comment by AldrinMathew** [comment]
@efriedma-quic 
Any updates on this? I still have this issue, after building LLVM more than 5 times in 3 different linux machines.
One doubt I have: Are all floating point numbers supported on all platforms? Or a specific floating point type is the only one supported for a platform?

**Comment by nikic** [comment]
At this layer, all floating point numbers are supported on all platforms. (They may fail to lower in the backend, but the IR doesn't care.)

**Comment by AldrinMathew** [comment]
@nikic @efriedma-quic I think this is related to #49542
The same issue occurs in Windows as well. So that is 3 versions of Ubuntu (20.04, 22.04, 21.20), PopOS 22.04 and Windows 11. The currently built LLVM version is 17.0.0, but I have been having this issue since 14.0.6. So that is 3 major releases after this was reported.
Here is target specific information:

On Linux
```ll
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
```

On Windows
```ll
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"
```

Here is the code written in my language:
```qat
pub lib math {
  pub myfn -> f64
  (angle_in_radians :: f64) [
    new pi :: f64 = 3.14.
    new var result = 0.0_f64.
    new var termIndex = 0_u64.
    loop while (termIndex < 15) [
      new var i_fac = 1_u64.
      new var factIndex = 1_u64.
      loop while (factIndex <= termIndex) [
        i_fac = i_fac * (factIndex + 1).
	factIndex = factIndex + 1.
      ]
      termIndex = termIndex + 1.
      new var coeff = 1.0.
      loop (termIndex) [
        coeff = coeff * coeff.
      ]
    ]
    give 0.0_f64.
  ]
}
```

And I get an error about the return value type:

```
test/build/llvm/file-main_lib-math.ll:38:7: error: value doesn't match function result type 'fp128'
  ret double 0.000000e+00
      ^
1 error generated.
```

And here is the resultant LLVM IR file

```ll
; ModuleID = 'math'
source_filename = "test/main.qat"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define weak fp128 @"math:myfn"(fp128 %0) {
"0_bb":
  %angle_in_radians = alloca fp128, align 16
  %pi = alloca fp128, align 16
  %result = alloca fp128, align 16
  %termIndex = alloca i64, align 8
  %i_fac = alloca i64, align 8
  %factIndex = alloca i64, align 8
  %coeff = alloca fp128, align 16
  %"711374AF73B5881291F539A94A196CAE" = alloca i64, align 8
  store fp128 %0, ptr %angle_in_radians, align 16
  store double 0x40091EB860000000, ptr %pi, align 8
  store double 0.000000e+00, ptr %result, align 8
  store i64 0, ptr %termIndex, align 8
  %1 = load i64, ptr %termIndex, align 8
  %2 = icmp ult i64 %1, 15
  br i1 %2, label %"0_bb.0_bb", label %"0_bb.2_bb"

"0_bb.0_bb":                                      ; preds = %"0_bb.1_bb", %"0_bb"
  store i64 1, ptr %i_fac, align 8
  store i64 1, ptr %factIndex, align 8
  %3 = load i64, ptr %factIndex, align 8
  %4 = load i64, ptr %termIndex, align 8
  %5 = icmp ule i64 %3, %4
  br i1 %5, label %"0_bb.0_bb.0_bb", label %"0_bb.0_bb.2_bb"

"0_bb.1_bb":                                      ; preds = %"1_bb"
  %6 = load i64, ptr %termIndex, align 8
  %7 = icmp ult i64 %6, 15
  br i1 %7, label %"0_bb.0_bb", label %"0_bb.2_bb"

"0_bb.2_bb":                                      ; preds = %"0_bb.1_bb", %"0_bb"
  ret double 0.000000e+00

"0_bb.0_bb.0_bb":                                 ; preds = %"0_bb.0_bb.1_bb", %"0_bb.0_bb"
  %8 = load i64, ptr %factIndex, align 8
  %9 = add i64 %8, 1
  %10 = load i64, ptr %i_fac, align 8
  %11 = mul i64 %10, %9
  store i64 %11, ptr %i_fac, align 8
  %12 = load i64, ptr %factIndex, align 8
  %13 = add i64 %12, 1
  store i64 %13, ptr %factIndex, align 8
  br label %"0_bb.0_bb.1_bb"

"0_bb.0_bb.1_bb":                                 ; preds = %"0_bb.0_bb.0_bb"
  %14 = load i64, ptr %factIndex, align 8
  %15 = load i64, ptr %termIndex, align 8
  %16 = icmp ule i64 %14, %15
  br i1 %16, label %"0_bb.0_bb.0_bb", label %"0_bb.0_bb.2_bb"

"0_bb.0_bb.2_bb":                                 ; preds = %"0_bb.0_bb.1_bb", %"0_bb.0_bb"
  %17 = load i64, ptr %termIndex, align 8
  %18 = add i64 %17, 1
  store i64 %18, ptr %termIndex, align 8
  store double 1.000000e+00, ptr %coeff, align 8
  %19 = load i64, ptr %termIndex, align 8
  store i64 0, ptr %"711374AF73B5881291F539A94A196CAE", align 8
  %20 = load i64, ptr %"711374AF73B5881291F539A94A196CAE", align 8
  %21 = icmp ult i64 %20, %19
  br i1 %21, label %"0_bb.0_bb.2_bb.0_bb", label %"1_bb"

"0_bb.0_bb.2_bb.0_bb":                            ; preds = %"0_bb.0_bb.2_bb.1_bb", %"0_bb.0_bb.2_bb"
  %22 = load fp128, ptr %coeff, align 16
  %23 = load fp128, ptr %coeff, align 16
  %24 = fmul fp128 %22, %23
  store fp128 %24, ptr %coeff, align 16
  br label %"0_bb.0_bb.2_bb.1_bb"

"0_bb.0_bb.2_bb.1_bb":                            ; preds = %"0_bb.0_bb.2_bb.0_bb"
  %25 = load i64, ptr %"711374AF73B5881291F539A94A196CAE", align 8
  %26 = add i64 %25, 1
  store i64 %26, ptr %"711374AF73B5881291F539A94A196CAE", align 8
  %27 = load i64, ptr %"711374AF73B5881291F539A94A196CAE", align 8
  %28 = icmp ult i64 %27, %19
  br i1 %28, label %"0_bb.0_bb.2_bb.0_bb", label %"1_bb"

"1_bb":                                           ; preds = %"0_bb.0_bb.2_bb.1_bb", %"0_bb.0_bb.2_bb"
  br label %"0_bb.1_bb"
}

!llvm.module.flags = !{!0, !1}

!0 = !{i32 1, !"Code Model", i32 1}
!1 = !{i32 2, !"SDK Version", [3 x i32] [i32 0, i32 8, i32 0]}

```

I can confirm that the AST and IR representation for `f64` returns double datatype, however the function return type is automatically changed to f128 by llvm, and so is all alloca instructions

**Comment by efriedma-quic** [comment]
I'm still 99% sure LLVM is fine, and you're doing something wrong in your compiler; there's no way LLVM is so obviously broken that it's impossible to create floating-point constants, and you're the only one who noticed.

I just thought of a specific way your could cause weird results: maybe you're linking to multiple copies of LLVM somehow?  APFloat uses equality comparisons against the address of a global constant to figure out the "semantics" of a float; if you somehow had two copies of those globals in your program, it could lead to confusing results.

**Comment by AldrinMathew** [comment]
@efriedma-quic There actually have been a change in behaviour. Now constants are the correct type as specified in the AST and the IR, but return types and allocas are always `fp128`.

I am using `llvm-config --link-static --libs` to get the libraries to link. In addition to  that, I am linking `clangBasic`, `lldCOFF`, `lldCommon`, `lldELF`, `lldMachO`, `lldMinGW`, `lldWasm`. But this issue have been there long before clang and lld libraries were linked to the project. Initially I was linking only libraries obtained from `llvm-config --libs core`

**Comment by AldrinMathew** [comment]
Here is the relevant CMake config:

```cmake
execute_process(COMMAND ${LLVM_ROOT_DIR}/bin/llvm-config --link-static --libs
		OUTPUT_VARIABLE LLVM_LIBRARIES)
add_executable(${PROJECT_NAME} qat.cpp qat_sitter.cpp memory_tracker.cpp)
add_subdirectory(cli/)
add_subdirectory(utils/)
add_subdirectory(ast/)
add_subdirectory(lexer/)
add_subdirectory(parser/)
add_subdirectory(IR/)
target_include_directories(${PROJECT_NAME} PUBLIC "${LLVM_ROOT_DIR}/include")
target_link_directories(${PROJECT_NAME} PUBLIC ast/ lexer/ parser/ utils/ cli/ IR/)
target_link_directories(${PROJECT_NAME} PRIVATE ${LLVM_ROOT_DIR}/lib)
SET(LLD_LIBRARIES lldCOFF lldCommon lldELF lldMachO lldMinGW lldWasm)
target_link_libraries(${PROJECT_NAME}
	${LLVM_LIBRARIES} ${LLD_LIBRARIES} clangBasic
	stdc++ stdc++fs rt dl pthread m z tinfo xml2
	QAT_AST QAT_LEXER QAT_PARSER QAT_IR QAT_UTILS QAT_CLI
)
```
Libraries in the subdirectory only link against other libraries within the project, there is no instance of any  individual component linking against LLVM.

**Comment by AldrinMathew** [comment]
@efriedma-quic @nikic

I found something peculiar while debugging, the address of llvm::LLVMContext instance seems to change on its own in functions like `llvm::Type::getDoubleTy`. I have printed the address whenever llvm::LLVMContext& is fetched in the compiler and it can be seen as `llctx(0x555562f89840)`, to verify that it's not caused by passing different value. That log remains same throughout the program, but the address of llvm::LLVMContext instance as received by llvm functions seems to change

```log
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
(lldb) target create "build/qat"
Current executable set to '/mnt/Main/DEV/qatlang/qat/build/qat' (x86_64).
(lldb) breakpoint set --name llvm::Type::getDoubleTy
Breakpoint 1: where = qat`llvm::Type::getDoubleTy(llvm::LLVMContext&) at Type.cpp:237:41, address = 0x00000000075f74b2
(lldb) process launch -- build test/main.qat -o test/build
Process 37945 launched: '/mnt/Main/DEV/qatlang/qat/build/qat' (x86_64)
llctx address: 0x555562f89840
Builder llctx address: 0x555562f89840
llctx(0x555562f89840)
Process 37945 stopped
* thread #1, name = 'qat', stop reason = breakpoint 1.1
    frame #0: 0x000055555cb4b4b2 qat`llvm::Type::getDoubleTy(C=0x0000555562f89820) at Type.cpp:237:41
   234  Type *Type::getHalfTy(LLVMContext &C) { return &C.pImpl->HalfTy; }
   235  Type *Type::getBFloatTy(LLVMContext &C) { return &C.pImpl->BFloatTy; }
   236  Type *Type::getFloatTy(LLVMContext &C) { return &C.pImpl->FloatTy; }
-> 237  Type *Type::getDoubleTy(LLVMContext &C) { return &C.pImpl->DoubleTy; }
   238  Type *Type::getMetadataTy(LLVMContext &C) { return &C.pImpl->MetadataTy; }
   239  Type *Type::getTokenTy(LLVMContext &C) { return &C.pImpl->TokenTy; }
   240  Type *Type::getX86_FP80Ty(LLVMContext &C) { return &C.pImpl->X86_FP80Ty; }
(lldb) finish
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::Type *) $0 = 0x0000555562f8a4a0

    frame #0: 0x000055556271e774 qat`qat::ast::CustomFloatLiteral::emit(this=0x0000555562f8f620, ctx=0x0000555562f89820) at custom_float_literal.cpp:23:56
   20       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getFloatTy(ctx->getllCtx()), std::stof(value)),
   21                                    IR::FloatType::get(IR::FloatTypeKind::_32, ctx->getllCtx()));
   22     } else if (kind == "f64") {
-> 23       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getDoubleTy(ctx->getllCtx()), std::stod(value)),
   24                                    IR::FloatType::get(IR::FloatTypeKind::_64, ctx->getllCtx()));
   25     } else if (kind == "f80") {
   26       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getX86_FP80Ty(ctx->getllCtx()), std::stod(value)),
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = breakpoint 1.1
    frame #0: 0x000055555cb4b4b2 qat`llvm::Type::getDoubleTy(C=0x000055555c893950) at Type.cpp:237:41
   234  Type *Type::getHalfTy(LLVMContext &C) { return &C.pImpl->HalfTy; }
   235  Type *Type::getBFloatTy(LLVMContext &C) { return &C.pImpl->BFloatTy; }
   236  Type *Type::getFloatTy(LLVMContext &C) { return &C.pImpl->FloatTy; }
-> 237  Type *Type::getDoubleTy(LLVMContext &C) { return &C.pImpl->DoubleTy; }
   238  Type *Type::getMetadataTy(LLVMContext &C) { return &C.pImpl->MetadataTy; }
   239  Type *Type::getTokenTy(LLVMContext &C) { return &C.pImpl->TokenTy; }
   240  Type *Type::getX86_FP80Ty(LLVMContext &C) { return &C.pImpl->X86_FP80Ty; }
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::Type *) $1 = 0x0000555562f8a4a0

    frame #0: 0x000055555cb4aadb qat`llvm::Type::getFloatingPointTy(C=0x0000555562f89840, S=0x000055555603d050) at Type.cpp:100:27
   97     else if (&S == &APFloat::IEEEsingle())
   98       Ty = Type::getFloatTy(C);
   99     else if (&S == &APFloat::IEEEdouble())
-> 100      Ty = Type::getDoubleTy(C);
   101    else if (&S == &APFloat::x87DoubleExtended())
   102      Ty = Type::getX86_FP80Ty(C);
   103    else if (&S == &APFloat::IEEEquad())
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::Type *) $2 = 0x0000555562f8a4a0

    frame #0: 0x000055555c87ada7 qat`llvm::ConstantFP::get(Context=0x0000555562f89840, V=0x00007fffffff8850) at Constants.cpp:1020:40
   1017   std::unique_ptr<ConstantFP> &Slot = pImpl->FPConstants[V];
   1018
   1019   if (!Slot) {
-> 1020     Type *Ty = Type::getFloatingPointTy(Context, V.getSemantics());
   1021     Slot.reset(new ConstantFP(Ty, V));
   1022   }
   1023
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::ConstantFP *) $3 = 0x0000555562f9bd70

    frame #0: 0x000055555c87a78a qat`llvm::ConstantFP::get(Ty=0x0000555562f8a4a0, V=0.23400000000000001) at Constants.cpp:934:20
   931    bool ignored;
   932    FV.convert(Ty->getScalarType()->getFltSemantics(),
   933               APFloat::rmNearestTiesToEven, &ignored);
-> 934    Constant *C = get(Context, FV);
   935 
   936    // For vectors, broadcast the value.
   937    if (VectorType *VTy = dyn_cast<VectorType>(Ty))
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::Constant *) $4 = 0x0000555562f9bd70

    frame #0: 0x000055556271e7b5 qat`qat::ast::CustomFloatLiteral::emit(this=0x0000555562f8f620, ctx=0x0000555562f89820) at custom_float_literal.cpp:23:34
   20       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getFloatTy(ctx->getllCtx()), std::stof(value)),
   21                                    IR::FloatType::get(IR::FloatTypeKind::_32, ctx->getllCtx()));
   22     } else if (kind == "f64") {
-> 23       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getDoubleTy(ctx->getllCtx()), std::stod(value)),
   24                                    IR::FloatType::get(IR::FloatTypeKind::_64, ctx->getllCtx()));
   25     } else if (kind == "f80") {
   26       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getX86_FP80Ty(ctx->getllCtx()), std::stod(value)),
(lldb) 
llctx(0x555562f89840)
Process 37945 stopped
* thread #1, name = 'qat', stop reason = breakpoint 1.1
    frame #0: 0x000055555cb4b4b2 qat`llvm::Type::getDoubleTy(C=0x0000555562f9bdb0) at Type.cpp:237:41
   234  Type *Type::getHalfTy(LLVMContext &C) { return &C.pImpl->HalfTy; }
   235  Type *Type::getBFloatTy(LLVMContext &C) { return &C.pImpl->BFloatTy; }
   236  Type *Type::getFloatTy(LLVMContext &C) { return &C.pImpl->FloatTy; }
-> 237  Type *Type::getDoubleTy(LLVMContext &C) { return &C.pImpl->DoubleTy; }
   238  Type *Type::getMetadataTy(LLVMContext &C) { return &C.pImpl->MetadataTy; }
   239  Type *Type::getTokenTy(LLVMContext &C) { return &C.pImpl->TokenTy; }
   240  Type *Type::getX86_FP80Ty(LLVMContext &C) { return &C.pImpl->X86_FP80Ty; }
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (llvm::Type *) $5 = 0x0000555562f8a4a0

    frame #0: 0x000055556273f4bc qat`qat::IR::FloatType::FloatType(this=0x0000555562f9bdb0, _kind=_64, llctx=0x0000555562f89840) at float.cpp:20:18
   17         llvmType = llvm::Type::getFloatTy(llctx);
   18       }
   19       case FloatTypeKind::_64: {
-> 20         llvmType = llvm::Type::getDoubleTy(llctx);
   21       }
   22       case FloatTypeKind::_80: {
   23         llvmType = llvm::Type::getX86_FP80Ty(llctx);
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
    frame #0: 0x000055556273f630 qat`qat::IR::FloatType::get(_kind=_64, llctx=0x0000555562f89840) at float.cpp:42:14
   39         }
   40       }
   41     }
-> 42     return new FloatType(_kind, llctx);
   43   }
   44  
   45   TypeKind FloatType::typeKind() const { return TypeKind::Float; }
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (qat::IR::FloatType *) $6 = 0x0000555562f9bdb0

    frame #0: 0x000055556271e7e7 qat`qat::ast::CustomFloatLiteral::emit(this=0x0000555562f8f620, ctx=0x0000555562f89820) at custom_float_literal.cpp:24:34
   21                                    IR::FloatType::get(IR::FloatTypeKind::_32, ctx->getllCtx()));
   22     } else if (kind == "f64") {
   23       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getDoubleTy(ctx->getllCtx()), std::stod(value)),
-> 24                                    IR::FloatType::get(IR::FloatTypeKind::_64, ctx->getllCtx()));
   25     } else if (kind == "f80") {
   26       return new IR::ConstantValue(llvm::ConstantFP::get(llvm::Type::getX86_FP80Ty(ctx->getllCtx()), std::stod(value)),
   27                                    IR::FloatType::get(IR::FloatTypeKind::_80, ctx->getllCtx()));
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (qat::IR::ConstantValue *) $7 = 0x0000555562f9b310

    frame #0: 0x0000555562707af0 qat`qat::ast::LocalDeclaration::emit(this=0x0000555562f8af60, ctx=0x0000555562f89820) at local_declaration.cpp:308:12
   305          }
   306        }
   307      }
-> 308      expVal = value.value()->emit(ctx);
   309      SHOW("Type of value to be assigned to local value " << name.value << " is " << expVal->getType()->toString())
   310    }
   311    SHOW("Type inference for value is complete")
(lldb) 
llctx(0x555562f89840)
llvm::StoreInst created
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (qat::IR::Value *) $8 = nullptr

    frame #0: 0x000055555cdd9be5 qat`qat::ast::emitSentences(sentences=size=1, ctx=0x0000555562f89820) at sentence.cpp:9:11
   6    void emitSentences(const Vec<Sentence*>& sentences, IR::Context* ctx) {
   7      for (auto* snt : sentences) {
   8        SHOW("Sentence nodeType is: " << (int)snt->nodeType())
-> 9        auto* irVal = snt->emit(ctx);
   10       if (irVal && irVal->getLLVM() && IR::isTerminatorInstruction(irVal->getLLVM())) {
   11         break;
   12       }
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
    frame #0: 0x000055555cdf1b2f qat`qat::ast::FunctionDefinition::emit(this=0x0000555562f8f9b0, ctx=0x0000555562f89820) at function.cpp:350:3
   347    }
   348    SHOW("Emitting sentences")
   349    emitSentences(sentences, ctx);
-> 350    SHOW("Sentences emitted")
   351    IR::functionReturnHandler(ctx, fnEmit, fileRange);
   352    return fnEmit;
   353  }
(lldb) finish
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
Return value: (qat::IR::Value *) $9 = 0x0000555562f99380

    frame #0: 0x000055555cf99b91 qat`qat::IR::QatModule::emitNodes(this=0x0000555562f94b20, ctx=0x0000555562f89820) at qat_module.cpp:1680:7
   1677       if (node) {
   1678         SHOW("Emitting node with type: " << (int)node->nodeType())
   1679         (void)node->emit(ctx);
-> 1680       }
   1681     }
   1682     SHOW("Emission for module complete")
   1683     for (auto* sub : submodules) {
(lldb) 
Process 37945 stopped
* thread #1, name = 'qat', stop reason = step out
    frame #0: 0x000055555c8482cd qat`qat::QatSitter::init(this=0x0000555562f897b0) at qat_sitter.cpp:61:23
   58       if (cfg->hasOutputPath()) {
   59         fs::remove_all(cfg->getOutputPath() / "llvm");
   60       }
-> 61       for (auto* entity : fileEntities) {
   62         ctx->mod = entity;
   63         SHOW("Calling emitNodes")
   64         entity->emitNodes(ctx);
(lldb) 
```

**Comment by AldrinMathew** [comment]
The issue has been solved on my end. Found the culprit in the codebase. Closing this.
