### ISSUE TITLE
[OpenMP][AMDGPU] no more works with rocprof

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#57536]
rocprof an application using OpenMP offload to AMDGPU.
When exiting
```gdb
double free or corruption (out)

Thread 1 "check_spo_batch" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6bb2859 in __GI_abort () at abort.c:79
#2  0x00007ffff6c1d26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6d47298 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff6c252fc in malloc_printerr (str=str@entry=0x7ffff6d49670 "double free or corruption (out)") at malloc.c:5347
#4  0x00007ffff6c26fa0 in _int_free (av=0x7ffff6d7cb80 <main_arena>, p=0x555555829980, have_lock=<optimized out>) at malloc.c:4314
#5  0x00007fffe5a2c0be in ?? () from /opt/rocm-5.2.0/lib/librocprofiler64.so
#6  0x00007fffe68f88ad in RTLDeviceInfoTy::~RTLDeviceInfoTy() () from /soft/llvm/release-15.0.0-rc3/lib/libomptarget.rtl.amdgpu.so
#7  0x00007fffe68f9249 in __tgt_rtl_deinit_plugin () from /soft/llvm/release-15.0.0-rc3/lib/libomptarget.rtl.amdgpu.so
#8  0x00007ffff6dc9d03 in deinit() () from /soft/llvm/release-15.0.0-rc3/lib/libomptarget.so.15
#9  0x00007ffff7fe0f6b in _dl_fini () at dl-fini.c:138
#10 0x00007ffff6bd68a7 in __run_exit_handlers (status=0, listp=0x7ffff6d7c718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#11 0x00007ffff6bd6a60 in __GI_exit (status=<optimized out>) at exit.c:139
#12 0x00007ffff6bb408a in __libc_start_main (main=0x55555555e080 <main>, argc=1, argv=0x7fffffffbb58, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffbb48) at ../csu/libc-start.c:342
#13 0x000055555555d55e in _start ()
```

**Comment by ye-luo** [comment]
Affecting both main and 15 release.

**Comment by tru** [comment]
Since there is no fix at this point and 15.0.0 is going to be released next week - I will move this issue to 15.0.1.

**Comment by tru** [comment]
15.0.1 window is soon closing - is there any updates on fixes here?

**Comment by jhuber6** [comment]
I believe this was caused by https://reviews.llvm.org/D130714 causing the HSA plugin to outlive some static constructor present in rocprof. We could try to revert that patch and use https://reviews.llvm.org/D131443 to side-step the issue of needing to call HSA at deconstruction. However, this would prevent device deconstructors from working.

**Comment by ye-luo** [comment]
As of today, the main remains broken and I'd like to have it fixed. About 15, I would consider it a bonus.

**Comment by ye-luo** [comment]
I'd like to see a sane fix in master before applying a fix to 15. We can remove this from 15 release blocker for now.

**Comment by ye-luo** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/292cb114b0a35da5e35eb856c29deff577c54210
