### ISSUE TITLE
compiler-rt: lit crashes if ld.gold is not found

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#57580]
If there is no `ld.gold` installed, compiler-rt's test suite crashes with the following exception:

```console
$ ninja -v -j12 -l0 check-builtins
[0/1] cd /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins && /usr/bin/python3.11 /usr/bin/lit -vv -j 12 /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/TestCases /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/Unit/I386LinuxConfig /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/Unit/X86_64LinuxConfig
lit: /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py:146: warning: Compiler lib dir != compiler-rt lib dir
Compiler libdir:     "/usr/lib/clang/15.0.0/lib/linux"
compiler-rt libdir:  "/tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/lib/linux"
lit: /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py:156: warning: COMPILER_RT_TEST_STANDALONE_BUILD_LIBS=ON, but this test suite does not support testing the just-built runtime libraries when the test compiler is configured to use different runtime libraries. Either modify this test suite to support this test configuration, or set COMPILER_RT_TEST_STANDALONE_BUILD_LIBS=OFF to test the runtime libraries included in the compiler instead.
lit: /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py:167: note: Testing using libraries in "/tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/lib/linux"
lit: /usr/lib/python3.11/site-packages/lit/TestingConfig.py:136: fatal: unable to parse config file '/tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py', traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lit/TestingConfig.py", line 125, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "/tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py", line 561, in <module>
    if is_binutils_lto_supported():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt/test/lit.common.cfg.py", line 543, in is_binutils_lto_supported
    ld_cmd = subprocess.Popen([exe, '--help'], stdout=subprocess.PIPE, env={'LANG': 'C'})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'GOLD_EXECUTABLE-NOTFOUND'

FAILED: test/builtins/CMakeFiles/check-builtins /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/CMakeFiles/check-builtins 
cd /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins && /usr/bin/python3.11 /usr/bin/lit -vv -j 12 /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/TestCases /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/Unit/I386LinuxConfig /tmp/portage/sys-libs/compiler-rt-15.0.0/work/compiler-rt-15.0.0_build/test/builtins/Unit/X86_64LinuxConfig
ninja: build stopped: subcommand failed.
```

Filed https://reviews.llvm.org/D133358 with a proposed fix.

**Comment by MaskRay** [comment]
LGTM for a 15.0.1 backport once the patch is pushed to the main branch.

**Comment by mgorny** [comment]
Pushed as ea953b9d9a65c202985a79f1f95da115829baef6
