### ISSUE TITLE
Build failure when building llvm-shlib: LLVMDemangle.lib no such file or directory

### ISSUE THREAD

**Issue by PigeonF** [llvm/llvm-project#57625]
When building llvm-15.0.0, I get an error like this

```
[1180/1297] Generating export list for LLVM-C
FAILED: Debug/libllvm-c.exports C:/path/to/llvm/llvm-project/_build/Debug/libllvm-c.exports
cmd.exe /C "cd /D C:\path\to\llvm\llvm-project\_build\tools\llvm-shlib && C:\Users\pigeon\AppData\Local\Programs\Python\Python39\python.exe C:/path/to/llvm/llvm-project/llvm/tools/llvm-shlib/gen-msvc-exports.py --libsfile C:/path/to/llvm/llvm-project/_build/Debug/libllvm-c.args --nm C:/path/to/llvm/llvm-project/_build/Debug/bin/llvm-nm.exe -o C:/path/to/llvm/llvm-project/_build/Debug/libllvm-c.exports"
C:/path/to/llvm/llvm-project/_build/Debug/bin/llvm-nm.exe: error: C:/path/to/llvm/llvm-project/_build/Debug/lib/LLVMDemangle.lib: no such file or directory
Traceback (most recent call last):
  File "C:\path\to\llvm\llvm-project\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 116, in <module>
    main()
  File "C:\path\to\llvm\llvm-project\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 112, in main
    gen_llvm_c_export(ns.output, ns.underscore, libs, ns.nm)
  File "C:\path\to\llvm\llvm-project\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 72, in gen_llvm_c_export
    check_call([nm, '-g', lib], stdout=dumpout_f)
  File "C:\Users\pigeon\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/path/to/llvm/llvm-project/_build/Debug/bin/llvm-nm.exe', '-g', 'C:/path/to/llvm/llvm-project/_build/Debug/lib/LLVMDemangle.lib']' returned non-zero exit status 1.
```

Searching the directory I found `LLVMDemangled.lib`, as I set `CMAKE_DEBUG_POSTFIX` to `d`.

I assume the problem is not adding the current build configuration postfix in https://github.com/llvm/llvm-project/blob/llvmorg-15.0.0/llvm/tools/llvm-shlib/CMakeLists.txt#L138-L140, but am not familiar enough with where the library names come from to further speculate.

I worked around this by not building the corresponding parts (i.e. setting `LLVM_BUILD_LLVM_C_DYLIB` to `OFF`)

**Comment by lshqqytiger** [comment]
I got very similar error while building LLVM Clang compiler on Windows. (llvmorg-20.1.3)
```
subprocess.CalledProcessError: Command '['path/to/llvm-project/build/bin/llvm-nm.exe', '-g', 'path/to/llvm-project/build/./lib/LLVMDemangle.lib']' returned non-zero exit status 3221225781.
```

**Comment by zsjyzx** [comment]
llvm 依赖 zlib, 将 zlib.dll 复制到 c:windowssystem32,或者C:WindowsSysWOW64

The LLVM relies on zlib to copy the zlib.dll to c:\windows\system32, or C:\Windows\SysWOW64
