### ISSUE TITLE
Crash Report/Package Manager

### ISSUE THREAD

**Issue by VanishPoint13** [llvm/llvm-project#57728]
App Name: Package Manager
Package Name: com.smartpack.packagemanager
App Version: v6.5
SDK Version: 31

Crash Report

```console
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:258)
	at m2.c.H(Unknown Source:0)
	at i2.c.a(Unknown Source:9)
	at f2.a.d(:1)
	at f2.a.c(Unknown Source:5)
	at z1.s.e(:1)
	at y1.e.E(:6)
	at androidx.fragment.app.Fragment.N(Unknown Source:15)
	at androidx.fragment.app.p.T(:31)
	at androidx.fragment.app.p.R(:1)
	at androidx.fragment.app.a.h(:2)
	at androidx.fragment.app.p.D(:7)
	at androidx.fragment.app.p.a0(Unknown Source:84)
	at androidx.fragment.app.p.C(Unknown Source:30)
	at androidx.fragment.app.u.b(:2)
	at androidx.viewpager.widget.ViewPager.q(:8)
	at androidx.viewpager.widget.ViewPager.onMeasure(:1)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

Steps to reproduce the issue:

**Comment by EugeneZelenko** [comment]
Could you please explain, how this relates to LLVM project?
