### ISSUE TITLE
win32 + `-flto` + ASAN = ODR violation or bug?

### ISSUE THREAD

**Issue by croepha** [llvm/llvm-project#58248]
```
// odr-dll0.cpp
#include <stdio.h>

void dll0() {
      printf("dll0\n");
}

// odr-dll1.cpp
#include <stdarg.h>
#include <stdio.h>

void dll1(char const * fmt, ...) {
    char buf[2048];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof buf, fmt, ap);
}

// odr-main.cpp
#include <stdio.h>
#include <windows.h>

int main () {
    printf("main\n");
    // crashes here...
    auto handle = LoadLibraryA("odr.dll");
}

// build.bat
clang -fsanitize=address -c -flto odr-dll0.cpp -o odr-dll0.o
clang -fsanitize=address -c -flto odr-dll1.cpp -o odr-dll1.o
clang -fsanitize=address -shared -fuse-ld=lld -flto  odr-dll0.o odr-dll1.o -o odr.dll
clang -fsanitize=address -c odr-main.cpp -o odr-main.o  
clang -fsanitize=address -fuse-ld=lld  odr-main.o -o odr.exe 
./odr.exe
```
Output:
```
PS C:\projects\hello-world> .\odr.exe
main
=================================================================
==52800==ERROR: AddressSanitizer: odr-violation (0x7ff943089940):
  [1] size=8 'unsigned __int64 `extern "C" __local_stdio_printf_options'::`2'::_OptionsStorage' odr-dll0.cpp
  [2] size=8 'unsigned __int64 `extern "C" __local_stdio_printf_options'::`2'::_OptionsStorage' odr-dll1.cpp
These globals were registered at these points:
  [1]:
    #0 0x7ff63d2229fd in __asan_register_globals C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_globals.cpp:356
    #1 0x7ff943036524 in __sanitizer::atomic_load C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_atomic_clang_x86.h:37
    #2 0x7ff943036524 in __sanitizer::atomic_load_relaxed C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_atomic.h:76
    #3 0x7ff943036524 in __sanitizer::Mutex::Unlock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_mutex.h:230
    #4 0x7ff943036524 in __sanitizer::ThreadRegistry::Unlock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_thread_registry.h:100
    #5 0x7ff943036524 in __sanitizer::GenericScopedLock<__sanitizer::ThreadRegistry>::~GenericScopedLock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_mutex.h:386
    #6 0x7ff943036524 in __sanitizer::ThreadRegistry::GetNumberOfThreads(unsigned __int64 *, unsigned __int64 *, unsigned __int64 *) C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_thread_registry.cpp:129
    #7 0x7ff94300eb15 in __asan::FakeStack::FlagsOffset C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.h:94
    #8 0x7ff94300eb15 in __asan::FakeStack::GetFlags C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.h:108
    #9 0x7ff94300eb15 in __asan::FakeStack::Allocate C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:95
    #10 0x7ff94300eb15 in __asan::OnMalloc C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:211
    #11 0x7ff94300eb15 in __asan_stack_malloc_2 C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:257
    #12 0x7ff94300ecff in __asan::SetShadow C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:34
    #13 0x7ff94300ecff in __asan::OnMallocAlways C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:228
    #14 0x7ff94300ecff in __asan_stack_malloc_always_2 C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:257
    #15 0x7ff9903bff06  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003ff06)
    #16 0x7ff9903f2f2d  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180072f2d)
    #17 0x7ff9903f2cdd  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180072cdd)
    #18 0x7ff9903cdb3a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18004db3a)
    #19 0x7ff9903bbafe  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003bafe)
    #20 0x7ff9903c4dfb  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180044dfb)
    #21 0x7ff9903baeb5  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003aeb5)
    #22 0x7ff98dbf3ec1  (C:\WINDOWS\System32\KERNELBASE.dll+0x180033ec1)
    #23 0x7ff98dc3b4f0  (C:\WINDOWS\System32\KERNELBASE.dll+0x18007b4f0)
    #24 0x7ff98dc37f6e  (C:\WINDOWS\System32\KERNELBASE.dll+0x180077f6e)
    #25 0x7ff63d25e6ec in main (C:\projects\hello-world\odr.exe+0x14004e6ec)
    #26 0x7ff63d25f693 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #27 0x7ff63d25f693 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #28 0x7ff98ed154df  (C:\WINDOWS\System32\KERNEL32.DLL+0x1800154df)
    #29 0x7ff99038485a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18000485a)
  [2]:
    #0 0x7ff63d2229fd in __asan_register_globals C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_globals.cpp:356
    #1 0x7ff943036524 in __sanitizer::atomic_load C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_atomic_clang_x86.h:37
    #2 0x7ff943036524 in __sanitizer::atomic_load_relaxed C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_atomic.h:76
    #3 0x7ff943036524 in __sanitizer::Mutex::Unlock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_mutex.h:230
    #4 0x7ff943036524 in __sanitizer::ThreadRegistry::Unlock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_thread_registry.h:100
    #5 0x7ff943036524 in __sanitizer::GenericScopedLock<__sanitizer::ThreadRegistry>::~GenericScopedLock C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_mutex.h:386
    #6 0x7ff943036524 in __sanitizer::ThreadRegistry::GetNumberOfThreads(unsigned __int64 *, unsigned __int64 *, unsigned __int64 *) C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_thread_registry.cpp:129
    #7 0x7ff94300eb15 in __asan::FakeStack::FlagsOffset C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.h:94
    #8 0x7ff94300eb15 in __asan::FakeStack::GetFlags C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.h:108
    #9 0x7ff94300eb15 in __asan::FakeStack::Allocate C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:95
    #10 0x7ff94300eb15 in __asan::OnMalloc C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:211
    #11 0x7ff94300eb15 in __asan_stack_malloc_2 C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:257
    #12 0x7ff94300ecff in __asan::SetShadow C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:34
    #13 0x7ff94300ecff in __asan::OnMallocAlways C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:228
    #14 0x7ff94300ecff in __asan_stack_malloc_always_2 C:\src\llvm_package_15.0.1\llvm-project\compiler-rt\lib\asan\asan_fake_stack.cpp:257
    #15 0x7ff9903bff06  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003ff06)
    #16 0x7ff9903f2f2d  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180072f2d)
    #17 0x7ff9903f2cdd  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180072cdd)
    #18 0x7ff9903cdb3a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18004db3a)
    #19 0x7ff9903bbafe  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003bafe)
    #20 0x7ff9903c4dfb  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x180044dfb)
    #21 0x7ff9903baeb5  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18003aeb5)
    #22 0x7ff98dbf3ec1  (C:\WINDOWS\System32\KERNELBASE.dll+0x180033ec1)
    #23 0x7ff98dc3b4f0  (C:\WINDOWS\System32\KERNELBASE.dll+0x18007b4f0)
    #24 0x7ff98dc37f6e  (C:\WINDOWS\System32\KERNELBASE.dll+0x180077f6e)
    #25 0x7ff63d25e6ec in main (C:\projects\hello-world\odr.exe+0x14004e6ec)
    #26 0x7ff63d25f693 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #27 0x7ff63d25f693 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #28 0x7ff98ed154df  (C:\WINDOWS\System32\KERNEL32.DLL+0x1800154df)
    #29 0x7ff99038485a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18000485a)

==52800==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'unsigned __int64 `extern "C" __local_stdio_printf_options'::`2'::_OptionsStorage' at odr-dll0.cpp
==52800==ABORTING
PS C:\projects\hello-world>
```
Have I hit some strange bug or am I doing something wrong?  If I turn off `-flto` on `odr-dll1.cpp` then I don't hit this problem..

**Comment by croepha** [comment]
Googling around, it looks like people suggest adding this `-mllvm -asan-use-private-alias=1 `

but when I do that I get this:
```
clang: warning: argument unused during compilation: '-asan-use-private-alias=1' [-Wunused-command-line-argument]
```

```
PS C:\projects\hello-world> clang --version
clang version 15.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by Kojoley** [comment]
This is a Windows-specific bug.

Simplified repro:

`odr-tu.cpp`
```cpp
inline int* foo()
{
    static int data;
    return &data;
}

void dll0() {
    foo();
}
```
`odr-main.cpp`
```cpp
inline int* foo()
{
    static int data;
    return &data;
}

int main () {
    foo();
}
```

On Windows:
```
> clang++ -v
clang version 15.0.7
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
> clang++ -fsanitize=address -fuse-ld=lld -flto odr-tu.cpp odr-main.cpp -o odr.exe && .\odr.exe
=================================================================
==17268==ERROR: AddressSanitizer: odr-violation (0x7ff6aaa4bfa0):
  [1] size=4 'int `int * __cdecl foo(void)'::`2'::data' odr-tu.cpp
  [2] size=4 'int `int * __cdecl foo(void)'::`2'::data' odr-main.cpp
These globals were registered at these points:
  [1]:
    #0 0x7ff6aa0129fd in __asan_register_globals C:\src\llvm_package_15.0.7\llvm-project\compiler-rt\lib\asan\asan_globals.cpp:356
    #1 0x7ff6aa06ccde in _initterm C:\w\minkernel\crts\ucrt\src\appcrt\startup\initterm.cpp:21
    #2 0x7ff6aa04f3d8 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:256
    #3 0x7ffdcdd07613  (C:\Windows\System32\KERNEL32.DLL+0x180017613)
    #4 0x7ffdcfcc26a0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526a0)

  [2]:
    #0 0x7ff6aa0129fd in __asan_register_globals C:\src\llvm_package_15.0.7\llvm-project\compiler-rt\lib\asan\asan_globals.cpp:356
    #1 0x7ff6aa06ccde in _initterm C:\w\minkernel\crts\ucrt\src\appcrt\startup\initterm.cpp:21
    #2 0x7ff6aa04f3d8 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:256
    #3 0x7ffdcdd07613  (C:\Windows\System32\KERNEL32.DLL+0x180017613)
    #4 0x7ffdcfcc26a0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526a0)

==17268==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'int `int * __cdecl foo(void)'::`2'::data' at odr-tu.cpp
==17268==ABORTING
```

On Linux:
```
$ clang++ -v
Ubuntu clang version 15.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
$ clang++ -fsanitize=address -fuse-ld=lld -flto odr-tu.cpp odr-main.cpp -o odr && ./odr
```

**Comment by firewave** [comment]
Looks like this was previously reported in #35812.
