### ISSUE TITLE
Asan with clang reports puzzling "((ptr[0] == kCurrentStackFrameMagic) ) != (0)" while gcc doesn't

### ISSUE THREAD

**Issue by ByteYue** [llvm/llvm-project#58706]
Recently we encountered a puzzling asan report when compiling using `Ubuntu clang version 13.0.1-++20220120110844+75e33f71c2da-1~exp1~20220120230854.66`. Messages asan reports are as follows.
```
AddressSanitizer: CHECK failed: asan_thread.cpp:371 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0) (tid=68081)
    #0 0x8ac92e1 in __asan::CheckUnwind() crtstuff.c
    #1 0x8ade724 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) crtstuff.c
    #2 0x8acc95a in __asan::AsanThread::GetStackFrameAccessByAddr(unsigned long, __asan::AsanThread::StackFrameAccess*) crtstuff.c
    #3 0x8a4e563 in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) crtstuff.c
    #4 0x8a50072 in __asan::ErrorGeneric::ErrorGeneric(unsigned int, unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long) crtstuff.c
    #5 0x8ac7257 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) crtstuff.c
    #6 0x8a653c1 in vsprintf (/mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be+0x8a653c1)
    #7 0x8a66459 in __sprintf_chk (/mnt/disk1/yuejing/projects/doris/output/be/lib/doris_be+0x8a66459)
    #8 0x1730ee29 in apache::thrift::transport::TSocket::local_open() (../output/be/lib/doris_be+0x1730ee29)
    #9 0xb818303 in doris::ThriftClientImpl::open() ../be/src/util/thrift_client.cpp:30:25
......
```
After a series of debugging, we still hadn't discovered the underlying problem. Then we tried to compile the program using g++ with asan and started the program exactly the way we did before, and it turned out that the failed check had never happened anymore. It seems so weird that the asan program reacts inconsistently.

**Comment by ByteYue** [comment]
> Could this be a data-race?

Sorry for my late response. I think it 's possible, i'll try to compile the program using tsan to check it out. Thanks a lot.

**Comment by ByteYue** [comment]
> Could this be a data-race?

Hi there, so sorry for bothering again. Last time I tried to compile with tsan, but other data races bug happended and it took some days to repair or suppress them. Then unconsciously I changed the clang version to `clang-15` and compile the program using it. No matter tsan/asan the problem seems it never occurs. Is't so confusing.
