### ISSUE TITLE
UBSAN errors in TableGen (GlobalISelEmitter.cpp:6154:17: runtime error: downcast of address 0x60c514b0 which does not point to an object of type 'RuleMatcher')

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#59485]
Noticed the following UBSan errors in `llvm-tblgen` from LLVM 15.0.6 when building on amd64 with GCC 12.2.1 20221210 (multilib build, so -m32/x86).

(Motivated by investigating a miscompiled `llvm-tblgen` on PPC with GCC 12 but not necessarily related. Will file a bug for that once got enough information, if the bug is on LLVM's side, but I can't rule out this issue causing it.)

```console
$ cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AArch64 -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AArch64/AArch64.td --write-if-changed -o lib/Target/AArch64/AArch64GenGlobalISel.inc -d lib/Target/AArch64/AArch64GenGlobalISel.inc.d
FAILED: lib/Target/AArch64/AArch64GenGlobalISel.inc /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/lib/Target/AArch64/AArch64GenGlobalISel.inc
cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AArch64 -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AArch64/AArch64.td --write-if-changed -o lib/Target/AArch64/AArch64GenGlobalISel.inc -d lib/Target/AArch64/AArch64GenGlobalISel.inc.d
/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154:17: runtime error: downcast of address 0x60c514b0 which does not point to an object of type 'RuleMatcher'
0x60c514b0: note: object is of type '*N12_GLOBAL__N_113SwitchMatcherE'
 41 00 00 00  fc f4 ab 58 b0 4e 44 60  c0 4e 44 60 c0 4e 44 60  30 2b 4d 60 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~
              vptr for '*N12_GLOBAL__N_113SwitchMatcherE'
    #0 0x5784adf4 in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154
    #1 0x5784c76f in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6287
    #2 0x5781e2ea in buildTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:690
    #3 0x57820fae in buildMatchTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5639
    #4 0x578a5f45 in run /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5976
    #5 0x578a5f45 in llvm::EmitGlobalISel(llvm::RecordKeeper&, llvm::raw_ostream&) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6301
    #6 0x57e16d04 in LLVMTableGenMain /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:249
    #7 0x5821614d in llvm::TableGenMain(char const*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&)) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/TableGen/Main.cpp:122
    #8 0x566d2dd6 in main /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:291
    #9 0xf73f04d8  (/usr/lib/libc.so.6+0x1f4d8)
    #10 0xf73f05ab in __libc_start_main (/usr/lib/libc.so.6+0x1f5ab)
    #11 0x566d8baa in _start (/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen+0x16bbaa)
```

```console
$ cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/X86 -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/X86/X86.td --write-if-changed -o lib/Target/X86/X86GenGlobalISel.inc -d lib/Target/X86/X86GenGlobalISel.inc.d
FAILED: lib/Target/X86/X86GenGlobalISel.inc /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/lib/Target/X86/X86GenGlobalISel.inc
cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/X86 -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/X86/X86.td --write-if-changed -o lib/Target/X86/X86GenGlobalISel.inc -d lib/Target/X86/X86GenGlobalISel.inc.d
/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154:17: runtime error: downcast of address 0x66f89d70 which does not point to an object of type 'RuleMatcher'
0x66f89d70: note: object is of type '*N12_GLOBAL__N_113SwitchMatcherE'
 41 00 00 00  fc 24 b6 58 20 9e 9f 66  2c 9e 9f 66 30 9e 9f 66  f0 af de 66 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~
              vptr for '*N12_GLOBAL__N_113SwitchMatcherE'
    #0 0x578eddf4 in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154
    #1 0x578ef76f in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6287
    #2 0x578c12ea in buildTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:690
    #3 0x578c3fae in buildMatchTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5639
    #4 0x57948f45 in run /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5976
    #5 0x57948f45 in llvm::EmitGlobalISel(llvm::RecordKeeper&, llvm::raw_ostream&) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6301
    #6 0x57eb9d04 in LLVMTableGenMain /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:249
    #7 0x582b914d in llvm::TableGenMain(char const*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&)) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/TableGen/Main.cpp:122
    #8 0x56775dd6 in main /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:291
    #9 0xf73e84d8  (/usr/lib/libc.so.6+0x1f4d8)
    #10 0xf73e85ab in __libc_start_main (/usr/lib/libc.so.6+0x1f5ab)
    #11 0x5677bbaa in _start (/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen+0x16bbaa)
```

```console
$ cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AMDGPU -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AMDGPU/AMDGPUGISel.td --write-if-changed -o lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc -d lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc.d
FAILED: lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc
cd /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86 && /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen -gen-global-isel -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AMDGPU -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/include -I/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/include -I /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/Target/AMDGPU/AMDGPUGISel.td --write-if-changed -o lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc -d lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc.d
/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154:17: runtime error: downcast of address 0x6e698660 which does not point to an object of type 'RuleMatcher'
0x6e698660: note: object is of type '*N12_GLOBAL__N_113SwitchMatcherE'
 41 00 00 00  fc 94 aa 58 b0 d6 b5 6c  bc d6 b5 6c c0 d6 b5 6c  90 11 b4 6c 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~
              vptr for '*N12_GLOBAL__N_113SwitchMatcherE'
    #0 0x57834df4 in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6154
    #1 0x5783676f in emit /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6287
    #2 0x578082ea in buildTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:690
    #3 0x5780afae in buildMatchTable /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5639
    #4 0x5788ff45 in run /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:5976
    #5 0x5788ff45 in llvm::EmitGlobalISel(llvm::RecordKeeper&, llvm::raw_ostream&) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/GlobalISelEmitter.cpp:6301
    #6 0x57e00d04 in LLVMTableGenMain /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:249
    #7 0x5820014d in llvm::TableGenMain(char const*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&)) /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/lib/TableGen/Main.cpp:122
    #8 0x566bcdd6 in main /var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm/utils/TableGen/TableGen.cpp:291
    #9 0xf741e4d8  (/usr/lib/libc.so.6+0x1f4d8)
    #10 0xf741e5ab in __libc_start_main (/usr/lib/libc.so.6+0x1f5ab)
    #11 0x566c2baa in _start (/var/tmp/portage.notmp/portage/sys-devel/llvm-15.0.6/work/llvm_build-abi_x86_32.x86/bin/llvm-tblgen+0x16bbaa)
```

**Comment by thesamesam** [comment]
I can't see these w/ LLVM 16.
