### ISSUE TITLE
`add_new_check.py` needs refactoring

### ISSUE THREAD

**Issue by beckadd** [llvm/llvm-project#59606]
When attempting to add a new check in a new (uninitialized) module, the script will continuously fail. Likewise, the script will fail if a `CMakeLists.txt` file is not present and properly boilerplated.

### Reproducible Example

```console
$ ./add_new_check.py my-module no-messy-functions
Traceback (most recent call last):
  File "/home/<user>/llvm-project/clang-tools-extra/clang-tidy/./add_new_check.py", line 595, in <module>
    main()
  File "/home/<user>/llvm-project/clang-tools-extra/clang-tidy/./add_new_check.py", line 574, in main
    if not adapt_cmake(module_path, check_name_camel):
  File "/home/<user>/llvm-project/clang-tools-extra/clang-tidy/./add_new_check.py", line 29, in adapt_cmake
    with io.open(filename, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './my-module/CMakeLists.txt'
```
This is true until there are directories for `my-module` in `clang-tidy/tests/checkers` and `clang-tools-extra/docs/clang-tidy/checks`. The appropriate error messages are produced.

### Suggested Fix

The Python script should initialize the module and notify the user that the module has been initialized in the appropriate directories. It should confirm that the user wants to initialize a new module in case they have accidentally made a typo (for example, if the user accidentally types `./add_new_check.py my-modlue no-other-functions` - a typo at my-module that should require confirmation).

I'll make a pull request with the suggested changes here soon.

**Comment by beckadd** [comment]
Actually - it looks like this could be resolved and the file cleaned up with a little refactoring. I will get back with a revised version of the code that is a bit more updated.
