### ISSUE TITLE
Failing parallel.ll test with LLVM gold plugin

### ISSUE THREAD

**Issue by RaitoBezarius** [llvm/llvm-project#61350]
I am packaging LLVM 16.0.0rc4 for [NixOS](https://nixos.org) and I am running into one unique failed test on x86_64 at the moment which is tools/gold/X86/parallel.ll.

More generally, it seems like `LD_PRELOAD=LLVMGold.so` for any non trivial program will make this program crash, more logs are here:
```
Starting program: /nix/store/k2b87dvmz4mbs3d29z9fy18ja874q4nf-bash-interactive-5.1-p16/bin/bash /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/ld.gold
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/76l4v99sk83ylfwkz8wmwrm4s8h73rhd-glibc-2.35-224/lib/libthread_db.so.1".

malloc: unknown:0: assertion botched
free: called with unallocated block argument
Aborting...
Program received signal SIGABRT, Aborted.
0x00007ffff7d44bc7 in __pthread_kill_implementation () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7d44bc7 in __pthread_kill_implementation () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
#1  0x00007ffff7cf7b46 in raise () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
#2  0x00007ffff7ce24b5 in abort () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
#3  0x000000000044781d in programming_error ()
#4  0x00000000004b5589 in internal_free.constprop ()
#5  0x00007ffff05e371f in llvm::PassRegistry::registerPass(llvm::PassInfo const&, bool) ()
   from /run/user/2024/tmp.7GeZ4sH4uv/llvm-src-16.0.0-rc4/llvm/build/lib/libLLVM-16.so
#6  0x00007ffff4344f1b in initializeScopInlinerPassOnce(llvm::PassRegistry&) ()
   from /run/user/2024/tmp.7GeZ4sH4uv/llvm-src-16.0.0-rc4/llvm/build/lib/libLLVM-16.so
#7  0x00007ffff7d48077 in __pthread_once_slow () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6
#8  0x00007ffff434505d in llvm::initializeScopInlinerPass(llvm::PassRegistry&) ()
   from /run/user/2024/tmp.7GeZ4sH4uv/llvm-src-16.0.0-rc4/llvm/build/lib/libLLVM-16.so
#9  0x00007ffff42ec2a9 in polly::initializePollyPasses(llvm::PassRegistry&) ()
   from /run/user/2024/tmp.7GeZ4sH4uv/llvm-src-16.0.0-rc4/llvm/build/lib/libLLVM-16.so
#10 0x00007ffff7fcbe1e in call_init () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/ld-linux-x86-64.so.2
#11 0x00007ffff7fcbf0c in _dl_init () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/ld-linux-x86-64.so.2
#12 0x00007ffff7fe33da in _dl_start_user () from /nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/ld-linux-x86-64.so.2
#13 0x0000000000000002 in ?? ()
#14 0x00007fffffffb412 in ?? ()
#15 0x00007fffffffb460 in ?? ()
#16 0x0000000000000000 in ?? ()
```

I wanted to understand if this is something that maintainers have already encountered or whether I should investigate more with debug builds and all.

Thank you in advance!

**Comment by lorenz** [comment]
`malloc: unknown:0: assertion botched` indicates quite severe memory corruption, the stack trace is possibly bogous. Could you try running with ASAN enabled or Valgrind?

**Comment by RaitoBezarius** [comment]
> `malloc: unknown:0: assertion botched` indicates quite severe memory corruption, the stack trace is possibly bogous. Could you try running with ASAN enabled or Valgrind?

Pardon for ignorance, but I am having troubles finding any documentation on how to compile LLVM with sanitizers, is it just enough to do `LLVM_USE_SANITIZERS=Address` and rerun the whole compilation machinery?

**Comment by RaitoBezarius** [comment]
Also, under `LLVM_USE_SANITIZER=Address`, I get:
```
[nix-shell:/run/user/2024/tmp.4X9omY51ws/llvm-src-16.0.0-rc4/llvm/build]$ bin/llvm-lit ../test/tools/gold/X86/parallel.ll 
-- Testing: 1 tests, 1 workers --
UNSUPPORTED: LLVM :: tools/gold/X86/parallel.ll (1 of 1)

Testing Time: 0.01s
  Unsupported: 1
```

**Comment by lorenz** [comment]
Can you try a normal build (no ASAN) and just run the failing test under valgrind?

**Comment by RaitoBezarius** [comment]
> Can you try a normal build (no ASAN) and just run the failing test under valgrind?

I tried this:
```

[nix-shell:/tmp/llvm-build/llvm-src-16.0.0-rc4/llvm/build]$ env LD_LIBRARY_PATH=$(pwd)/lib /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/bin/valgrind env LD_PRELOAD=$(pwd)/lib/LLVMgold.so /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/ld.gold
==977167== Memcheck, a memory error detector
==977167== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==977167== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==977167== Command: env LD_PRELOAD=/tmp/llvm-build/llvm-src-16.0.0-rc4/llvm/build/lib/LLVMgold.so /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/ld.gold
==977167== 

malloc: unknown:0: assertion botched
free: called with unallocated block argument
Aborting...Aborted (core dumped)
```

I don't know if I'm supposed to LD_PRELOAD before or after or I am supposed to use `llvm-lit` somewhat.

**Comment by RaitoBezarius** [comment]
If I do it before:
```
[nix-shell:/tmp/llvm-build/llvm-src-16.0.0-rc4/llvm/build]$ env LD_LIBRARY_PATH=$(pwd)/lib LD_PRELOAD=$(pwd)/lib/LLVMgold.so /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/bin/valgrind /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/ld.gold
==977426== Memcheck, a memory error detector
==977426== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==977426== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==977426== Command: /nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin/ld.gold
==977426== 
==977426== Invalid free() / delete / delete[] / realloc()
==977426==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977426==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x48390C: parse_and_execute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x482BBD: _evalfile (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x482E2C: source_file (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x48E288: source_builtin (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x430D2A: execute_builtin (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x436BC6: execute_command_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x4373B8: execute_command (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x41DD0C: reader_loop (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x41C573: main (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==  Address 0x406f010 is in the brk data segment 0x4039000-0x408afff
==977426== 
==977426== Invalid free() / delete / delete[] / realloc()
==977426==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977426==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x48E292: source_builtin (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x430D2A: execute_builtin (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x436BC6: execute_command_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x4373B8: execute_command (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x41DD0C: reader_loop (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==    by 0x41C573: main (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977426==  Address 0x406bb10 is in the brk data segment 0x4039000-0x408afff
==977426== 
==977533== Invalid free() / delete / delete[] / realloc()
==977533==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977533==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x48390C: parse_and_execute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x45A10C: command_substitute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x45C8F5: param_expand (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x460589: expand_word_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x46286D: expand_string_assignment (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x45AD89: expand_string_if_necessary (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x45B3A3: do_assignment_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x451465: do_assignment_statements.isra.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x466E04: expand_words (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==    by 0x436194: execute_command_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977533==  Address 0x4066e90 is in the brk data segment 0x4039000-0x4094fff
==977533== 
==977533== 
==977533== HEAP SUMMARY:
==977533==     in use at exit: 141,005 bytes in 2,248 blocks
==977533==   total heap usage: 2,955 allocs, 712 frees, 400,959 bytes allocated
==977533== 
==977533== LEAK SUMMARY:
==977533==    definitely lost: 0 bytes in 0 blocks
==977533==    indirectly lost: 0 bytes in 0 blocks
==977533==      possibly lost: 0 bytes in 0 blocks
==977533==    still reachable: 141,005 bytes in 2,248 blocks
==977533==         suppressed: 0 bytes in 0 blocks
==977533== Rerun with --leak-check=full to see details of leaked memory
==977533== 
==977533== For lists of detected and suppressed errors, rerun with: -s
==977533== ERROR SUMMARY: 5 errors from 3 contexts (suppressed: 0 from 0)
==977534== Invalid free() / delete / delete[] / realloc()
==977534==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977534==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x48390C: parse_and_execute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x45A10C: command_substitute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x45C8F5: param_expand (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x460589: expand_word_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x4664BD: shell_expand_word_list.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x466EB9: expand_words_no_vars (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x4718D3: expand_compound_array_assignment (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x472FB2: assign_array_var_from_string (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x45B19F: do_assignment_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==    by 0x451465: do_assignment_statements.isra.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977534==  Address 0x4066910 is in the brk data segment 0x4039000-0x409efff
==977534== 
==977534== 
==977534== HEAP SUMMARY:
==977534==     in use at exit: 141,005 bytes in 2,248 blocks
==977534==   total heap usage: 2,955 allocs, 714 frees, 400,959 bytes allocated
==977534== 
==977534== LEAK SUMMARY:
==977534==    definitely lost: 0 bytes in 0 blocks
==977534==    indirectly lost: 0 bytes in 0 blocks
==977534==      possibly lost: 0 bytes in 0 blocks
==977534==    still reachable: 141,005 bytes in 2,248 blocks
==977534==         suppressed: 0 bytes in 0 blocks
==977534== Rerun with --leak-check=full to see details of leaked memory
==977534== 
==977534== For lists of detected and suppressed errors, rerun with: -s
==977534== ERROR SUMMARY: 7 errors from 3 contexts (suppressed: 0 from 0)
==977535== Invalid free() / delete / delete[] / realloc()
==977535==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977535==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x48390C: parse_and_execute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x45A10C: command_substitute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x45C8F5: param_expand (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x460589: expand_word_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x4664BD: shell_expand_word_list.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x466EB9: expand_words_no_vars (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x4718D3: expand_compound_array_assignment (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x472FB2: assign_array_var_from_string (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x45B19F: do_assignment_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==    by 0x451465: do_assignment_statements.isra.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977535==  Address 0x4093890 is in the brk data segment 0x4039000-0x409cfff
==977535== 
==977535== 
==977535== HEAP SUMMARY:
==977535==     in use at exit: 141,005 bytes in 2,248 blocks
==977535==   total heap usage: 2,955 allocs, 714 frees, 400,959 bytes allocated
==977535== 
==977535== LEAK SUMMARY:
==977535==    definitely lost: 0 bytes in 0 blocks
==977535==    indirectly lost: 0 bytes in 0 blocks
==977535==      possibly lost: 0 bytes in 0 blocks
==977535==    still reachable: 141,005 bytes in 2,248 blocks
==977535==         suppressed: 0 bytes in 0 blocks
==977535== Rerun with --leak-check=full to see details of leaked memory
==977535== 
==977535== For lists of detected and suppressed errors, rerun with: -s
==977535== ERROR SUMMARY: 7 errors from 3 contexts (suppressed: 0 from 0)
==977536== Invalid free() / delete / delete[] / realloc()
==977536==    at 0x4848F6C: free (in /nix/store/bq5zlcidj4zj6j4nkqpw7b1dc6zf5n13-valgrind-3.20.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==977536==    by 0x46B55F: unwind_frame_run_internal.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x48390C: parse_and_execute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x45A10C: command_substitute (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x45C8F5: param_expand (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x460589: expand_word_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x4664BD: shell_expand_word_list.constprop.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x466EB9: expand_words_no_vars (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x4718D3: expand_compound_array_assignment (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x472FB2: assign_array_var_from_string (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x45B19F: do_assignment_internal (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==    by 0x451465: do_assignment_statements.isra.0 (in /nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin/bash)
==977536==  Address 0x4093a90 is in the brk data segment 0x4039000-0x409cfff
==977536== 
==977536== 
==977536== HEAP SUMMARY:
==977536==     in use at exit: 141,005 bytes in 2,248 blocks
==977536==   total heap usage: 2,955 allocs, 714 frees, 400,959 bytes allocated
==977536== 
==977536== LEAK SUMMARY:
==977536==    definitely lost: 0 bytes in 0 blocks
==977536==    indirectly lost: 0 bytes in 0 blocks
==977536==      possibly lost: 0 bytes in 0 blocks
==977536==    still reachable: 141,005 bytes in 2,248 blocks
==977536==         suppressed: 0 bytes in 0 blocks
==977536== Rerun with --leak-check=full to see details of leaked memory
==977536== 
==977536== For lists of detected and suppressed errors, rerun with: -s
==977536== ERROR SUMMARY: 7 errors from 3 contexts (suppressed: 0 from 0)
/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin/ld.gold: fatal error: no input files
==977426== 
==977426== HEAP SUMMARY:
==977426==     in use at exit: 141,005 bytes in 2,248 blocks
==977426==   total heap usage: 3,436 allocs, 1,194 frees, 2,195,063 bytes allocated
==977426== 
==977426== LEAK SUMMARY:
==977426==    definitely lost: 0 bytes in 0 blocks
==977426==    indirectly lost: 0 bytes in 0 blocks
==977426==      possibly lost: 0 bytes in 0 blocks
==977426==    still reachable: 141,005 bytes in 2,248 blocks
==977426==         suppressed: 0 bytes in 0 blocks
==977426== Rerun with --leak-check=full to see details of leaked memory
==977426== 
==977426== For lists of detected and suppressed errors, rerun with: -s
==977426== ERROR SUMMARY: 6 errors from 2 contexts (suppressed: 0 from 0)
```

**Comment by RaitoBezarius** [comment]
I confirm this bug to be on LLVM16.0.0.

We will disable Gold plugin for LLVM16.0.0 in NixOS until this is closed.

**Comment by ivan** [comment]
Still an issue in 16.0.1:

```
buildPhase completed in 31 minutes 39 seconds
running tests
check flags: -j15 check-all
[1/2] Preparing lit tests
[1/2] Running all regression tests
-- Testing: 48195 tests, 15 workers --
FAIL: LLVM :: tools/gold/X86/parallel.ll (41695 of 48195)
******************** TEST 'LLVM :: tools/gold/X86/parallel.ll' FAILED ********************
Script:
--
: 'RUN: at line 1';   /build/llvm-src-16.0.1/llvm/build/bin/llvm-as -o /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.bc /build/llvm-src-16.0.1/llvm/test/tools/gold/X86/parallel.ll
: 'RUN: at line 2';   rm -f /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.0.5.precodegen.bc /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.1.5.precodegen.bc /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.lto.o /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.lto.o1
: 'RUN: at line 3';   env LD_PRELOAD=/build/llvm-src-16.0.1/llvm/build/lib/LLVMgold.so /nix/store/6ylnn4p1vmyc0gpzmi7iia0cmz4ixz45-gcc-wrapper-12.2.0/bin/ld.gold -plugin /build/llvm-src-16.0.1/llvm/build/lib/LLVMgold.so -u foo -u bar -plugin-opt lto-partitions=2 -plugin-opt save-temps -m elf_x86_64 -o /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.bc
: 'RUN: at line 4';   /build/llvm-src-16.0.1/llvm/build/bin/llvm-dis /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.0.5.precodegen.bc -o - | /build/llvm-src-16.0.1/llvm/build/bin/FileCheck --check-prefix=CHECK-BC0 /build/llvm-src-16.0.1/llvm/test/tools/gold/X86/parallel.ll
: 'RUN: at line 5';   /build/llvm-src-16.0.1/llvm/build/bin/llvm-dis /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.1.5.precodegen.bc -o - | /build/llvm-src-16.0.1/llvm/build/bin/FileCheck --check-prefix=CHECK-BC1 /build/llvm-src-16.0.1/llvm/test/tools/gold/X86/parallel.ll
: 'RUN: at line 6';   /build/llvm-src-16.0.1/llvm/build/bin/llvm-nm /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.lto.o | /build/llvm-src-16.0.1/llvm/build/bin/FileCheck --check-prefix=CHECK0 /build/llvm-src-16.0.1/llvm/test/tools/gold/X86/parallel.ll
: 'RUN: at line 7';   /build/llvm-src-16.0.1/llvm/build/bin/llvm-nm /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.lto.o1 | /build/llvm-src-16.0.1/llvm/build/bin/FileCheck --check-prefix=CHECK1 /build/llvm-src-16.0.1/llvm/test/tools/gold/X86/parallel.ll
--
Exit Code: 134

Command Output (stderr):
--

malloc: unknown:0: assertion botched
free: called with unallocated block argument
Aborting.../build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.script: line 7: 230741 Aborted                 (core dumped) env LD_PRELOAD=/build/llvm-src-16.0.1/llvm/build/lib/LLVMgold.so /nix/store/6ylnn4p1vmyc0gpzmi7iia0cmz4ixz45-gcc-wrapper-12.2.0/bin/ld.gold -plugin /build/llvm-src-16.0.1/llvm/build/lib/LLVMgold.so -u foo -u bar -plugin-opt lto-partitions=2 -plugin-opt save-temps -m elf_x86_64 -o /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp /build/llvm-src-16.0.1/llvm/build/test/tools/gold/X86/Output/parallel.ll.tmp.bc

--

********************
********************
Failed Tests (1):
  LLVM :: tools/gold/X86/parallel.ll


Testing Time: 328.85s
  Skipped          :     7
  Unsupported      :  1782
  Passed           : 51633
  Expectedly Failed:   173
  Failed           :     1
FAILED: CMakeFiles/check-all /build/llvm-src-16.0.1/llvm/build/CMakeFiles/check-all 
cd /build/llvm-src-16.0.1/llvm/build && /nix/store/fdgv8di2p4xn435n4wxri1iz2crz6glg-python3-3.10.11-env/bin/python3.10 /build/llvm-src-16.0.1/llvm/build/./bin/llvm-lit -svj15 --no-progress-bar --param polly_site_config=/build/llvm-src-16.0.1/llvm/build/tools/polly/test/lit.site.cfg --param polly_unit_site_config=/build/llvm-src-16.0.1/llvm/build/tools/polly/test/Unit/lit.site.cfg /build/llvm-src-16.0.1/llvm/build/tools/polly/test /build/llvm-src-16.0.1/llvm/build/utils/lit /build/llvm-src-16.0.1/llvm/build/test
ninja: build stopped: subcommand failed.
```

**Comment by MaskRay** [comment]
I think this is likely a NixOS issue and unlikely a llvm-project issue.

`ninja check-llvm-tools-gold` . `llvm/test/tools/gold/X86/parallel.ll` passes for me with both the main branch and the `release/16.x` branch. My gold version is the latest released version, but I've used quite a few versions and don't see that this failed.
```
GNU gold (GNU Binutils for Debian 2.40) 1.16
```

With `LD_PRELOAD` you may cause mismatching between your glibc libc.so.6 and the dynamic loader, leading to strange malloc issues.

**Comment by MaskRay** [comment]
@chapuni 3c0f9d81705f95c3f6b25add6b17eb7c5ad3b0ff added `env LD_PRELOAD=%llvmshlibdir/LLVMgold.so` to `llvm/test/tools/gold/X86/parallel.ll`, which may made this test fail on NixOS.

**Comment by RaitoBezarius** [comment]
I can try without the `LD_PRELOAD`, but I don't see why NixOS would prevent this LLVMgold.so to be loaded.

> With LD_PRELOAD you may cause mismatching between your glibc libc.so.6 and the dynamic loader, leading to strange malloc issues.

Hm, yes, but it's not like we are mixing two libc, are we?
