### ISSUE TITLE
Segmentation fault with -O2 & -O3

### ISSUE THREAD

**Issue by MCausc78** [llvm/llvm-project#62160]
Hey LLVM project. I dont know why I'm getting segmentation fault. I think that error in backend for Arm. The compiler asked me to send issue:
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /data/data/com.termux/files/usr/bin/clang-15 -cc1 -triple armv7-unknown-linux-android24 -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name gena.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -target-feature +soft-float-abi -target-feature +vfp2 -target-feature +vfp2sp -target-feature +vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature +vfp3sp -target-feature -fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature -vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature +fp64 -target-feature +d32 -target-feature +neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/data/data/com.termux/files/home/box/cpp -resource-dir /data/data/com.termux/files/usr/lib/clang/15.0.6 -isysroot /data/data/com.termux/files -internal-isystem /data/data/com.termux/files/usr/include/c++/v1 -internal-isystem /data/data/com.termux/files/usr/lib/clang/15.0.6/include -internal-isystem /data/data/com.termux/files/usr/local/include -internal-externc-isystem /data/data/com.termux/files/usr/include/arm-linux-androideabi -internal-externc-isystem /data/data/com.termux/files/include -internal-externc-isystem /data/data/com.termux/files/usr/include -O3 -std=gnu++20 -fdeprecated-macro -fdebug-compilation-dir=/data/data/com.termux/files/home/box/cpp -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /data/data/com.termux/files/usr/tmp/gena-7ad854.o -x c++ gena.cpp
1.      <eof> parser at end of file
2.      Optimizer
clang-15: error: unable to execute command: Segmentation fault
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.6
Target: armv7a-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang-15: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /data/data/com.termux/files/usr/tmp/gena-8d2636.cpp
clang-15: note: diagnostic msg: /data/data/com.termux/files/usr/tmp/gena-8d2636.sh
clang-15: note: diagnostic msg:

********************
```
Here a files that compiler asked to attach:
[gena-8d2636.cpp.txt](https://github.com/llvm/llvm-project/files/11240735/gena-8d2636.cpp.txt)
[gena-8d2636.sh.txt](https://github.com/llvm/llvm-project/files/11240736/gena-8d2636.sh.txt)
A clean source code, that i give to compiler: [gena.cpp.txt](https://github.com/llvm/llvm-project/files/11240737/gena.cpp.txt)

**Comment by DimitryAndric** [comment]
This reproduces with the latest clang I have here (7486b7b6bac):

```
Assertion failed: (!NodePtr->isKnownSentinel()), function operator*, file /home/dim/src/llvm/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h, line 138.
```

The problem was introduced somewhere after 15.x branched.

**Comment by DimitryAndric** [comment]
Okay, at first sight this assertion got introduced in 702d5de4380b1e1554e5b90863093c3a57f76f70 ("[Clang] Enable opaque pointers by default") by @nikic.  If I compile it with ~15.0.0 and add `-no-opaque-pointers`, it works. However, later versions of clang don't accept this anymore, and assert with:

```
Assertion failed: (Ptr->getType()->isOpaquePointerTy() && "Only opaque pointers supported"), function getAdjustedPtr
```

**Comment by DimitryAndric** [comment]
Reduced test case:

```c++
// clang -cc1 -triple armv7-- -S -O1 -std=c++20 -fexceptions gena-min.cpp
inline namespace __ndk1 {
template <class _Tp, class = _Tp> class vector;
int __libcpp_allocate___size;
struct __wrap_iter {
  __wrap_iter(int) {}
};
template <class _Iter1, class _Iter2> bool operator==(_Iter1, _Iter2) {
  return 0 == 0;
}
template <class _Alloc> struct allocator_traits {
  typedef int *pointer;
  static pointer allocate() {
    _Alloc __a;
    return __a.allocate(1);
  }
};
struct allocator {
  int *allocate(int) {
    void *__trans_tmp_6 = __builtin_operator_new(__libcpp_allocate___size);
    return static_cast<int *>(__trans_tmp_6);
  }
};
template <class> struct __compressed_pair_elem {
  template <class _Up> __compressed_pair_elem(_Up) {}
};
struct __compressed_pair : __compressed_pair_elem<int>,
                           __compressed_pair_elem<allocator> {
  template <class _U1, class _U2>
  __compressed_pair(_U1, _U2)
      : __compressed_pair_elem<int>(0), __compressed_pair_elem<allocator>(0) {}
};
template <class _InputIterator, class _Predicate>
bool all_of(_InputIterator __first, _InputIterator __last, _Predicate) {
  for (; __first != __last;)
    return false;
  return true;
}
struct __vector_base_common {
  void __throw_length_error();
};
template <class> struct __vector_base : __vector_base_common {
  typedef allocator_traits<allocator> __alloc_traits;
  typedef int size_type;
  __alloc_traits::pointer __begin_;
  __alloc_traits::pointer __end_;
  __compressed_pair __end_cap_;
  __vector_base() noexcept;
  ~__vector_base();
};
template <class _Allocator>
__vector_base<_Allocator>::__vector_base() noexcept
    : __begin_(), __end_(), __end_cap_(nullptr, int()) {}
template <class _Allocator> __vector_base<_Allocator>::~__vector_base() {
  __builtin_operator_delete(__begin_);
}
template <class, class> struct vector : __vector_base<int> {
  vector() {}
  vector(const vector &);
  __wrap_iter begin() noexcept;
  __wrap_iter end() noexcept;
  size_type size() const { return __end_ - __begin_; }
};
template <class _Tp, class _Allocator>
vector<_Tp, _Allocator>::vector(const vector &__x) {
  size_type __n = __x.size();
  if (__n)
    __throw_length_error();
  __end_ = __alloc_traits::allocate();
}
template <class _Tp, class _Allocator>
__wrap_iter vector<_Tp, _Allocator>::begin() noexcept {
  return 0;
}
template <class _Tp, class _Allocator>
__wrap_iter vector<_Tp, _Allocator>::end() noexcept {
  return 0;
}
} // namespace __ndk1
int main() {
  vector<int> range, result;
  __wrap_iter __trans_tmp_1 = result.begin(), __trans_tmp_2 = result.end();
  while (all_of(__trans_tmp_1, __trans_tmp_2, [range] {}))
    ;
}
```

**Comment by MCausc78** [comment]
> ```c++
> // clang -cc1 -triple armv7-- -S -O1 -std=c++20 -fexceptions gena-min.cpp
> ```

And the stacktrace:
```console
$ clang-16 -cc1 -triple armv7-- -S -O1 -std=c++20 -fexceptions gena-min.cpp
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang-16 -cc1 -triple armv7-- -S -O1 -std=c++20 -fexceptions gena-min.cpp
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x00005573bcf5a5b4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005573bcf57d5b SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f9eeece5f90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #3 0x00005573ba7b10f4 llvm::removeUnreachableBlocks(llvm::Function&, llvm::DomTreeUpdater*, llvm::MemorySSAUpdater*) (.cold) Local.cpp:0:0
 #4 0x00005573bce3c891 simplifyFunctionCFGImpl(llvm::Function&, llvm::TargetTransformInfo const&, llvm::DominatorTree*, llvm::SimplifyCFGOptions const&) SimplifyCFGPass.cpp:0:0
 #5 0x00005573bce3d60f llvm::SimplifyCFGPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/mclr/opt/cross/bin/clang-16+0x375060f)
 #6 0x00005573bb24830d llvm::detail::PassModel<llvm::Function, llvm::SimplifyCFGPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/mclr/opt/cross/bin/clang-16+0x1b5b30d)
 #7 0x00005573bab9652f llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/mclr/opt/cross/bin/clang-16+0x14a952f)
 #8 0x00005573bbed0a1e llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x27e3a1e)
 #9 0x00005573bab8ad4d llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x149dd4d)
#10 0x00005573bbecc60b llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x27df60b)
#11 0x00005573bc89581d llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x31a881d)
#12 0x00005573bbed184c llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x27e484c)
#13 0x00005573bc8957fd llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::DevirtSCCRepeatedPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/home/mclr/opt/cross/bin/clang-16+0x31a87fd)
#14 0x00005573bbecd532 llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/mclr/opt/cross/bin/clang-16+0x27e0532)
#15 0x00005573bc89d9ff llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/mclr/opt/cross/bin/clang-16+0x31b09ff)
#16 0x00005573be10d12d llvm::detail::PassModel<llvm::Module, llvm::ModuleInlinerWrapperPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/mclr/opt/cross/bin/clang-16+0x4a2012d)
#17 0x00005573bc78000f llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/mclr/opt/cross/bin/clang-16+0x309300f)
#18 0x00005573bd2d4002 (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile> >&) BackendUtil.cpp:0:0
#19 0x00005573bd2d7715 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/mclr/opt/cross/bin/clang-16+0x3bea715)
#20 0x00005573be0a78ad clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/mclr/opt/cross/bin/clang-16+0x49ba8ad)
#21 0x00005573beb88349 clang::ParseAST(clang::Sema&, bool, bool) (/home/mclr/opt/cross/bin/clang-16+0x549b349)
#22 0x00005573bda1d409 clang::FrontendAction::Execute() (/home/mclr/opt/cross/bin/clang-16+0x4330409)
#23 0x00005573bd9a7f5b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/mclr/opt/cross/bin/clang-16+0x42baf5b)
#24 0x00005573bdad6883 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/mclr/opt/cross/bin/clang-16+0x43e9883)
#25 0x00005573ba8af1cd cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/mclr/opt/cross/bin/clang-16+0x11c21cd)
#26 0x00005573ba8a8d9c ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#27 0x00005573ba8ab00d clang_main(int, char**) (/home/mclr/opt/cross/bin/clang-16+0x11be00d)
#28 0x00007f9eeecd118a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#29 0x00007f9eeecd1245 call_init ./csu/../csu/libc-start.c:128:20
#30 0x00007f9eeecd1245 __libc_start_main ./csu/../csu/libc-start.c:368:5
#31 0x00005573ba8a82f1 _start (/home/mclr/opt/cross/bin/clang-16+0x11bb2f1)
Segmentation fault
```

**Comment by DimitryAndric** [comment]
Yeah, you are getting a segfault because your clang binary is not compiled with assertions enabled. With assertions enabled, the stack trace is similar, though:

```
#0  thr_kill () at thr_kill.S:4
#1  0x00000008079089c4 in __raise (s=s@entry=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x00000008079b9779 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#3  0x00000008078eb7a1 in __assert (func=<optimized out>, file=<optimized out>, line=<optimized out>, failedexpr=<optimized out>) at /usr/src/lib/libc/gen/assert.c:51
#4  0x000000000429c0b0 in llvm::removeUnreachableBlocks(llvm::Function&, llvm::DomTreeUpdater*, llvm::MemorySSAUpdater*) ()
#5  0x000000000410580e in simplifyFunctionCFGImpl(llvm::Function&, llvm::TargetTransformInfo const&, llvm::DominatorTree*, llvm::SimplifyCFGOptions const&) ()
#6  0x0000000004104572 in simplifyFunctionCFG(llvm::Function&, llvm::TargetTransformInfo const&, llvm::DominatorTree*, llvm::SimplifyCFGOptions const&) ()
#7  0x0000000004104301 in llvm::SimplifyCFGPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
#8  0x000000000545e2c2 in llvm::detail::PassModel<llvm::Function, llvm::SimplifyCFGPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
#9  0x0000000003d3ed55 in llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
#10 0x00000000049218f2 in llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
#11 0x0000000003dd3424 in llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#12 0x0000000005461172 in llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#13 0x0000000003dce4be in llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#14 0x00000000054497d2 in llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#15 0x0000000003dd16a3 in llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#16 0x0000000005461ef2 in llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::DevirtSCCRepeatedPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) ()
#17 0x0000000003dd040e in llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#18 0x0000000005449a52 in llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#19 0x0000000003d3d965 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#20 0x000000000554efbc in llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#21 0x0000000005450522 in llvm::detail::PassModel<llvm::Module, llvm::ModuleInlinerWrapperPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#22 0x0000000003d3d965 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
#23 0x00000000049193cb in (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >&, std::__1::unique_ptr<llvm::ToolOutputFile, std::__1::default_delete<llvm::ToolOutputFile> >&) ()
#24 0x00000000049122f4 in clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) ()
#25 0x0000000004d5c2e2 in clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) ()
#26 0x0000000005ac8675 in clang::ParseAST(clang::Sema&, bool, bool) ()
#27 0x0000000004c82033 in clang::FrontendAction::Execute() ()
#28 0x0000000004c05e0f in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#29 0x0000000004d54b98 in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) ()
#30 0x00000000027e67dd in cc1_main(llvm::ArrayRef<char const*>, char const*, void*) ()
#31 0x00000000027e2655 in ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) ()
#32 0x00000000027e1539 in clang_main(int, char**, llvm::ToolContext const&) ()
#33 0x00000000027f0964 in main ()
```
