### ISSUE TITLE
Assertion `Ptr != End && "dereferencing end() iterator"' failed in ScalarEvolution::getBackedgeTakenInfo

### ISSUE THREAD

**Issue by d-makogon** [llvm/llvm-project#62380]
Reproducer: https://godbolt.org/z/oqh84KvTs
```shell
opt -passes='loop(loop-deletion),loop-mssa(loop-predication,licm<allowspeculation>,simple-loop-unswitch<nontrivial>),loop(loop-predication)'
```
crashes with the following backtrace:
```console
opt: /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/DenseMap.h:1256: pointer llvm::DenseMapIterator<const llvm::Loop *, llvm::ScalarEvolution::BackedgeTakenInfo>::operator->() const [KeyT = const llvm::Loop *, ValueT = llvm::ScalarEvolution:
:BackedgeTakenInfo, KeyInfoT = llvm::DenseMapInfo<const llvm::Loop *>, Bucket = llvm::detail::DenseMapPair<const llvm::Loop *, llvm::ScalarEvolution::BackedgeTakenInfo>, IsConst = false]: Assertion `Ptr != End && "dereferencing end() iterator"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /localhome/dmakogon/llvm/llvm-project/build/RA/bin/opt -passes=loop(loop-deletion),loop-mssa(loop-predication,licm<allowspeculation>,simple-loop-unswitch<nontrivial>),loop(loop-predication) renamed.ll
 #0 0x00007f0f245f92c8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:602:13
 #1 0x00007f0f245f7340 llvm::sys::RunSignalHandlers() /localhome/dmakogon/llvm/llvm-project/llvm/lib/Support/Signals.cpp:105:18
 #2 0x00007f0f245f993d SignalHandler(int) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007f0f238e4630 __restore_rt sigaction.c:0:0
 #4 0x00007f0f22c8c387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f0f22c8da78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f0f22c851a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f0f22c85252 (/lib64/libc.so.6+0x2f252)
 #8 0x00007f0f25dcaa22 bool llvm::DenseMapBase<llvm::DenseMap<llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>, llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>::LookupBucketFor<llvm::PHINode*>(llvm::PHINode* const&, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*> const*&) const /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/DenseMap.h:635:5
 #9 0x00007f0f25dcaa22 bool llvm::DenseMapBase<llvm::DenseMap<llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>, llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>::LookupBucketFor<llvm::PHINode*>(llvm::PHINode* const&, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>*&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/DenseMap.h:675:9
#10 0x00007f0f25dcaa22 llvm::DenseMapBase<llvm::DenseMap<llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>, llvm::PHINode*, llvm::Constant*, llvm::DenseMapInfo<llvm::PHINode*, void>, llvm::detail::DenseMapPair<llvm::PHINode*, llvm::Constant*>>::erase(llvm::PHINode* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/DenseMap.h:317:10
#11 0x00007f0f25dcaa22 llvm::ScalarEvolution::getBackedgeTakenInfo(llvm::Loop const*) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Analysis/ScalarEvolution.cpp:8419:38
#12 0x00007f0f25dc9318 llvm::SmallVectorBase<unsigned int>::size() const /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/SmallVector.h:91:32
#13 0x00007f0f25dc9318 llvm::SmallVectorTemplateCommon<llvm::ScalarEvolution::ExitNotTakenInfo, void>::end() const /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/ADT/SmallVector.h:273:49
#14 0x00007f0f25dc9318 llvm::ScalarEvolution::BackedgeTakenInfo::getExact(llvm::BasicBlock const*, llvm::ScalarEvolution*) const /localhome/dmakogon/llvm/llvm-project/llvm/lib/Analysis/ScalarEvolution.cpp:8622:24
#15 0x00007f0f25dc9318 llvm::ScalarEvolution::getExitCount(llvm::Loop const*, llvm::BasicBlock const*, llvm::ScalarEvolution::ExitCountKind) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Analysis/ScalarEvolution.cpp:8309:36
#16 0x00007f0f256bf49c llvm::isa_impl_cl<llvm::SCEVCouldNotCompute, llvm::SCEV const*>::doit(llvm::SCEV const*) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:109:5
#17 0x00007f0f256bf49c llvm::isa_impl_wrap<llvm::SCEVCouldNotCompute, llvm::SCEV const*, llvm::SCEV const*>::doit(llvm::SCEV const* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:137:12
#18 0x00007f0f256bf49c llvm::isa_impl_wrap<llvm::SCEVCouldNotCompute, llvm::SCEV const* const, llvm::SCEV const*>::doit(llvm::SCEV const* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:127:12
#19 0x00007f0f256bf49c llvm::CastIsPossible<llvm::SCEVCouldNotCompute, llvm::SCEV const*, void>::isPossible(llvm::SCEV const* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:255:12
#20 0x00007f0f256bf49c llvm::CastInfo<llvm::SCEVCouldNotCompute, llvm::SCEV const* const, void>::isPossible(llvm::SCEV const* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:509:12
#21 0x00007f0f256bf49c bool llvm::isa<llvm::SCEVCouldNotCompute, llvm::SCEV const*>(llvm::SCEV const* const&) /localhome/dmakogon/llvm/llvm-project/llvm/include/llvm/Support/Casting.h:549:10
#22 0x00007f0f256bf49c getMinAnalyzeableBackedgeTakenCount(llvm::ScalarEvolution&, llvm::DominatorTree&, llvm::Loop*) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Transforms/Scalar/LoopPredication.cpp:1096:9
#23 0x00007f0f256bf49c (anonymous namespace)::LoopPredication::predicateLoopExits(llvm::Loop*, llvm::SCEVExpander&) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Transforms/Scalar/LoopPredication.cpp:1189:23
#24 0x00007f0f256bf49c (anonymous namespace)::LoopPredication::runOnLoop(llvm::Loop*) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Transforms/Scalar/LoopPredication.cpp:1326:14
#25 0x00007f0f256bd57d llvm::LoopPredicationPass::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) /localhome/dmakogon/llvm/llvm-project/llvm/lib/Transforms/Scalar/LoopPredication.cpp:380:7
```

The crash happens here in `ScalarEvolution::getBackedgeTakenInfo` in the following piece of code:
```cpp
return BackedgeTakenCounts.find(L)->second = std::move(Result);
```
So we expect here that entry for `L` exists in `BackedgeTakenCounts`. Indeed, in the beginning of the function we insert an entry if it wasn't already there. Here's how we've come to delete it from the cache.
In the example above we call `getBackedgeTakenInfo` on loop `bb9`.
After the initial insertion we call `computeBackedgeTakenCount` to get the `BackedgeTakenInfo` that is returned later. And it's all fine. The problem happens after the call to `computeBackedgeTakenCount`. We have some code that updates some statistics:
```c++
computeBackedgeTakenCount(L);
...
#if LLVM_ENABLE_STATS || !defined(NDEBUG)
  const SCEV *BEExact = Result.getExact(L, this);
  // update stats
  ...
```
And in the call to `getExact` we may call `getBackedgeTakenInfo` on another loop - `bb3`, which happens to be the parent loop for `bb9`. We compute its backedge taken info and then invalidate any SCEVs that use AddRecs of `bb3`. This is perfomed in `getBackedgeTakenInfo` and it's done to get more precise results as now we have a computed backedge count for the loop. While doing this invalidation, we erase the computed backedge count from `BackedgeTakenCounts` map for the child loop `bb9` because it happens to use the AddRec of `bb3`. Then we return from `getBackedgeTakenInfo` for the parent loop, update the stats and in `return` expect the entry for `bb9` to be in cache. Here's the stacktrace of the cache entry deletion:
```console
#0  llvm::ScalarEvolution::forgetBackedgeTakenCounts (this=0x7b9258, L=0x7fffead56000, Predicated=false)
#1  0x00007ffff1926b1d in llvm::ScalarEvolution::forgetMemoizedResultsImpl (this=0x7b9258, S=0x7fffeacf2960)
#2  0x00007ffff1926350 in llvm::ScalarEvolution::forgetMemoizedResults (this=0x7b9258, SCEVs=...)
#3  0x00007ffff190e42c in llvm::ScalarEvolution::getBackedgeTakenInfo (this=0x7b9258, L=0x7fffead560a8) // bb3
#4  0x00007ffff190de24 in llvm::ScalarEvolution::getBackedgeTakenCount (this=0x7b9258, L=0x7fffead560a8, Kind=llvm::ScalarEvolution::ConstantMaximum)
#5  0x00007ffff0dce9f8 in llvm::ScalarEvolution::getConstantMaxBackedgeTakenCount (this=0x7b9258, L=0x7fffead560a8)
#6  0x00007ffff1906451 in llvm::ScalarEvolution::getRangeRef (this=0x7b9258, S=0x7fffeacf2730, SignHint=llvm::ScalarEvolution::HINT_RANGE_UNSIGNED, Depth=1)
#7  0x00007ffff1905bf7 in llvm::ScalarEvolution::getRangeRef (this=0x7b9258, S=0x7fffeacf2790, SignHint=llvm::ScalarEvolution::HINT_RANGE_UNSIGNED, Depth=0)
#8  0x00007fffefd4b7ae in llvm::ScalarEvolution::getUnsignedRange (this=0x7b9258, S=0x7fffeacf2790)
#9  0x00007ffff191a8d4 in llvm::ScalarEvolution::isKnownPredicateViaConstantRanges (this=0x7b9258, Pred=llvm::CmpInst::ICMP_ULE, LHS=0x7fffeacf2790, RHS=0x7fffeacf23d0)
#10 0x00007ffff191fa87 in llvm::ScalarEvolution::isKnownViaNonRecursiveReasoning (this=0x7b9258, Pred=llvm::CmpInst::ICMP_ULE, LHS=0x7fffeacf2790, RHS=0x7fffeacf23d0)
#11 0x00007ffff18fb0d1 in llvm::ScalarEvolution::getMinMaxExpr (this=0x7b9258, Kind=<incomplete type>, Ops=...)
#12 0x00007ffff18fc4e7 in llvm::ScalarEvolution::getSequentialMinMaxExpr (this=0x7b9258, Kind=<incomplete type>, Ops=...)
#13 0x00007ffff18fcaf6 in llvm::ScalarEvolution::getUMinExpr (this=0x7b9258, Ops=..., Sequential=true)
#14 0x00007ffff18fea07 in llvm::ScalarEvolution::getUMinFromMismatchedTypes (this=0x7b9258, Ops=..., Sequential=true)
#15 0x00007ffff190f2a4 in llvm::ScalarEvolution::BackedgeTakenInfo::getExact (this=0x7fffffff7430, L=0x7fffead56000, 
#16 0x00007ffff190e223 in llvm::ScalarEvolution::getBackedgeTakenInfo (this=0x7b9258, L=0x7fffead56000) // bb9
```
Notice how we initially call `getBackedgeTakenInfo` on `bb9`, during it call `getBackedgeTakenInfo` on `bb3` and end up calling `forgetBackedgeTakenCounts` on `bb9`.

**Comment by d-makogon** [comment]
Added a test - https://github.com/llvm/llvm-project/blob/main/llvm/test/Analysis/ScalarEvolution/pr62380.ll

**Comment by d-makogon** [comment]
Fix on review - https://reviews.llvm.org/D149251
