### ISSUE TITLE
Looks like LLDB extract encoder issue

### ISSUE THREAD

**Issue by sushil89** [llvm/llvm-project#62539]
Traceback (most recent call last):
  File "/mnt/lwhelper/lwhelper.py", line 4089, in <module>
    main()
  File "/mnt/lwhelper/lwhelper.py", line 4007, in main
    print(extract.to_json())
  File "/mnt/lwhelper/lwhelper.py", line 2308, in to_json
    return json.dumps({
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by asl** [comment]
`lwhelper.py` is not a part of LLVM.

Please reopen with more information how to reproduce the issue, etc.
