### ISSUE TITLE
[ASAN] invalid-pointer-pair with flexible array member

### ISSUE THREAD

**Issue by alejandro-colomar** [llvm/llvm-project#62656]
I'm getting an AddressSanitizer report that I believe is invalid.

Here's the source code of the program:

```c
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

struct s {
	int        x;
	ptrdiff_t  off[];
};

int
main(void)
{
	char      *p;
	struct s  *s;

	s = malloc(offsetof(struct s, off) +
	           sizeof(ptrdiff_t) * 2 +
		   sizeof("foo") + sizeof("bar"));

	p = (char *) s + offsetof(struct s, off) + sizeof(ptrdiff_t) * 2;

	s->off[0] = p - (char *) s;
	p = stpcpy(p, "foo") + 1;
	s->off[1] = p - (char *) s;
	p = stpcpy(p, "bar") + 1;

	puts((char *) s + s->off[0]);
	puts((char *) s + s->off[1]);

	free(s);
}
```

Here's the compilation and run:

```sh
$ export ASAN_OPTIONS='detect_invalid_pointer_pairs=2'
$ clang-16 --version
Debian clang version 16.0.0 (++20221111053703+a77a02aa5794-1~exp1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ clang-16 -Weverything -Wno-padded -D_FORTIFY_SOURCE=3 -fstrict-flex-arrays=3 -O3 flexi2.c
$ ./a.out 
foo
bar
```

And here's the same with sanitizers:

```sh
$ export ASAN_OPTIONS='detect_invalid_pointer_pairs=2'
$ clang-16 -Weverything -Wno-padded -D_FORTIFY_SOURCE=3 -fstrict-flex-arrays=3 -O3 -g -fsanitize=address -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=undefined flexi2.c
$ ./a.out 
=================================================================
==7569==ERROR: AddressSanitizer: invalid-pointer-pair: 0x603000000048 0xffffffffffffffef
    #0 0x561cc3867b2b in main /home/alx/tmp/flexi2.c:21:43
    #1 0x7f05260cf189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #2 0x7f05260cf244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #3 0x561cc37932e0 in _start (/home/alx/tmp/a.out+0x1e2e0) (BuildId: 832643d32c15646f636155b4b23a053d68ec17c7)

0x603000000048 is located 8 bytes inside of 32-byte region [0x603000000040,0x603000000060)
allocated by thread T0 here:
    #0 0x561cc382d36e in __interceptor_malloc (/home/alx/tmp/a.out+0xb836e) (BuildId: 832643d32c15646f636155b4b23a053d68ec17c7)
    #1 0x561cc3867af4 in main /home/alx/tmp/flexi2.c:17:6

Address 0xffffffffffffffef is a wild pointer inside of access range of size 0x000000000001.
SUMMARY: AddressSanitizer: invalid-pointer-pair /home/alx/tmp/flexi2.c:21:43 in main
==7569==ABORTING
```

The report refers to the following code:

```c
	p = (char *) s + offsetof(struct s, off) + sizeof(ptrdiff_t) * 2;
	                                         ^~~ this operation is the trigger
```

**Comment by alejandro-colomar** [comment]
GCC 13 doesn't report anything wrong in here:

```sh
$ gcc-13 --version
gcc-13 (Debian 13.1.0-1) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ export ASAN_OPTIONS='detect_invalid_pointer_pairs=2'
$ gcc-13 -Wall -Wextra -D_FORTIFY_SOURCE=3 -fstrict-flex-arrays=3 -O3 -g -fsanitize=address -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=undefined -fanalyzer flexi2.c
$ ./a.out 
foo
bar
```

**Comment by aaronpuchert** [comment]
I think the underlying issue is the same as #62120.
