### ISSUE TITLE
Deadlock during realloc when sanitizing with ASAN

### ISSUE THREAD

**Issue by maxammann** [llvm/llvm-project#63224]
I noticed hangs of my Rust test suite, which uses some ASAN-instrumented C library.
It turns out that ASAN is blocking a child process, which is being awaited from the main binary.

There is a test case which spawn a subprocess via `fork()` and then waits for it using `waitpid()`.

Using `gdb` I was able to extract the following bracktrace from the hanging child process:

```
0x00007ffff74c9a3a in __sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
(gdb) bt
#0  0x00007ffff74c9a3a in __sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#1  0x00007ffff74caeb2 in __sanitizer::Semaphore::Wait() ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#2  0x00007ffff74fa746 in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long) () from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#3  0x00007ffff74fa7fd in __sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >*, unsigned long) ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#4  0x00007ffff74facf9 in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >*, unsigned long, unsigned long) () from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#5  0x00007ffff74fb01a in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#6  0x00007ffff74f68e6 in __asan::asan_realloc(void*, unsigned long, __sanitizer::BufferedStackTrace*) ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#7  0x00007ffff759f46f in __interceptor_realloc.part.0 ()
   from /nix/store/572dbfdcc1zkzw96z6iw51i6p3q777qh-clang-wrapper-14.0.6/resource-root/lib/linux/libclang_rt.asan-x86_64.so
#8  0x000055555628085f in alloc::alloc::realloc () at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/alloc.rs:132
#9  alloc::alloc::Global::grow_impl (self=0x7ffff40f76f8, ptr=..., old_layout=..., new_layout=..., zeroed=false)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/alloc.rs:209
#10 0x0000555556280c20 in <alloc::alloc::Global as core::alloc::Allocator>::grow (self=0x7ffff40f76f8, ptr=..., old_layout=..., new_layout=...)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/alloc.rs:262
#11 0x000055555627fa06 in alloc::raw_vec::finish_grow (new_layout=..., current_memory=..., alloc=0x7ffff40f76f8)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/raw_vec.rs:466
#12 0x0000555555947f77 in alloc::raw_vec::RawVec<T,A>::grow_amortized (self=0x7ffff40f76f8, len=111, additional=1)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/raw_vec.rs:400
#13 0x000055555594d5d8 in alloc::raw_vec::RawVec<T,A>::reserve_for_push (self=0x7ffff40f76f8, len=111)
--Type <RET> for more, q to quit, c to continue without paging--
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/raw_vec.rs:298
#14 0x00005555559d5aba in alloc::vec::Vec<T,A>::push (self=0x7ffff40f76f8, value=...)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:1840
#15 0x0000555555775152 in tlspuffin::tls::fn_impl::fn_fields::fn_append_cipher_suite (suites=0x60300001ed30, suite=0x6020002bbfd0)
    at tlspuffin/src/tls/./fn_fields.rs:200
#16 0x00005555556f10ea in core::ops::function::Fn::call () at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:79
#17 0x00005555557fe0c9 in <F as puffin::algebra::dynamic_function::DescribableFunction<(R,T1,T2)>>::make_dynamic::{{closure}} (args=0x7ffff40f7da8)
    at puffin/src/algebra/dynamic_function.rs:210
#18 0x0000555555e64457 in <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call (self=0x611000c5de40, args=...)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002
#19 0x0000555555831b17 in core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (self=0x7ffff40f7e38, args=...)
    at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:263
#20 0x00005555558a77b2 in puffin::algebra::term::Term<M>::evaluate (self=0x611000c5de00, context=0x7ffff40fd0b0) at puffin/src/algebra/term.rs:132
```

I tested this using Clang versions 10-14. All hang about 50% of time.

**Comment by maxammann** [comment]
Just wanted to leave a note that we are still experiencing this deadlock. I'm aware though that this issue is in a non-actionable state as there is no reproducible demo.

**Comment by vitalybuka** [comment]
Is possible to have a reproducer for clang 18+?

**Comment by maxammann** [comment]
@michaelmera how reproducible is the test case we have right now?

**Comment by michaelmera** [comment]
> @michaelmera how reproducible is the test case we have right now?

It hangs at least 50% of the time with the current test suite and the variability seems entirely dependent on the scheduling order done by cargo-test.

@vitalybuka I will spend some time on this issue next week and see if I can get you a reproducer. Thanks!

**Comment by renatahodovan** [comment]
I'm regularly experiencing a similar issue while using libFuzzer with asan. It usually took 1-5 hours of fuzzing (and another hours until I spot the deadlock, so it's quite annoying). Unfortunately, I don't have a repro either. However, I can also paste the backtrace from an attached lldb. I use llvm-17.0.6.

```
    frame #0: 0x000055555573a31a fuzz_grammarinator`__sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) + 26
fuzz_grammarinator`__sanitizer::FutexWait:
->  0x55555573a31a <+26>: popq   %rbx
    0x55555573a31b <+27>: retq
    0x55555573a31c:       nopl   (%rax)
fuzz_grammarinator`__sanitizer::FutexWake:
    0x55555573a320 <+0>:  pushq  %rbx
  thread #2, name = 'fuzz_grammarina', stop reason = signal SIGSTOP
    frame #0: 0x00007ffff7b227f8 libc.so.6`__GI___clock_nanosleep(clock_id=0, flags=0, req=0x00007ffff29d6d60, rem=0x00007ffff29d6d60) at clock_nanosleep.c:78:7
Executable module set to "oss-fuzz/projects/quickjs/build_basic/fuzz_grammarinator".
Architecture set to: x86_64-pc-linux-gnu.
(lldb) bt
* thread #1, name = 'fuzz_grammarina', stop reason = signal SIGSTOP
  * frame #0: 0x000055555573a31a fuzz_grammarinator`__sanitizer::FutexWait(__sanitizer::atomic_uint32_t*, unsigned int) + 26
    frame #1: 0x000055555573b2da fuzz_grammarinator`__sanitizer::Semaphore::Wait() + 26
    frame #2: 0x00005555556a514c fuzz_grammarinator`__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long) + 220
    frame #3: 0x00005555556a4fc3 fuzz_grammarinator`__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >*, unsigned long) + 51
    frame #4: 0x00005555556a4c67 fuzz_grammarinator`__sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >*, unsigned long, unsigned long) + 487
    frame #5: 0x00005555556a49c1 fuzz_grammarinator`__sanitizer::QuarantineCache<__asan::QuarantineCallback>::Enqueue(__asan::QuarantineCallback, void*, unsigned long) + 65
    frame #6: 0x00005555556a4856 fuzz_grammarinator`__asan::Allocator::QuarantineChunk(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) + 294
    frame #7: 0x000055555575c46c fuzz_grammarinator`operator delete(void*, unsigned long) + 236
    frame #8: 0x0000555555b17857 fuzz_grammarinator`fuzzer::Sha1ToString(unsigned char const*) [inlined] void std::__Fuzzer::__libcpp_operator_delete<void*, unsigned long>((null)=<unavailable>, (null)=<unavailable>) at new:257:20
    frame #9: 0x0000555555b17852 fuzz_grammarinator`fuzzer::Sha1ToString(unsigned char const*) [inlined] void std::__Fuzzer::__do_deallocate_handle_size<>(__size=<unavailable>, __ptr=<unavailable>) at new:281:34
    frame #10: 0x0000555555b17852 fuzz_grammarinator`fuzzer::Sha1ToString(unsigned char const*) [inlined] std::__Fuzzer::__libcpp_deallocate(__align=<unavailable>, __size=<unavailable>, __ptr=<unavailable>) at new:289:39
    frame #11: 0x0000555555b17852 fuzz_grammarinator`fuzzer::Sha1ToString(unsigned char const*) [inlined] std::__Fuzzer::allocator<char>::deallocate(__n=<unavailable>, __p=<unavailable>, this=<unavailable>) at allocator.h:114:39
    frame #12: 0x0000555555b00e9c fuzz_grammarinator`fuzzer::Fuzzer::DumpCurrentUnit(this=0x0000618000000080, Prefix="timeout-") at FuzzerLoop.cpp:181:43
    frame #13: 0x0000555555b01b27 fuzz_grammarinator`fuzzer::Fuzzer::StaticAlarmCallback() [inlined] fuzzer::Fuzzer::AlarmCallback(this=0x0000618000000080) at FuzzerLoop.cpp:298:20
    frame #14: 0x0000555555b01a98 fuzz_grammarinator`fuzzer::Fuzzer::StaticAlarmCallback() at FuzzerLoop.cpp:275:6
    frame #15: 0x0000555555b01a98 fuzz_grammarinator`fuzzer::Fuzzer::StaticAlarmCallback() at FuzzerLoop.cpp:199:19
    frame #16: 0x00007ffff7a7f520 libc.so.6`__restore_rt
    frame #17: 0x0000555555739ba1 fuzz_grammarinator`__sanitizer::internal_mmap(void*, unsigned long, int, int, int, unsigned long long) + 33
    frame #18: 0x000055555573b90a fuzz_grammarinator`__sanitizer::MmapFixedImpl(unsigned long, unsigned long, bool, char const*) + 154
    frame #19: 0x00005555556a55cf fuzz_grammarinator`__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::PopulateFreeArray(__sanitizer::AllocatorStats*, unsigned long, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::RegionInfo*, unsigned long) + 271
    frame #20: 0x00005555556a5447 fuzz_grammarinator`__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::GetFromAllocator(__sanitizer::AllocatorStats*, unsigned long, unsigned int*, unsigned long) + 983
    frame #21: 0x00005555556a4fc3 fuzz_grammarinator`__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::Refill(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >::PerClass*, __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >*, unsigned long) + 51
    frame #22: 0x00005555556a4c67 fuzz_grammarinator`__sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate(__sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> > >*, unsigned long, unsigned long) + 487
    frame #23: 0x00005555556a49c1 fuzz_grammarinator`__sanitizer::QuarantineCache<__asan::QuarantineCallback>::Enqueue(__asan::QuarantineCallback, void*, unsigned long) + 65
    frame #24: 0x00005555556a4856 fuzz_grammarinator`__asan::Allocator::QuarantineChunk(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) + 294
    frame #25: 0x0000555555720786 fuzz_grammarinator`__interceptor_free + 358
    frame #26: 0x0000555555843b68 fuzz_grammarinator`free_gc_object [inlined] js_free_rt(rt=0x000061700048bc80, ptr=0x0000607003e2d760) at quickjs.c:1320:5
    frame #27: 0x0000555555843b3d fuzz_grammarinator`free_gc_object [inlined] free_object(rt=0x000061700048bc80, p=0x0000607003e2d760) at quickjs.c:5479:9
    frame #28: 0x0000555555843b32 fuzz_grammarinator`free_gc_object(rt=<unavailable>, gp=0x0000607003e2d760) at quickjs.c:5487:9
    frame #29: 0x0000555555784568 fuzz_grammarinator`__JS_FreeValueRT [inlined] free_zero_refcount(rt=0x000061700048bc80) at quickjs.c:5512:9
    frame #30: 0x00005555557844f0 fuzz_grammarinator`__JS_FreeValueRT(rt=<unavailable>, v=<unavailable>) at quickjs.c:5556:21
    frame #31: 0x00005555557cf52a fuzz_grammarinator`JS_CallInternal [inlined] __JS_FreeValue(ctx=<unavailable>, v=<unavailable>) at quickjs.c:5597:5
    frame #32: 0x00005555557cf508 fuzz_grammarinator`JS_CallInternal at quickjs.h:652:13
    frame #33: 0x00005555557cf4fd fuzz_grammarinator`JS_CallInternal [inlined] set_value(ctx=<unavailable>, pval=<unavailable>, new_val=<unavailable>) at quickjs.c:2201:5
    frame #34: 0x00005555557cf4fd fuzz_grammarinator`JS_CallInternal(caller_ctx=0x00006150000f7380, func_obj=<unavailable>, this_obj=<unavailable>, new_target=JSValue @ 0x00007fffffff9160, argc=<unavailable>, argv=<unavailable>, flags=<unavailable>) at quickjs.c:17001:28
    frame #35: 0x00005555557f2346 fuzz_grammarinator`JS_EvalFunctionInternal [inlined] JS_CallFree(ctx=<unavailable>, func_obj=JSValue @ 0x0000000001106560, this_obj=JSValue @ 0x0000000001106560, argc=0, argv=0x0000000000000000) at quickjs.c:18695:19
    frame #36: 0x00005555557f229a fuzz_grammarinator`JS_EvalFunctionInternal(ctx=<unavailable>, fun_obj=JSValue @ 0x00000000010f78a0, this_obj=<unavailable>, var_refs=<unavailable>, sf=<unavailable>) at quickjs.c:34351:19
    frame #37: 0x000055555581b69c fuzz_grammarinator`__JS_EvalInternal(ctx=<unavailable>, this_obj=<unavailable>, input=<unavailable>, input_len=<unavailable>, filename=<unavailable>, flags=<unavailable>, scope_idx=<unavailable>) at quickjs.c:34486:19
    frame #38: 0x00005555557f3e2d fuzz_grammarinator`JS_Eval [inlined] JS_EvalInternal(ctx=0x00006150000f7380, this_obj=JSValue @ 0x0000000000cf32e0, input="{for (BigFloat;;)[[1]]}\n", input_len=24, filename="<none>", flags=0, scope_idx=-1) at quickjs.c:34504:12
    frame #39: 0x00005555557f3ddb fuzz_grammarinator`JS_Eval [inlined] JS_EvalThis(ctx=0x00006150000f7380, this_obj=JSValue @ 0x0000000000cf3fc0, input="{for (BigFloat;;)[[1]]}\n", input_len=24, filename="<none>", eval_flags=0) at quickjs.c:34535:11
    frame #40: 0x00005555557f3da1 fuzz_grammarinator`JS_Eval(ctx=0x00006150000f7380, input=<unavailable>, input_len=<unavailable>, filename=<unavailable>, eval_flags=<unavailable>) at quickjs.c:34543:12
    frame #41: 0x000055555575e90c fuzz_grammarinator`::LLVMFuzzerTestOneInput() at fuzz_grammarinator.cpp:135:19
    frame #42: 0x0000555555b02122 fuzz_grammarinator`fuzzer::Fuzzer::ExecuteCallback(this=0x0000618000000080, Data="\U00000004", Size=1336) at FuzzerLoop.cpp:611:17
    frame #43: 0x0000555555b04151 fuzz_grammarinator`fuzzer::Fuzzer::RunOne(this=0x0000618000000080, Data="\U00000004", Size=<unavailable>, MayDeleteFile=<unavailable>, II=<unavailable>, ForceAddToCorpus=<unavailable>, FoundUniqFeatures=0x00007fffffffd5bf) at FuzzerLoop.cpp:514:18
    frame #44: 0x0000555555b051c1 fuzz_grammarinator`fuzzer::Fuzzer::MutateAndTestOne(this=0x0000618000000080) at FuzzerLoop.cpp:757:25
    frame #45: 0x0000555555b05d60 fuzz_grammarinator`fuzzer::Fuzzer::Loop(this=0x0000618000000080, CorporaFiles=<unavailable>) at FuzzerLoop.cpp:895:21
    frame #46: 0x0000555555af8deb fuzz_grammarinator`fuzzer::FuzzerDriver(argc=0x00007fffffffdb9c, argv=0x00007fffffffdb90, Callback=<unavailable>)(unsigned char const*, unsigned long)) at FuzzerDriver.cpp:912:10
    frame #47: 0x000055555569da07 fuzz_grammarinator`main(argc=<unavailable>, argv=<unavailable>) at FuzzerMain.cpp:20:30
    frame #48: 0x00007ffff7a66d90 libc.so.6`__libc_start_call_main(main=(fuzz_grammarinator`main at FuzzerMain.cpp:19:53), argc=21, argv=0x00007fffffffdcb8) at libc_start_call_main.h:58:16
    frame #49: 0x00007ffff7a66e40 libc.so.6`__libc_start_main_impl(main=(fuzz_grammarinator`main at FuzzerMain.cpp:19:53), argc=21, argv=0x00007fffffffdcb8, init=(_rtld_global), fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdca8) at libc-start.c:392:3
    frame #50: 0x000055555569db85 fuzz_grammarinator`_start + 37
```
