### ISSUE TITLE
[libomptarget] miniqmc hangs when running on amdgpu

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#64572]
The failure is sporadic. The code seems got stuck in calling hsa_signal_wait_scacquire
I was running on mi250 with SLES SP4 and rocm 5.5.0.

clang version
```
clang++ -v
clang version 18.0.0 (https://github.com/llvm/llvm-project.git c8ed138c34ddb22610f18468c1b7938f9e2abae5)
...
Found HIP installation: /soft/compilers/rocm/rocm-5.5.0, version 5.5.30201
```
reproducer https://github.com/ye-luo/miniqmc
```
cmake -DCMAKE_CXX_COMPILER=clang++ -DQMC_ENABLE_ROCM=ON -DQMC_MIXED_PRECISION=ON -DCMAKE_CXX_FLAGS=--gcc-toolchain=/soft/compilers/gcc/12.2.0/x86_64-suse-linux -DENABLE_OFFLOAD=ON ..
make -j32 miniqmc_sync_move
OMP_NUM_THREADS=16 ./bin/miniqmc_sync_move
```
Note: gcc 12 toolchain is required by gpu runtime libraries from rocm. If your clang is configured with gcc 12 toolchain, there is no need to point to one.

**Comment by kevinsala** [comment]
Hi Ye,
Could you provide the stack trace of the thread that hangs?
Thank you

**Comment by ye-luo** [comment]
I was running with
```
(gdb) info threads 
  Id   Target Id                                            Frame 
* 1    Thread 0x7f4e6d4a6ac0 (LWP 200143) "miniqmc_sync_mo" 0x00007f4e76937ed5 in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  2    Thread 0x7f4e65897700 (LWP 200145) "miniqmc_sync_mo" 0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
  3    Thread 0x7f4c5fbfeb80 (LWP 200147) "miniqmc_sync_mo" 0x00007f4e76937cab in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  4    Thread 0x7f4c5f3fcc00 (LWP 200148) "miniqmc_sync_mo" 0x00007f4e76937ed5 in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  5    Thread 0x7f4c5ebfac80 (LWP 200149) "miniqmc_sync_mo" 0x00007f4e76937ed5 in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  6    Thread 0x7f4c5e3f8d00 (LWP 200150) "miniqmc_sync_mo" 0x00007f4e76937217 in int __kmp_execute_tasks_64<false, true>(kmp_info*, int, kmp_flag_64<false, true>*, int, int*, void*, int)
    () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  7    Thread 0x7f4c5dbf6d80 (LWP 200151) "miniqmc_sync_mo" 0x00007f4e76937217 in int __kmp_execute_tasks_64<false, true>(kmp_info*, int, kmp_flag_64<false, true>*, int, int*, void*, int)
    () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  8    Thread 0x7f4c5d3f4e00 (LWP 200152) "miniqmc_sync_mo" 0x00007f4e76937ed5 in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  9    Thread 0x7f4c5cbf2e80 (LWP 200153) "miniqmc_sync_mo" 0x00007f4e769115fb in __kmp_get_random () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  10   Thread 0x7f4c3fffef00 (LWP 200154) "miniqmc_sync_mo" 0x00007f4e76932503 in __kmp_steal_task(kmp_info*, int, kmp_task_team*, std::atomic<int>*, int*, int) ()
   from /soft/compilers/llvm/master-nightly/lib/libomp.so
  11   Thread 0x7f4c3f7fcf80 (LWP 200155) "miniqmc_sync_mo" 0x00007f4e76937cab in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  12   Thread 0x7f4c3effb000 (LWP 200156) "miniqmc_sync_mo" 0x00007f4e76937ed5 in int __kmp_execute_tasks_32<false, false>(kmp_info*, int, kmp_flag_32<false, false>*, int, int*, void*, int) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  13   Thread 0x7f4c3e7f9080 (LWP 200157) "miniqmc_sync_mo" 0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
  14   Thread 0x7f4c3dff7100 (LWP 200158) "miniqmc_sync_mo" 0x00007f4e76932503 in __kmp_steal_task(kmp_info*, int, kmp_task_team*, std::atomic<int>*, int*, int) ()
   from /soft/compilers/llvm/master-nightly/lib/libomp.so
  15   Thread 0x7f4c3d7f5180 (LWP 200159) "miniqmc_sync_mo" 0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
  16   Thread 0x7f4c3cff3200 (LWP 200160) "miniqmc_sync_mo" 0x00007f4e76937217 in int __kmp_execute_tasks_64<false, true>(kmp_info*, int, kmp_flag_64<false, true>*, int, int*, void*, int)
    () from /soft/compilers/llvm/master-nightly/lib/libomp.so
  17   Thread 0x7f4c27fff280 (LWP 200161) "miniqmc_sync_mo" 0x00007f4e76932519 in __kmp_steal_task(kmp_info*, int, kmp_task_team*, std::atomic<int>*, int*, int) ()
   from /soft/compilers/llvm/master-nightly/lib/libomp.so
```
T2 this is a service thread
```
[Switching to thread 2 (Thread 0x7f4e65897700 (LWP 200145))]
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
#1  0x00007f4e6e342e28 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#2  0x00007f4e6e33cfde in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#3  0x00007f4e6e2d20a6 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#4  0x00007f4e6e2b397e in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#5  0x00007f4e6e2c6e52 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#6  0x00007f4e6e282217 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#7  0x00007f4e766046ea in start_thread () from /lib64/libpthread.so.0
#8  0x00007f4e7651c94f in clone () from /lib64/libc.so.6
```
T13
```
(gdb) t 13
[Switching to thread 13 (Thread 0x7f4c3e7f9080 (LWP 200157))]
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
#1  0x00007f4e6e342e28 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#2  0x00007f4e6e33cfde in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#3  0x00007f4e6e33d629 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#4  0x00007f4e6e2b74d2 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#5  0x00007f4e6e2b732a in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#6  0x00007f4e6e2ab0a9 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#7  0x00007f4e65ae7372 in llvm::omp::target::plugin::AMDGPUSignalTy::wait(unsigned long, llvm::omp::target::RPCServerTy*, llvm::omp::target::plugin::GenericDeviceTy*) const ()
   from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#8  0x00007f4e65af1ca5 in llvm::omp::target::plugin::AMDGPUDeviceTy::synchronizeImpl(__tgt_async_info&) () from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#9  0x00007f4e65b0e778 in __tgt_rtl_synchronize () from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#10 0x00007f4e76865d37 in AsyncInfoTy::synchronize() [clone .localalias] () from /soft/compilers/llvm/master-nightly/lib/libomptarget.so.18git
#11 0x00007f4e76861d88 in __tgt_target_kernel () from /soft/compilers/llvm/master-nightly/lib/libomptarget.so.18git
#12 0x00005608a35084c2 in qmcplusplus::SoaDistanceTableABOMPTarget<double, 3u, 40>::evaluate(qmcplusplus::ParticleSet&) ()
#13 0x00005608a3477fcd in qmcplusplus::ParticleSet::update(bool) ()
#14 0x00005608a340fd3e in qmcplusplus::NonLocalPP<double>::evaluate(qmcplusplus::ParticleSet const&, qmcplusplus::WaveFunction&) ()
#15 0x00005608a340a91d in qmcplusplus::NonLocalPP<double>::multi_evaluate(std::vector<qmcplusplus::NonLocalPP<double>*, std::allocator<qmcplusplus::NonLocalPP<double>*> > const&, std::vector<qmcplusplus::WaveFunction*, std::allocator<qmcplusplus::WaveFunction*> > const&, std::vector<qmcplusplus::ParticleSet*, std::allocator<qmcplusplus::ParticleSet*> > const&) [clone .omp_outlined] ()
#16 0x00007f4e7699fe93 in __kmp_invoke_microtask () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#17 0x00007f4e7691a84b in __kmp_fork_call () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#18 0x00007f4e76905271 in __kmpc_fork_call () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#19 0x00005608a340a5c1 in main.omp_outlined ()
#20 0x00007f4e7699fe93 in __kmp_invoke_microtask () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#21 0x00007f4e7690fd0f in __kmp_invoke_task_func () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#22 0x00007f4e769125f9 in __kmp_launch_thread () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#23 0x00007f4e7697ff24 in __kmp_launch_worker(void*) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#24 0x00007f4e766046ea in start_thread () from /lib64/libpthread.so.0
#25 0x00007f4e7651c94f in clone () from /lib64/libc.so.6
```
T15
```
(gdb) t 15
[Switching to thread 15 (Thread 0x7f4c3d7f5180 (LWP 200159))]
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f4e76511b07 in ioctl () from /lib64/libc.so.6
#1  0x00007f4e6e342e28 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#2  0x00007f4e6e33cfde in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#3  0x00007f4e6e33d629 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#4  0x00007f4e6e2b74d2 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#5  0x00007f4e6e2b732a in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#6  0x00007f4e6e2ab0a9 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#7  0x00007f4e65ae7372 in llvm::omp::target::plugin::AMDGPUSignalTy::wait(unsigned long, llvm::omp::target::RPCServerTy*, llvm::omp::target::plugin::GenericDeviceTy*) const ()
   from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#8  0x00007f4e65af1ca5 in llvm::omp::target::plugin::AMDGPUDeviceTy::synchronizeImpl(__tgt_async_info&) () from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#9  0x00007f4e65b0e778 in __tgt_rtl_synchronize () from /soft/compilers/llvm/master-nightly/lib/libomptarget.rtl.amdgpu.so
#10 0x00007f4e76865d37 in AsyncInfoTy::synchronize() [clone .localalias] () from /soft/compilers/llvm/master-nightly/lib/libomptarget.so.18git
#11 0x00007f4e76861d88 in __tgt_target_kernel () from /soft/compilers/llvm/master-nightly/lib/libomptarget.so.18git
#12 0x00005608a3465c3f in qmcplusplus::einspline_spo_omp<double>::evaluateDetRatios(qmcplusplus::VirtualParticleSet const&, qmcplusplus::Vector<double, std::allocator<double> >&, qmcplusplus::Vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> >&) ()
#13 0x00005608a345a3ea in qmcplusplus::DiracDeterminant<qmcplusplus::DelayedUpdate<double, double> >::evaluateRatios(qmcplusplus::VirtualParticleSet&, std::vector<double, std::allocator<double> >&) ()
#14 0x00005608a3412081 in qmcplusplus::WaveFunction::evaluateRatios(qmcplusplus::VirtualParticleSet&, std::vector<double, std::allocator<double> >&) ()
#15 0x00005608a340fd50 in qmcplusplus::NonLocalPP<double>::evaluate(qmcplusplus::ParticleSet const&, qmcplusplus::WaveFunction&) ()
#16 0x00005608a340a91d in qmcplusplus::NonLocalPP<double>::multi_evaluate(std::vector<qmcplusplus::NonLocalPP<double>*, std::allocator<qmcplusplus::NonLocalPP<double>*> > const&, std::vector<qmcplusplus::WaveFunction*, std::allocator<qmcplusplus::WaveFunction*> > const&, std::vector<qmcplusplus::ParticleSet*, std::allocator<qmcplusplus::ParticleSet*> > const&) [clone .omp_outlined] ()
#17 0x00007f4e7699fe93 in __kmp_invoke_microtask () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#18 0x00007f4e7691a84b in __kmp_fork_call () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#19 0x00007f4e76905271 in __kmpc_fork_call () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#20 0x00005608a340a5c1 in main.omp_outlined ()
#21 0x00007f4e7699fe93 in __kmp_invoke_microtask () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#22 0x00007f4e7690fd0f in __kmp_invoke_task_func () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#23 0x00007f4e769125f9 in __kmp_launch_thread () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#24 0x00007f4e7697ff24 in __kmp_launch_worker(void*) () from /soft/compilers/llvm/master-nightly/lib/libomp.so
#25 0x00007f4e766046ea in start_thread () from /lib64/libpthread.so.0
#26 0x00007f4e7651c94f in clone () from /lib64/libc.so.6
```
