### ISSUE TITLE
[BOLT] Segmentation fault after optimization of shared library with relocation mode enabled

### ISSUE THREAD

**Issue by wh015** [llvm/llvm-project#64634]
Hi guys!

We are trying to optimize one of our shared libraries with BOLT but faced an issue with segfault after the library is optimized or instrumented. It's enough just to link the processed library to any application, even simple one like "hello world", to reproduce the issue, and it happens during loading other dynamic libraries that the initial library depends on.
```
Breakpoint 6, 0x00007ffff60c8620 in __cxa_atexit@plt () from /home/ppreblagin/src/git/test-router/lib/../lib/liblog4cplus.so.8
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6271b5e in __GI__IO_fwrite (buf=0x55555556b2a0, size=93824992326432, count=7, fp=0x636f6d7070616374) at iofwrite.c:35
35      iofwrite.c: No such file or directory.
#0  0x00007ffff6271b5e in __GI__IO_fwrite (buf=0x55555556b2a0, size=93824992326432, count=7, fp=0x636f6d7070616374) at iofwrite.c:35

#1  0x00007ffff75a9c68 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from lib/router.so.26
#2  0x00007ffff61313c9 in std::pair<std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<Catch::IReporterFactory> > >, bool> std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<Catch::IReporterFactory> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<Catch::IReporterFactory> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<Catch::IReporterFactory> > > >::_M_emplace_unique<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Catch::IReporterFactory> const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Catch::IReporterFactory> const&) () from /home/ppreblagin/src/git/test-router/lib/../lib/liblog4cplus.so.8
#3  0x00007ffff6131e57 in Catch::ReporterRegistrar<Catch::ConsoleReporter>::ReporterRegistrar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /home/ppreblagin/src/git/test-router/lib/../lib/liblog4cplus.so.8
#4  0x00007ffff60dd969 in _GLOBAL__sub_I_global_init.cxx () from /home/ppreblagin/src/git/test-router/lib/../lib/liblog4cplus.so.8
#5  0x00007ffff7fe438a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe3b8, env=env@entry=0x7fffffffe3c8) at dl-init.c:72
#6  0x00007ffff7fe4486 in call_init (env=0x7fffffffe3c8, argv=0x7fffffffe3b8, argc=1, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe3b8, env=0x7fffffffe3c8) at dl-init.c:119
#8  0x00007ffff7fd60ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000001 in ?? ()
#10 0x00007fffffffe64c in ?? ()
#11 0x0000000000000000 in ?? ()
```
The library is compiled and linked with
```
-O3 -DNDEBUG -fPIC -Wall -Wextra -Wnon-virtual-dtor -Wcast-align -fno-reorder-blocks-and-partition -std=c++17
```
and 
```
-fPIC -O3 -DNDEBUG -Wl,--exclude-libs=ALL -Wl,--disable-new-dtags -Wl,--start-group -Wl,--emit-relocs -shared -Wl,-soname,router.so.26 <list-of-dependencies>
```
After a research I figured out it's related to relocation mode, and `-relocs=false` helps to avoid the issue sacrificing some optimization options.  

I've attached logs to the ticket:
[gdb.txt](https://github.com/llvm/llvm-project/files/12326707/gdb.txt)
[llvm-bolt.txt](https://github.com/llvm/llvm-project/files/12326708/llvm-bolt.txt)
[perf2bolt.txt](https://github.com/llvm/llvm-project/files/12326709/perf2bolt.txt)

**Comment by llongint** [comment]
From the llvm-bolt.txt log, we can still see function symbols with the .cold suffix. This may indicate that some of the .o files (\<list-of-dependencies\>) were still compiled without the -fno-reorder-blocks-and-partition compiler option. You might want to check your compilation script to ensure that this option is applied consistently throughout.

Alternatively, you can try reverting the patch [D127464](https://reviews.llvm.org/D127464) - this is my personal suggestion.

**Comment by aaupov** [comment]
Please check with LLVM 17 or trunk version. The issue might have to do with split function support which has been improved since the version you're using (LLVM release 16.x/ 7cbf1a2591520c2491aa35339f227775f4d3adf6). Likely fix is https://github.com/llvm/llvm-project/commit/c49941bd0d7f2a7a9ddbdce29fd584827d00dd06 which is included in LLVM 17.
