### ISSUE TITLE
[libomptarget] potential deadlock in amdgpu plugin

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#64681]
Tries to guess why https://github.com/llvm/llvm-project/issues/64572 happens.

In a threaded code,
T1 gets Stream 1 and summit Event 1
T2 gets Stream 2 and summit Event 2
T3 gets Stream 3 and summit Event 3
now for what ever reason each thread picks up the next stream
T1 gets Stream 2 and summit Event 1. Tries to lock stream 1 and 2
T2 gets Stream 3 and summit Event 2. Tries to lock stream 2 and 3
T3 gets Stream 1 and summit Event 3. Tries to lock stream 3 and 1
at https://github.com/llvm/llvm-project/blob/e63382542f0941b550839a226d0e2ad02a9de328/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp#L1436
I feel deadlock may happen and we need to avoid actively waiting a stream through its recorded stream.

**Comment by ye-luo** [comment]
```
(gdb) info threads 
  Id   Target Id                                            Frame 
* 1    Thread 0x7f1867604b00 (LWP 229619) "miniqmc_sync_mo" 0x00007f185c3e8bb0 in pthread_mutex_lock@plt () from /soft/compilers/llvm/main-patched/lib/libomptarget.rtl.amdgpu.so
  2    Thread 0x7f185877a700 (LWP 229621) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  3    Thread 0x7f16560feb80 (LWP 229623) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  4    Thread 0x7f16558fcc00 (LWP 229624) "miniqmc_sync_mo" 0x00007f187076970c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7f16550fac80 (LWP 229625) "miniqmc_sync_mo" 0x00007f18707650fc in pthread_mutex_lock () from /lib64/libpthread.so.0
  6    Thread 0x7f16548f8d00 (LWP 229626) "miniqmc_sync_mo" 0x00007f1870766a41 in __pthread_mutex_unlock_usercnt () from /lib64/libpthread.so.0
  7    Thread 0x7f1652ae4d80 (LWP 229627) "miniqmc_sync_mo" 0x00007f187076970c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  8    Thread 0x7f1650cd0e00 (LWP 229628) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  9    Thread 0x7f164f9c5e80 (LWP 229629) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  10   Thread 0x7f164f1c3f00 (LWP 229630) "miniqmc_sync_mo" 0x00007f18707653b4 in pthread_mutex_trylock () from /lib64/libpthread.so.0
  11   Thread 0x7f164deb8f80 (LWP 229631) "miniqmc_sync_mo" 0x00007f187076970c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  12   Thread 0x7f164cbae000 (LWP 229632) "miniqmc_sync_mo" 0x00007f187076970c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  13   Thread 0x7f164b8a3080 (LWP 229633) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  14   Thread 0x7f1649a8f100 (LWP 229634) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  15   Thread 0x7f1648784180 (LWP 229635) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  16   Thread 0x7f1647f82200 (LWP 229636) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
  17   Thread 0x7f164616e280 (LWP 229637) "miniqmc_sync_mo" 0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
```
all the pthread_cond_wait and are stuck at `llvm::omp::target::plugin::AMDGPUStreamTy::waitEvent` scoped_lock.
```
(gdb) t 6
[Switching to thread 6 (Thread 0x7f16548f8d00 (LWP 229626))]
#0  0x00007f1870766a41 in __pthread_mutex_unlock_usercnt () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f1870766a41 in __pthread_mutex_unlock_usercnt () from /lib64/libpthread.so.0
#1  0x00007f185a0211be in __gthread_mutex_unlock (__mutex=<optimized out>)
    at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/x86_64-pc-linux-gnu/bits/gthr-default.h:779
#2  std::mutex::unlock (this=<optimized out>) at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/bits/std_mutex.h:118
#3  std::unique_lock<std::mutex>::unlock (this=<optimized out>)
    at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/bits/unique_lock.h:197
#4  std::unique_lock<std::mutex>::~unique_lock (this=<optimized out>)
    at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/bits/unique_lock.h:106
#5  std::lock<std::mutex, std::mutex> (__l1=..., __l2=...) at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/mutex:555
#6  std::scoped_lock<std::mutex, std::mutex>::scoped_lock (__m=..., __m=..., this=<optimized out>)
    at /soft/compilers/gcc/9.5.0/x86_64-suse-linux/lib/gcc/x86_64-pc-linux-gnu/9.5.0/../../../../include/c++/9.5.0/mutex:570
#7  llvm::omp::target::plugin::AMDGPUStreamTy::waitEvent (this=this@entry=0x50f000060580, Event=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:1436
#8  0x00007f185a068e7c in llvm::omp::target::plugin::AMDGPUEventTy::wait (this=this@entry=0x50600001f6a0, Stream=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:1394
#9  0x00007f185a0319f7 in llvm::omp::target::plugin::AMDGPUDeviceTy::waitEventImpl (this=<optimized out>, EventPtr=<optimized out>, AsyncInfoWrapper=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:2282
#10 0x00007f185a0a2135 in llvm::omp::target::plugin::GenericDeviceTy::waitEvent (this=0x1, EventPtr=0x50600001f6a0, AsyncInfo=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.cpp:1234
#11 __tgt_rtl_wait_event (DeviceId=<optimized out>, EventPtr=<optimized out>, AsyncInfoPtr=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/common/PluginInterface/PluginInterface.cpp:1692
#12 0x00007f18709e6205 in DeviceTy::waitEvent (this=0x511000004c80, Event=0x50600001f6a0, AsyncInfo=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/device.cpp:767
#13 DeviceTy::getTargetPointer (this=<optimized out>, HDTTMap=..., HstPtrBegin=0x51100004dc00, HstPtrBase=<optimized out>, TgtPadding=<optimized out>, Size=<optimized out>, 
    HstPtrName=<optimized out>, HasFlagTo=<optimized out>, HasFlagAlways=<optimized out>, IsImplicit=<optimized out>, UpdateRefCount=<optimized out>, HasCloseModifier=<optimized out>, 
    HasPresentModifier=<optimized out>, HasHoldModifier=<optimized out>, AsyncInfo=..., OwnedTPR=<optimized out>, ReleaseHDTTMap=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/device.cpp:375
#14 0x00007f1870a0c7ae in targetDataBegin (Loc=<optimized out>, Device=..., ArgNum=11, ArgsBase=<optimized out>, Args=<optimized out>, ArgSizes=<optimized out>, ArgTypes=<optimized out>, 
    ArgNames=<optimized out>, ArgMappers=<optimized out>, AsyncInfo=..., FromMapper=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/omptarget.cpp:690
#15 0x00007f1870a145bd in (anonymous namespace)::processDataBefore (Loc=0x55f0d2914850, ArgNum=11, ArgBases=0x7f16548f64b0, Args=0x7f16548f6458, ArgSizes=0x7f16548f6570, 
    ArgTypes=0x55f0d28352a0, ArgNames=0x55f0d2914870, ArgMappers=0x0, TgtArgs=..., TgtOffsets=..., PrivateArgumentManager=..., AsyncInfo=..., DeviceId=<optimized out>, 
    HostPtr=<optimized out>) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/omptarget.cpp:1452
#16 target (Loc=<optimized out>, Device=..., HostPtr=<optimized out>, KernelArgs=..., AsyncInfo=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/omptarget.cpp:1653
#17 0x00007f18709f8a36 in targetKernel<AsyncInfoTy> (Loc=0x55f0d2914850, DeviceId=<optimized out>, NumTeams=<optimized out>, ThreadLimit=<optimized out>, 
    HostPtr=0x55f0d2835230 <.__omp_offloading_31_7907dfb0__ZN11qmcplusplus17einspline_spo_ompIdE17evaluateDetRatiosERKNS_18VirtualParticleSetERNS_6VectorIdSaIdEEERKS7_RSt6vectorIdS6_E_l248.region_id>, KernelArgs=0x7f16548f6508) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/interface.cpp:303
#18 __tgt_target_kernel (Loc=0x55f0d2914850, DeviceId=<optimized out>, NumTeams=<optimized out>, ThreadLimit=<optimized out>, HostPtr=<optimized out>, KernelArgs=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/src/interface.cpp:333
#19 0x000055f0d2777b9f in qmcplusplus::einspline_spo_omp<double>::evaluateDetRatios (this=0x519000100480, VP=..., psi=..., psiinv=..., ratios=...)
    at /home/yeluo/opt/miniqmc/src/QMCWaveFunctions/einspline_spo_omp.cpp:248
#20 0x000055f0d276c34a in qmcplusplus::DiracDeterminant<qmcplusplus::DelayedUpdate<double, double> >::evaluateRatios (this=0x51a0000e0480, VP=..., ratios=...)
    at /home/yeluo/opt/miniqmc/src/QMCWaveFunctions/DiracDeterminant.cpp:221
#21 0x000055f0d2723fe1 in qmcplusplus::WaveFunction::evaluateRatios (this=0x5260000914d0, VP=..., ratios=...) at /home/yeluo/opt/miniqmc/src/QMCWaveFunctions/WaveFunction.cpp:263
#22 0x000055f0d2721cb0 in qmcplusplus::NonLocalPP<double>::evaluate (this=0x526000091540, els=..., wf=...) at /home/yeluo/opt/miniqmc/src/Drivers/NonLocalPP.hpp:135
#23 0x000055f0d271c87d in _ZN11qmcplusplus10NonLocalPPIdE14multi_evaluateERKSt6vectorIPS1_SaIS3_EERKS2_IPNS_12WaveFunctionESaIS9_EERKS2_IPNS_11ParticleSetESaISF_EE.omp_outlined_debug__ (
    nlpp_list=..., .global_tid.=<optimized out>, .bound_tid.=<optimized out>, P_list=..., WF_list=...) at /home/yeluo/opt/miniqmc/src/Drivers/NonLocalPP.hpp:147
#24 _ZN11qmcplusplus10NonLocalPPIdE14multi_evaluateERKSt6vectorIPS1_SaIS3_EERKS2_IPNS_12WaveFunctionESaIS9_EERKS2_IPNS_11ParticleSetESaISF_EE.omp_outlined(void) const (
    .global_tid.=<optimized out>, .bound_tid.=<optimized out>, nlpp_list=..., P_list=..., WF_list=...) at /home/yeluo/opt/miniqmc/src/Drivers/NonLocalPP.hpp:145
#25 0x00007f1870d3f3f3 in __kmp_invoke_microtask () from /soft/compilers/llvm/main-patched/lib/libomp.so
#26 0x00007f1870b904df in __kmp_serial_fork_call (loc=<optimized out>, gtid=-1014412285, call_context=<optimized out>, argc=3, microtask=<optimized out>, invoker=<optimized out>, 
    master_th=<optimized out>, parent_team=<optimized out>, ompt_parallel_data=<optimized out>, return_address=<optimized out>, parent_task_data=<optimized out>, ap=<optimized out>)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/kmp_runtime.cpp:1804
#27 0x00007f1870b8add8 in __kmp_fork_call (loc=0x55f0d29134f0, gtid=12, call_context=fork_context_intel, argc=3, 
    microtask=0x55f0d271c7c0 <_ZN11qmcplusplus10NonLocalPPIdE14multi_evaluateERKSt6vectorIPS1_SaIS3_EERKS2_IPNS_12WaveFunctionESaIS9_EERKS2_IPNS_11ParticleSetESaISF_EE.omp_outlined(void) const>, invoker=0x7f1870ba3990 <__kmp_invoke_task_func(int)>, ap=0x7f16548f70e0) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/kmp_runtime.cpp:2028
#28 0x00007f1870b521a5 in __kmpc_fork_call (loc=0x55f0d29134f0, argc=0, microtask=0x50f000060600)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/kmp_csupport.cpp:300
#29 0x000055f0d271c521 in qmcplusplus::NonLocalPP<double>::multi_evaluate (nlpp_list=..., WF_list=..., P_list=..., this=<optimized out>)
    at /home/yeluo/opt/miniqmc/src/Drivers/NonLocalPP.hpp:145
#30 main.omp_outlined_debug__.68 (nbatches=@0x7ffc32219dfc: 16, .global_tid.=<optimized out>, .bound_tid.=<optimized out>, mover_list=..., pset_res_batches=..., Timers=..., 
    nsubsteps=<optimized out>, nels=<optimized out>, accept=<optimized out>, run_pseudo=<optimized out>) at /home/yeluo/opt/miniqmc/src/Drivers/miniqmc_sync_move.cpp:521
#31 main.omp_outlined.69(void) const (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, nbatches=@0x7ffc32219dfc: 16, mover_list=..., pset_res_batches=..., Timers=..., 
    nsubsteps=@0x7ffc32219e20: 1, nels=@0x7ffc32219e0c: 384, accept=@0x7ffc32219f00: 0.5, run_pseudo=@0x7ffc32219db2: true)
    at /home/yeluo/opt/miniqmc/src/Drivers/miniqmc_sync_move.cpp:436
#32 0x00007f1870d3f3f3 in __kmp_invoke_microtask () from /soft/compilers/llvm/main-patched/lib/libomp.so
#33 0x00007f1870ba3e7e in __kmp_invoke_task_func (gtid=12) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/kmp_runtime.cpp:7654
#34 0x00007f1870ba011c in __kmp_launch_thread (this_thr=0x51b0000093c0) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/kmp_runtime.cpp:6060
#35 0x00007f1870cddb0f in __kmp_launch_worker (thr=thr@entry=0x51b0000093c0) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/runtime/src/z_Linux_util.cpp:526
#36 0x00007f1878e37406 in asan_thread_start (arg=0x7f1866ac8000) at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:234
#37 0x00007f18707626ea in start_thread () from /lib64/libpthread.so.0
#38 0x00007f187067a94f in clone () from /lib64/libc.so.6
```
all the ioctl stuck as
```#0  0x00007f187066fb07 in ioctl () from /lib64/libc.so.6
#1  0x00007f1878ebed0c in ___interceptor_ioctl (d=3, request=3222817548)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1813
#2  0x00007f18684a0e28 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#3  0x00007f186849afde in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#4  0x00007f186849b629 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#5  0x00007f18684154d2 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#6  0x00007f186841532a in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#7  0x00007f18684090a9 in ?? () from /soft/compilers/rocm/rocm-5.5.0/lib/libhsa-runtime64.so.1
#8  0x00007f185a0659b5 in llvm::omp::target::plugin::AMDGPUSignalTy::wait (this=0x502000006790, ActiveTimeout=<optimized out>, RPCServer=0x0, Device=0x51a00000c080)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:529
#9  0x00007f185a065818 in llvm::omp::target::plugin::AMDGPUStreamTy::synchronize (this=this@entry=0x50f000007cf0)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:1319
#10 0x00007f185a02e6b3 in llvm::omp::target::plugin::AMDGPUDeviceTy::synchronizeImpl (this=0x51a00000c080, AsyncInfo=...)
    at /gpfs/jlse-fs0/users/yeluo/opt/llvm-clang/llvm-project/openmp/libomptarget/plugins-nextgen/amdgpu/src/rtl.cpp:2019
#11 0x00007f185a09eff0 in llvm::omp::target::plugin::GenericDeviceTy::synchronize (this=0xc0184b0c, AsyncInfo=0x7f1646702ae0)
```
