### ISSUE TITLE
AttributeError when using Pdb in lldb's script interpreter

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#66356]
This was originally reported by LambdaKnight on Discord.

```
$ ./bin/lldb
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
>>> breakpoint()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.8/pdb.py", line 1610, in set_trace
    pdb = Pdb()
  File "/usr/lib/python3.8/pdb.py", line 159, in __init__
    readline.set_completer_delims(' \t\n`@#$%^&*()=+[{]}\\|;:\'",<>?')
AttributeError: module 'lldb_editline' has no attribute 'set_completer_delims'
```

I think this is because our readline replacement `lldb/source/Plugins/ScriptInterpreter/Python/PythonReadline.cpp` is too minimal. It would be great if this could be fixed so we can recommend Pdb as the go to for debugging anything Python related in lldb.

Stubbing out the method is the first step, then figuring out what it's supposed to do.

**Comment by DavidSpickett** [comment]
@medismailben as code owner for Python.

**Comment by DavidSpickett** [comment]
Duplicate of https://github.com/llvm/llvm-project/issues/66092.

**Comment by medismailben** [comment]
@DavidSpickett Sorry, I'm in vacation until the 24th and I can't look at this currently :/ May be @JDevlieghere can help with this ?

**Comment by topke011** [comment]
@DavidSpickett @medismailben any workaround for this issue?
