### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by CHzhangi** [llvm/llvm-project#73434]
root@4ee3c0dff15b:/workspace# model_transform.py  --model_name fsr  --input_shape [[1,3,200,200]]  --model_def FSRCNN-pytorch-master/fsrcnn.pt  --mlir fsr.mlir
SOPHGO Toolchain v1.3.116-gf735aff3-20230821
2023/11/26 17:36:44 - INFO : 
	 _____________________________________________________ 
	| preprocess:                                           |
	|   (x - mean) * scale                                  |
	'-------------------------------------------------------'
  config Preprocess args : 
	resize_dims           : same to net input dims
	keep_aspect_ratio     : False
	keep_ratio_mode       : letterbox
	pad_value             : 0
	pad_type              : center
	--------------------------
	mean                  : [0.0, 0.0, 0.0]
	scale                 : [1.0, 1.0, 1.0]
	--------------------------
	pixel_format          : bgr
	channel_format        : nchw

Save mlir file: fsr_origin.mlir
[Running]: tpuc-opt fsr_origin.mlir --shape-infer --canonicalize --extra-optimize -o fsr.mlir 
tpuc-opt: ../lib/Dialect/Top/Interfaces/Conv.cpp:137: void tpu_mlir::top::ConvOp::shape_inference(): Assertion `input_shape.size() == filter_shape.size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: tpuc-opt fsr_origin.mlir --init --shape-infer --canonicalize --extra-optimize --deinit --mlir-print-debuginfo -o fsr.mlir
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):

0  tpuc-opt        0x00005654ad126dea
1  tpuc-opt        0x00005654ad1240ec
2  libpthread.so.0 0x00007f5823b3f980
3  libc.so.6       0x00007f5822c0ce87 gsignal + 199
4  libc.so.6       0x00007f5822c0e7f1 abort + 321
5  libc.so.6       0x00007f5822bfe3fa
6  libc.so.6       0x00007f5822bfe472
7  tpuc-opt        0x00005654acd10774
8  tpuc-opt        0x00005654accab0c7
9  tpuc-opt        0x00005654acd9dfb4
10 tpuc-opt        0x00005654ac4a9e7c
11 tpuc-opt        0x00005654acda01c1
12 tpuc-opt        0x00005654ace8076e
13 tpuc-opt        0x00005654ace81658
14 tpuc-opt        0x00005654ace81c9f
15 tpuc-opt        0x00005654ac444e45
16 tpuc-opt        0x00005654ac445a5b
17 tpuc-opt        0x00005654ac445c42
18 tpuc-opt        0x00005654ad0a46ef
19 tpuc-opt        0x00005654ac43eb72
20 tpuc-opt        0x00005654ac445ff7
21 tpuc-opt        0x00005654ac42f6e0
22 libc.so.6       0x00007f5822befc87 __libc_start_main + 231
23 tpuc-opt        0x00005654ac43c26a

Aborted (core dumped)
Traceback (most recent call last):
  File "/workspace/python/tools/model_transform.py", line 273, in <module>
    tool.model_transform(args.mlir, args.add_postprocess)
  File "/workspace/python/tools/model_transform.py", line 51, in model_transform
    mlir_opt_for_top(mlir_origin, self.mlir_file, add_postprocess)
  File "/workspace/python/utils/mlir_shell.py", line 60, in mlir_opt_for_top
    _os_system(cmd)
  File "/workspace/python/utils/mlir_shell.py", line 50, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt fsr_origin.mlir --shape-infer --canonicalize --extra-optimize -o fsr.mlir

**Comment by CHzhangi** [comment]
system: Ubuntu 18.04
