### ISSUE TITLE
[build issue] llvmtag-17.0.5 build failed on windows10

### ISSUE THREAD

**Issue by spobit** [llvm/llvm-project#73607]
platform: windows10
llvm-version: llvmtag-17.0.5
build script:

  ```
  CMDs=(
      "cmake"
      "-G \"${GENERATOR}\""
      "-A ${ARCH_CONFIG}"
      "-DCMAKE_BUILD_TYPE=${DEBUG_CONFIG}"
      "-DCMAKE_INSTALL_PREFIX=\"${DEPLOY_WORKSPACE_DIR}\""
      "-DLLVM_ENABLE_PROJECTS=\"clang;compiler-rt\""
      "-DLLVM_OPTIMIZED_TABLEGEN=ON"
      "\"${WORKSPACE_DIR}/llvm\""
      "||"
      "(echo \"Error at generate makefile\"; exit 1;)"
  )
  ```

problem:

  ```
    llvm-jitlink.vcxproj -> X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\Release\bin\llvm-jitlink.exe
    Generating export list for LLVM-C
    nm=X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/NATIVE/Release/bin/llvm-nm.exe, lib=X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/Release/lib/LLVMDemangle.lib
  
    Traceback (most recent call last):
      File "X:\_build_tools\llvm\llvm-project-17.0.5.src\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 125, in <module>
        main()
      File "X:\_build_tools\llvm\llvm-project-17.0.5.src\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 121, in main
        gen_llvm_c_export(ns.output, ns.underscore, libs, ns.nm)
      File "X:\_build_tools\llvm\llvm-project-17.0.5.src\llvm\tools\llvm-shlib\gen-msvc-exports.py", line 73, in gen_llvm_c_export
        check_call([nm, "-g", lib], stdout=dumpout_f)
      File "C:\_tools\Python\Python3.10.9-x64-official\lib\subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\_tools\Python\Python3.10.9-x64-official\lib\subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\_tools\Python\Python3.10.9-x64-official\lib\subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\_tools\Python\Python3.10.9-x64-official\lib\subprocess.py", line 1440, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
  x:\_apps\visual-studio\2022\community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): error MSB8066: Custom build for 'X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\CMakeFiles\2e5e782a74d743b405b2113da1f77187\libllvm-c.exports.rule;X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\CMakeFiles\52eb7e572e46ba61ba669126ec6320d8\LLVM-C.def.rule;X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\CMakeFiles\9f8cedb5dcd9b526bc5b422f7faa3ac6\LLVM-C_exports.rule' exited with code 1. [X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\tools\llvm-shlib\LLVM-C_exports.vcxproj]
    lli-child-target.vcxproj -> X:\_build_tools\llvm\llvm-project-17.0.5.src-ci\_build\x64r\Release\bin\lli-child-target.exe
  ```

```
$ ls "X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/NATIVE/Release/bin/llvm-nm.exe"
ls: cannot access 'X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/NATIVE/Release/bin/llvm-nm.exe': No such file or directory

$ ls "X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/Release/bin/llvm-nm.exe"
X:/_build_tools/llvm/llvm-project-17.0.5.src-ci/_build/x64r/Release/bin/llvm-nm.exe*
```

**Comment by ebraheemabbas** [comment]
me team also face this issue , seems it is related to -DLLVM_OPTIMIZED_TABLEGEN=ON
where it is may enable the LLVM_USE_HOST_TOOLS and that will make cmake to run build_native_tool
but actually there is no rule to build the llvm-nm within our settings
