### ISSUE TITLE
#74163 reverted #73777 and followup fixes

### ISSUE THREAD

**Issue by vitalybuka** [llvm/llvm-project#74177]

**Comment by vitalybuka** [comment]
#74163 reverted #73777 and followup fixes

**Comment by thurstond** [comment]
tl;dr it's not a bug in HWASan; but it's also not directly a bug in the reverted patch. There's likely a latent bug elsewhere that was exposed by the patch.

**Not a HWASan bug:** I re-ran the buildbot script at that revision (eef8e1d206dc01c081a0ca29b7f9e0c39d33446e), but with MSan, and it finds uninitialized memory (output below). My guess is sometimes it's not initialized to zero, and that leads the out of bounds access that HWASan caught.

**Not a bug in the reverted patch:** MSan also reports the same bug at the previous git revision (3246a32d3f6b97467ecdf2682d44a6515dbccf96).

```
# On Arm, modified to use msan-track-origins:
BUILDBOT_CLOBBER= BUILDBOT_REVISION=eef8e1d206dc01c081a0ca29b7f9e0c39d33446e llvm-zorg/zorg/buildbot/builders/sanitizers/buildbot_fast.sh

-- Build files have been written to: /home/thurston/scratch_dir2/llvm_build_msan_track_origins
+ ninja
[1986/7022] Building R600GenDAGISel.inc...
FAILED: lib/Target/AMDGPU/R600GenDAGISel.inc /home/thurston/scratch_dir2/llvm_build_msan_track_origins/lib/Target/AMDGPU/R600GenDAGISel.inc 
cd /home/thurston/scratch_dir2/llvm_build_msan_track_origins && /home/thurston/scratch_dir2/llvm_build_msan_track_origins/bin/llvm-tblgen -gen-dag-isel -I /home/thurston/scratch_dir2/llvm-project/llvm/lib/Target/AMDGPU -I/home/thurston/scratch_dir2/llvm_build_msan_track_origins/include -I/home/thurston/scratch_dir2/llvm-project/llvm/include -I /home/thurston/scratch_dir2/llvm-project/llvm/lib/Target -omit-comments /home/thurston/scratch_dir2/llvm-project/llvm/lib/Target/AMDGPU/R600.td --write-if-changed -o lib/Target/AMDGPU/R600GenDAGISel.inc -d lib/Target/AMDGPU/R600GenDAGISel.inc.d
==107855==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xaaaae3af7f90 in get /home/thurston/scratch_dir2/llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:205:27
    #1 0xaaaae3af7f90 in getChild /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.h:732:62
    #2 0xaaaae3af7f90 in GenerateVariantsOf(llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>, std::__1::vector<llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>, std::__1::allocator<llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>>>&, llvm::CodeGenDAGPatterns&, llvm::StringSet<llvm::MallocAllocator> const&) /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:4710:35
    #3 0xaaaae3add534 in llvm::CodeGenDAGPatterns::GenerateVariants() /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:4750:5
    #4 0xaaaae3ad1254 in llvm::CodeGenDAGPatterns::CodeGenDAGPatterns(llvm::RecordKeeper&, std::__1::function<void (llvm::TreePattern*)>) /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:3198:3
    #5 0xaaaae3c882cc in DAGISelEmitter /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/DAGISelEmitter.cpp:31:58
    #6 0xaaaae3c882cc in llvm::TableGen::Emitter::OptClass<(anonymous namespace)::DAGISelEmitter>::run(llvm::RecordKeeper&, llvm::raw_ostream&) /home/thurston/scratch_dir2/llvm-project/llvm/include/llvm/TableGen/TableGenBackend.h:44:56
    #7 0xaaaae42903f8 in llvm::TableGenMain(char const*, std::__1::function<bool (llvm::raw_ostream&, llvm::RecordKeeper&)>) /home/thurston/scratch_dir2/llvm-project/llvm/lib/TableGen/Main.cpp:137:5
    #8 0xaaaae412b72c in main /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/TableGen.cpp:84:10
    #9 0xffff8a326dbc in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0xffff8a326e94 in __libc_start_main csu/../csu/libc-start.c:360:3
    #11 0xaaaae385c9ec in _start (/home/thurston/scratch_dir2/llvm_build_msan_track_origins/bin/llvm-tblgen+0x1ac9ec)

  Uninitialized value was stored to memory at
    #0 0xaaaae3af7f8c in operator[] /home/thurston/scratch_dir2/libcxx_build_msan_track_origins/include/c++/v1/vector:1538:12
    #1 0xaaaae3af7f8c in getChild /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.h:732:50
    #2 0xaaaae3af7f8c in GenerateVariantsOf(llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>, std::__1::vector<llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>, std::__1::allocator<llvm::IntrusiveRefCntPtr<llvm::TreePatternNode>>>&, llvm::CodeGenDAGPatterns&, llvm::StringSet<llvm::MallocAllocator> const&) /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:4710:35
    #3 0xaaaae3add534 in llvm::CodeGenDAGPatterns::GenerateVariants() /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:4750:5
    #4 0xaaaae3ad1254 in llvm::CodeGenDAGPatterns::CodeGenDAGPatterns(llvm::RecordKeeper&, std::__1::function<void (llvm::TreePattern*)>) /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/CodeGenDAGPatterns.cpp:3198:3
    #5 0xaaaae3c882cc in DAGISelEmitter /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/DAGISelEmitter.cpp:31:58
    #6 0xaaaae3c882cc in llvm::TableGen::Emitter::OptClass<(anonymous namespace)::DAGISelEmitter>::run(llvm::RecordKeeper&, llvm::raw_ostream&) /home/thurston/scratch_dir2/llvm-project/llvm/include/llvm/TableGen/TableGenBackend.h:44:56
    #7 0xaaaae42903f8 in llvm::TableGenMain(char const*, std::__1::function<bool (llvm::raw_ostream&, llvm::RecordKeeper&)>) /home/thurston/scratch_dir2/llvm-project/llvm/lib/TableGen/Main.cpp:137:5
    #8 0xaaaae412b72c in main /home/thurston/scratch_dir2/llvm-project/llvm/utils/TableGen/TableGen.cpp:84:10
    #9 0xffff8a326dbc in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0xffff8a326e94 in __libc_start_main csu/../csu/libc-start.c:360:3
    #11 0xaaaae385c9ec in _start (/home/thurston/scratch_dir2/llvm_build_msan_track_origins/bin/llvm-tblgen+0x1ac9ec)
    ```

**Comment by thurstond** [comment]
Update: my bad, I hadn't run the buildbot script correctly. The MSan and HWASan reports only manifest specifically at eef8e1d206dc01c081a0ca29b7f9e0c39d33446e, not the previous revision. (This does not rule out the possibility that it is merely exposing a latent bug.)
