### ISSUE TITLE
`SIGSEGV` in `clang_getCursorPrettyPrinted()` (or, precisely, `StmtPrinter::Visit(clang::Stmt*)`)

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [llvm/llvm-project#75920]
I'm parsing C and C++ source code using _Libclang_ by calling `clang_visitChildren(CXCursor, CXCursorVisitor, CXClientData)` from a JVM, using [JVM bindings](https://github.com/bytedeco/javacpp-presets/tree/master/llvm) to _Libclang_.

In some complex cases (like the source code of _Linux_ kernel), the JVM process crashes with a `SIGSEGV` (Linux) or `EXCEPTION_ACCESS_VIOLATION` (Windows) inside `libclang.so`. This happens when my client code calls [`clang_getCursorPrettyPrinted()`](https://clang.llvm.org/doxygen/group__CINDEX__CURSOR__XREF.html#gab9d561cc237ce0d8bfbab80cdd5be216), and the exact location is [`StmtPrinter::Visit(clang::Stmt*)`](https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/lib/AST/StmtPrinter.cpp#L67):

```console
C  [libclang.so.16+0x86ac4a]  (anonymous namespace)::StmtPrinter::Visit(clang::Stmt*)+0x2a
```

I managed to pinpoint the problem: it occurs when I'm calling `clang_getCursorPrettyPrinted()` for a `CXCursor` instance of type `CXCursor_StructDecl` or `CXCursor_FunctionDecl`. Furtherore, _Libclang_ crashes trying to pretty-print the following function declaration:

```c
void *__kmalloc(size_t size, gfp_t flags) __attribute__((__assume_aligned__(__alignof__(unsigned long long)))) __attribute__((__malloc__));
```

One of the minimal reproducers is:

```c
void *f() __attribute__((__assume_aligned__(__alignof__(unsigned long long))));
```

_Libclang_ versions **15.0.3**, **16.0.4**, and **17.0.6** are all equally affected.

Original issue:
 - bytedeco/javacpp-presets#1442

**Comment by 0x6675636b796f75676974687562** [comment]
Here's the backtrace from the `core` file (_Libclang_ **17.0.6**, Linux):

```console
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f1348739d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f13486eaf32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f13486d5472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f134756dc27 in os::abort(bool, void*, void const*) [clone .cold.42] () from /usr/lib/jvm/zulu17-ca-amd64/lib/server/libjvm.so
#5  0x00007f1348227ba0 in VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) () from /usr/lib/jvm/zulu17-ca-amd64/lib/server/libjvm.so
#6  0x00007f13482286db in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) () from /usr/lib/jvm/zulu17-ca-amd64/lib/server/libjvm.so
#7  0x00007f134822870e in VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) () from /usr/lib/jvm/zulu17-ca-amd64/lib/server/libjvm.so
#8  0x00007f13480ce24c in JVM_handle_linux_signal () from /usr/lib/jvm/zulu17-ca-amd64/lib/server/libjvm.so
#9  <signal handler called>
#10 0x00007f1212300710 in (anonymous namespace)::StmtPrinter::Visit(clang::Stmt*) () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#11 0x00007f12123029d8 in clang::Stmt::printPretty(llvm::raw_ostream&, clang::PrinterHelper*, clang::PrintingPolicy const&, unsigned int, llvm::StringRef, clang::ASTContext const*) const [clone .localalias] () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#12 0x00007f121205b1f9 in clang::AssumeAlignedAttr::printPretty(llvm::raw_ostream&, clang::PrintingPolicy const&) const [clone .localalias] () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#13 0x00007f12120e7803 in (anonymous namespace)::DeclPrinter::prettyPrintAttributes(clang::Decl*) [clone .part.0] () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#14 0x00007f12120ee9eb in (anonymous namespace)::DeclPrinter::VisitFunctionDecl(clang::FunctionDecl*) () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#15 0x00007f12120eb1f5 in clang::declvisitor::Base<std::add_pointer, (anonymous namespace)::DeclPrinter, void>::Visit(clang::Decl*) () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#16 0x00007f12120ed23c in clang::Decl::print(llvm::raw_ostream&, clang::PrintingPolicy const&, unsigned int, bool) const () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#17 0x00007f1211f5b9e6 in clang_getCursorPrettyPrinted () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libclang.so.17
#18 0x00007f12b9482aa0 in Java_org_bytedeco_llvm_global_clang_clang_1getCursorPrettyPrinted () from /home/user/.javacpp/cache/llvm-17.0.6-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/llvm/linux-x86_64/libjniclang.so
```

`info frame`:

```console
(gdb) info frame
Stack level 10, frame at 0x7f134722ef30:
 rip = 0x7f1212300710 in (anonymous namespace)::StmtPrinter::Visit(clang::Stmt*); saved rip = 0x7f12123029d8
 called by frame at 0x7f134722efc0, caller of frame at 0x7f134722ee60
 Arglist at 0x7f134722ee58, args:
 Locals at 0x7f134722ee58, Previous frame's sp is 0x7f134722ef30
 Saved registers:
  rbx at 0x7f134722eef8, rbp at 0x7f134722ef00, r12 at 0x7f134722ef08, r13 at 0x7f134722ef10, r14 at 0x7f134722ef18, r15 at 0x7f134722ef20, rip at 0x7f134722ef28
```

`info args` and `info locals` provide no information.
