### ISSUE TITLE
Windows `github-pull-request` pre-merge CI fails with "OSError: [Errno 22] Invalid argument" on various tests

### ISSUE THREAD

**Issue by rengolin** [llvm/llvm-project#77086]
The basic `github-pull-request` CI check [fails](https://buildkite.com/llvm-project/github-pull-requests/builds/26594#018cd5cd-2449-4e92-ba57-d2b15c95eefe/404-10521) for FIR tests on Windows on unrelated changes (ex. #75955).

```
Unresolved Tests (4):
  Flang :: Lower/OpenMP/FIR/declare-target-implicit-func-and-subr-cap-enter.f90
  Flang :: Lower/OpenMP/FIR/declare-target-implicit-func-and-subr-cap.f90
  Flang :: Lower/OpenMP/declare-target-implicit-func-and-subr-cap-enter.f90
  Flang :: Lower/OpenMP/declare-target-implicit-func-and-subr-cap.f90
```

Example:
```
UNRESOLVED: Flang :: Lower/OpenMP/FIR/declare-target-implicit-func-and-subr-cap-enter.f90 (785 of 2469)
******************** TEST 'Flang :: Lower/OpenMP/FIR/declare-target-implicit-func-and-subr-cap-enter.f90' FAILED ********************
Exception during script execution:
Traceback (most recent call last):
  File "C:\ws\src\llvm\utils\lit\lit\worker.py", line 76, in _execute_test_handle_errors
    result = test.config.test_format.execute(test, lit_config)
  File "C:\ws\src\llvm\utils\lit\lit\formats\shtest.py", line 29, in execute
    return lit.TestRunner.executeShTest(
  File "C:\ws\src\llvm\utils\lit\lit\TestRunner.py", line 2257, in executeShTest
    parsed = parseIntegratedTestScript(test, require_script=not script)
  File "C:\ws\src\llvm\utils\lit\lit\TestRunner.py", line 2119, in parseIntegratedTestScript
    parsed = _parseKeywords(
  File "C:\ws\src\llvm\utils\lit\lit\TestRunner.py", line 2058, in _parseKeywords
    for line_number, command_type, ln in parseIntegratedTestScriptCommands(
  File "C:\ws\src\llvm\utils\lit\lit\TestRunner.py", line 1280, in parseIntegratedTestScriptCommands
    f = open(source_path, "rb")
OSError: [Errno 22] Invalid argument: 'C:\\ws\\src\\flang\\test\\Lower\\OpenMP\\FIR\\declare-target-implicit-func-and-subr-cap-enter.f90'
```

If these tests are flaky, the should not be enabled by default on general CI pre-merge tests.

**Comment by rengolin** [comment]
@kiranchandramohan @RichBarton-Arm

**Comment by joker-eph** [comment]
It's not clear to me that there is flakiness involved: do you see some runs passing?

The error seems to be `lit` failing to open these files:
```
  File "C:\ws\src\llvm\utils\lit\lit\TestRunner.py", line 1280, in parseIntegratedTestScriptCommands
    f = open(source_path, "rb")
OSError: [Errno 22] Invalid argument: 'C:\\ws\\src\\flang\\test\\Lower\\OpenMP\\FIR\\declare-target-implicit-func-and-subr-cap-enter.f90'
```

But I'm struggling to see what's special about these files that makes them different? (the path does not seem like it would exceed some length limitation for example)

**Comment by rengolin** [comment]
> It's not clear to me that there is flakiness involved: do you see some runs passing?

Not really, I'm just assuming someone have seen those tests passing before... At the very least when this code was introduced and the PR had the exact same builder on it. 

But these tests were added 6 months ago, so surely, they have passed before? Or maybe someone turned on the build recently? Still would have seen them in the PR that enabled them?

**Comment by Hardcode84** [comment]
My other PR, based on the same `main` sha https://github.com/llvm/llvm-project/pull/76108 had passed successfully

**Comment by kiranchandramohan** [comment]
@ergawy Did you investigate this further?

**Comment by ergawy** [comment]
I tried for quite sometime before the holidays to get a working build on Windows without much success unfortunately, spent more time than I'd like to admit :(. However, I am not that familiar with Windows so I might have not approached this in the best way.

Anyway, it is still on my todo list, if it's ok, I will give it a fresh try later this week.

**Comment by kiranchandramohan** [comment]
I will disable the tests for now.

**Comment by kiranchandramohan** [comment]
I have disabled these tests on Windows for now.
@ergawy @agozillon @shraiysh

**Comment by joker-eph** [comment]
> I will disable the tests for now.

@kiranchandramohan : did you miss https://github.com/llvm/llvm-project/issues/77086#issuecomment-1878905702 ?
It's not clear to me that we have data showing issues specific to these tests?

**Comment by kiranchandramohan** [comment]
> > I will disable the tests for now.
> 
> @kiranchandramohan : did you miss [#77086 (comment)](https://github.com/llvm/llvm-project/issues/77086#issuecomment-1878905702) ? It's not clear to me that we have data showing issues specific to these tests?

@joker-eph I saw the comment. But I thought it would be good to disable these tests on Windows until the issue is fixed. Otherwise, it will be a distraction for other contributors to LLVM.

**Comment by joker-eph** [comment]
That would make sense if we see that these tests in particular are failing more often than anything else, do we?

**Comment by kiranchandramohan** [comment]
I looked at the last three pages of Pull Requests, there are around 25 PRs per page.
Page 1 : 2 PRs have the flang openmp tests failing
Page 2 : Nothing applicable
Page 3: 2 PRs have the python tests failing

Note: I was only looking at the PRs with failing tests at the moment.

With this limited data, I think there is no reason to believe that the flang openmp tests are failing more often.
