### ISSUE TITLE
int128 as underlying enum type leaks memory

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#78160]
Code:

```c++
enum A : __int128 {
  a,
  b
};
```

Leak reported by asan:

```
Direct leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x3e3301 in operator new[](unsigned long) (/home/tbaeder/code/llvm-project/build/bin/clang-18+0x3e3301) (BuildId: f60b6049740dff9abb50a1499d5e41906fc6ed51)
    #1 0x7f7bdcfbfdfe in getMemory(unsigned int) /home/tbaeder/code/llvm-project/llvm/lib/Support/APInt.cpp:45:10
    #2 0x7f7bdcfbfbf3 in llvm::APInt::initSlowCase(llvm::APInt const&) /home/tbaeder/code/llvm-project/llvm/lib/Support/APInt.cpp:86:12
    #3 0x7f7c20dcb581 in llvm::APInt::APInt(llvm::APInt const&) /home/tbaeder/code/llvm-project/llvm/include/llvm/ADT/APInt.h:158:7
    #4 0x7f7c2176a5c6 in llvm::APSInt::APSInt(llvm::APSInt const&) /home/tbaeder/code/llvm-project/llvm/include/llvm/ADT/APSInt.h:23:21
    #5 0x7f7c22be7fc6 in clang::EnumConstantDecl::EnumConstantDecl(clang::DeclContext*, clang::SourceLocation, clang::IdentifierInfo*, clang::QualType, clang::Expr*, llvm::APSInt const&) /home/tbaeder/code/llvm-project/clang/include/clang/AST/Decl.h:3262:62
    #6 0x7f7c22bc2833 in clang::EnumConstantDecl::Create(clang::ASTContext&, clang::EnumDecl*, clang::SourceLocation, clang::IdentifierInfo*, clang::QualType, clang::Expr*, llvm::APSInt const&) /home/tbaeder/code/llvm-project/clang/lib/AST/Decl.cpp:5376:22
    #7 0x7f7c27b0048e in clang::Sema::CheckEnumConstant(clang::EnumDecl*, clang::EnumConstantDecl*, clang::SourceLocation, clang::IdentifierInfo*, clang::Expr*) /home/tbaeder/code/llvm-project/clang/lib/Sema/SemaDecl.cpp:19743:10
    #8 0x7f7c27b02e75 in clang::Sema::ActOnEnumConstant(clang::Scope*, clang::Decl*, clang::Decl*, clang::SourceLocation, clang::IdentifierInfo*, clang::ParsedAttributesView const&, clang::SourceLocation, clang::Expr*) /home/tbaeder/code/llvm-project/clang/lib/Sema/SemaDecl.cpp:19808:5
    #9 0x7f7c21265efd in clang::Parser::ParseEnumBody(clang::SourceLocation, clang::Decl*) /home/tbaeder/code/llvm-project/clang/lib/Parse/ParseDecl.cpp:5301:35
    #10 0x7f7c2125905b in clang::Parser::ParseEnumSpecifier(clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext) /home/tbaeder/code/llvm-project/clang/lib/Parse/ParseDecl.cpp:5220:5
    #11 0x7f7c2124bc69 in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) /home/tbaeder/code/llvm-project/clang/lib/Parse/ParseDecl.cpp:4413:7
    #12 0x7f7c212a0904 in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) /home/tbaeder/code/llvm-project/clang/include/clang/Parse/Parser.h:2452:12
    #13 0x7f7c2171d673 in clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /home/tbaeder/code/llvm-project/clang/lib/Parse/Parser.cpp:1143:3
    #14 0x7f7c2171c018 in clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /home/tbaeder/code/llvm-project/clang/lib/Parse/Parser.cpp:1261:12
    #15 0x7f7c21719d32 in clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /home/tbaeder/code/llvm-project/clang/lib/Parse/Parser.cpp:1065:14
    #16 0x7f7c21710c3e in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /home/tbaeder/code/llvm-project/clang/lib/Parse/Parser.cpp:755:12
    #17 0x7f7c2170e1fd in clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /home/tbaeder/code/llvm-project/clang/lib/Parse/Parser.cpp:602:26
    #18 0x7f7c211a4372 in clang::ParseAST(clang::Sema&, bool, bool) /home/tbaeder/code/llvm-project/clang/lib/Parse/ParseAST.cpp:162:25
    #19 0x7f7c33140d83 in clang::ASTFrontendAction::ExecuteAction() /home/tbaeder/code/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1183:3
    #20 0x7f7c2ed59c12 in clang::CodeGenAction::ExecuteAction() /home/tbaeder/code/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1153:30
    #21 0x7f7c3313efbf in clang::FrontendAction::Execute() /home/tbaeder/code/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1069:8
    #22 0x7f7c32c5c476 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/tbaeder/code/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1057:33
[...]
```

**Comment by shafik** [comment]
I can not reproduce: https://godbolt.org/z/o9P3xMEsW

Please provide more details.

**Comment by topperc** [comment]
EnumConstantDecl is allocated in the ASTContext's allocator. Destructors are never called for objects allocated in the ASTContext allocator. If the APInt in EnumConstantDecl is larger than 64 bits, the APInt constructor will allocate memory on the heap. This memory never gets destroyed.

Perhaps the APIntStorage class that is used to for a similar issue in IntegerLiteral can be extracted and used for EnumContantDecl as well?

**Comment by topperc** [comment]
> I can not reproduce: https://godbolt.org/z/o9P3xMEsW
> 
> Please provide more details.

The leak is in the compiler, not the program. asan won't find it unless you build the compiler itself with asan.
