### ISSUE TITLE
[X86][llvm-project-16.0.6] crash if use optimize

### ISSUE THREAD

**Issue by fzhedu** [llvm/llvm-project#82573]
```
source_filename = "sr_module_139888579933104"

define void @"{col[INT]<=>{INT[CONST: NULL Size : 1]}}BOOLEAN"(i64 %0, ptr %1) {
entry:
  %2 = getelementptr inbounds { ptr, ptr }, ptr %1, i64 0
  %3 = load { ptr, ptr }, ptr %2, align 8
  %4 = extractvalue { ptr, ptr } %3, 0
  %5 = extractvalue { ptr, ptr } %3, 1
  %6 = getelementptr inbounds { ptr, ptr }, ptr %1, i64 1
  %7 = load { ptr, ptr }, ptr %6, align 8
  %8 = extractvalue { ptr, ptr } %7, 0
  %9 = extractvalue { ptr, ptr } %7, 1
  br label %loop

end:                                              ; preds = %loop
  ret void

loop:                                             ; preds = %loop, %entry
  %10 = phi i64 [ 0, %entry ], [ %14, %loop ]
  %11 = getelementptr inbounds i32, ptr %4, i64 %10
  %12 = load i32, ptr %11, align 4
  %13 = getelementptr inbounds i8, ptr %8, i64 %10
  store i8 1, ptr %13, align 1
  %14 = add i64 %10, 1
  %15 = icmp eq i64 %14, %0
  br i1 %15, label %end, label %loop
}
```

this code will be crash if taking following optimize
```
static void optimize_module(llvm::Module& module, llvm::TargetIRAnalysis target_analysis) {
    // Setup an optimiser pipeline
    llvm::PassBuilder pass_builder;
    llvm::LoopAnalysisManager loop_am;
    llvm::FunctionAnalysisManager function_am;
    llvm::CGSCCAnalysisManager cgscc_am;
    llvm::ModuleAnalysisManager module_am;

    function_am.registerPass([&] { return target_analysis; });

    // Register required analysis managers
    pass_builder.registerModuleAnalyses(module_am);
    pass_builder.registerCGSCCAnalyses(cgscc_am);
    pass_builder.registerFunctionAnalyses(function_am);
    pass_builder.registerLoopAnalyses(loop_am);
    pass_builder.crossRegisterProxies(loop_am, function_am, cgscc_am, module_am);

    pass_builder.registerPipelineStartEPCallback(
            [&](llvm::ModulePassManager& module_pm, llvm::OptimizationLevel Level) {
                module_pm.addPass(llvm::ModuleInlinerPass());

                llvm::FunctionPassManager function_pm;
                function_pm.addPass(llvm::InstCombinePass());
                function_pm.addPass(llvm::PromotePass());
                function_pm.addPass(llvm::GVNPass());
                function_pm.addPass(llvm::NewGVNPass());
                function_pm.addPass(llvm::SimplifyCFGPass());
                function_pm.addPass(llvm::LoopVectorizePass());
                function_pm.addPass(llvm::SLPVectorizerPass());
                module_pm.addPass(llvm::createModuleToFunctionPassAdaptor(std::move(function_pm)));

                module_pm.addPass(llvm::GlobalOptPass());
            });

    pass_builder.buildPerModuleDefaultPipeline(llvm::OptimizationLevel::O3).run(module, module_am);
}
```

the stack is :
```
#0  0x00007f778e6fbaee in __memset_sse2 () from /lib64/libc.so.6
#1  0x00007f778e7aa124 in do_sym () from /lib64/libc.so.6
#2  0x00007f778f1610c4 in dlsym_doit () from /lib64/libdl.so.2
#3  0x00007f77907fa7d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f778f1615ad in _dlerror_run () from /lib64/libdl.so.2
#5  0x00007f778f161118 in dlsym () from /lib64/libdl.so.2
#6  0x000000000c760cac in llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate(llvm::orc::LookupState&, llvm::orc::LookupKind, llvm::orc::JITDylib&, llvm::orc::JITDylibLookupFlags, llvm::orc::SymbolLookupSet const&) ()
#7  0x000000000c73e006 in llvm::orc::ExecutionSession::OL_applyQueryPhase1(std::unique_ptr<llvm::orc::InProgressLookupState, std::default_delete<llvm::orc::InProgressLookupState> >, llvm::Error) ()
#8  0x000000000c74e04e in llvm::orc::ExecutionSession::lookup(llvm::orc::LookupKind, std::vector<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>, std::allocator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> > > const&, llvm::orc::SymbolLookupSet, llvm::orc::SymbolState, llvm::unique_function<void (llvm::Expected<llvm::DenseMap<llvm::orc::SymbolStringPtr, llvm::JITEvaluatedSymbol, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void>, llvm::detail::DenseMapPair<llvm::orc::SymbolStringPtr, llvm::JITEvaluatedSymbol> > >)>, std::function<void (llvm::DenseMap<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> >, llvm::DenseMapInfo<llvm::orc::JITDylib*, void>, llvm::detail::DenseMapPair<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> > > > const&)>) ()
#9  0x000000000c7d098d in llvm::orc::ObjectLinkingLayerJITLinkContext::lookup(llvm::DenseMap<llvm::StringRef, llvm::jitlink::SymbolLookupFlags, llvm::DenseMapInfo<llvm::StringRef, void>, llvm::detail::DenseMapPair<llvm::StringRef, llvm::jitlink::SymbolLookupFlags> > const&, std::unique_ptr<llvm::jitlink::JITLinkAsyncLookupContinuation, std::default_delete<llvm::jitlink::JITLinkAsyncLookupContinuation> >) ()
#10 0x000000000b5e8bd1 in llvm::jitlink::JITLinkerBase::linkPhase2(std::unique_ptr<llvm::jitlink::JITLinkerBase, std::default_delete<llvm::jitlink::JITLinkerBase> >, llvm::Expected<std::unique_ptr<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc, std::default_delete<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc> > >) ()
#11 0x000000000b5e8d5e in void llvm::detail::UniqueFunctionBase<void, llvm::Expected<std::unique_ptr<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc, std::default_delete<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc> > > >::CallImpl<llvm::jitlink::JITLinkerBase::linkPhase1(std::unique_ptr<llvm::jitlink::JITLinkerBase, std::default_delete<llvm::jitlink::JITLinkerBase> >)::{lambda(llvm::Expected<std::unique_ptr<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc, std::default_delete<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc> > >)#1}>(void*, llvm::Expected<std::unique_ptr<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc, std::default_delete<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc> > >&) ()
#12 0x000000000b5f217d in llvm::jitlink::InProcessMemoryManager::allocate(llvm::jitlink::JITLinkDylib const*, llvm::jitlink::LinkGraph&, llvm::unique_function<void (llvm::Expected<std::unique_ptr<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc, std::default_delete<llvm::jitlink::JITLinkMemoryManager::InFlightAlloc> > >)>) ()
#13 0x000000000b5ea31a in llvm::jitlink::JITLinkerBase::linkPhase1(std::unique_ptr<llvm::jitlink::JITLinkerBase, std::default_delete<llvm::jitlink::JITLinkerBase> >) ()
#14 0x000000000b634479 in llvm::jitlink::link_ELF_x86_64(std::unique_ptr<llvm::jitlink::LinkGraph, std::default_delete<llvm::jitlink::LinkGraph> >, std::unique_ptr<llvm::jitlink::JITLinkContext, std::default_delete<llvm::jitlink::JITLinkContext> >) ()
#15 0x000000000b614cde in llvm::jitlink::link_ELF(std::unique_ptr<llvm::jitlink::LinkGraph, std::default_delete<llvm::jitlink::LinkGraph> >, std::unique_ptr<llvm::jitlink::JITLinkContext, std::default_delete<llvm::jitlink::JITLinkContext> >) ()
#16 0x000000000b5e289e in llvm::jitlink::link(std::unique_ptr<llvm::jitlink::LinkGraph, std::default_delete<llvm::jitlink::LinkGraph> >, std::unique_ptr<llvm::jitlink::JITLinkContext, std::default_delete<llvm::jitlink::JITLinkContext> >) ()
#17 0x000000000c7cd9ce in llvm::orc::ObjectLinkingLayer::emit(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >) ()
#18 0x000000000c7d8695 in llvm::orc::ObjectTransformLayer::emit(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >) ()
#19 0x000000000c785714 in llvm::orc::IRCompileLayer::emit(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >, llvm::orc::ThreadSafeModule) ()
#20 0x000000000c78618c in llvm::orc::IRTransformLayer::emit(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >, llvm::orc::ThreadSafeModule) ()
#21 0x000000000c78618c in llvm::orc::IRTransformLayer::emit(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >, llvm::orc::ThreadSafeModule) ()
#22 0x000000000c790fb0 in llvm::orc::BasicIRLayerMaterializationUnit::materialize(std::unique_ptr<llvm::orc::MaterializationResponsibility, std::default_delete<llvm::orc::MaterializationResponsibility> >) ()
#23 0x000000000c74d6b3 in llvm::orc::MaterializationTask::run() ()
#24 0x000000000c731411 in void llvm::detail::UniqueFunctionBase<void, std::unique_ptr<llvm::orc::Task, std::default_delete<llvm::orc::Task> > >::CallImpl<void (*)(std::unique_ptr<llvm::orc::Task, std::default_delete<llvm::orc::Task> >)>(void*, std::unique_ptr<llvm::orc::Task, std::default_delete<llvm::orc::Task> >&) ()
#25 0x000000000c74db40 in llvm::orc::ExecutionSession::dispatchOutstandingMUs() ()
#26 0x000000000c755a6e in llvm::orc::ExecutionSession::OL_completeLookup(std::unique_ptr<llvm::orc::InProgressLookupState, std::default_delete<llvm::orc::InProgressLookupState> >, std::shared_ptr<llvm::orc::AsynchronousSymbolQuery>, std::function<void (llvm::DenseMap<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> >, llvm::DenseMapInfo<llvm::orc::JITDylib*, void>, llvm::detail::DenseMapPair<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> > > > const&)>) ()
#27 0x000000000c757132 in llvm::orc::InProgressFullLookupState::complete(std::unique_ptr<llvm::orc::InProgressLookupState, std::default_delete<llvm::orc::InProgressLookupState> >) ()
#28 0x000000000c73e617 in llvm::orc::ExecutionSession::OL_applyQueryPhase1(std::unique_ptr<llvm::orc::InProgressLookupState, std::default_delete<llvm::orc::InProgressLookupState> >, llvm::Error) ()
#29 0x000000000c74e04e in llvm::orc::ExecutionSession::lookup(llvm::orc::LookupKind, std::vector<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>, std::allocator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> > > const&, llvm::orc::SymbolLookupSet, llvm::orc::SymbolState, llvm::unique_function<void (llvm::Expected<llvm::DenseMap<llvm::orc::SymbolStringPtr, llvm::JITEvaluatedSymbol, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void>, llvm::detail::DenseMapPair<llvm::orc::SymbolStringPtr, llvm::JITEvaluatedSymbol> > >)>, std::function<void (llvm::DenseMap<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> >, llvm::DenseMapInfo<llvm::orc::JITDylib*, void>, llvm::detail::DenseMapPair<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> > > > const&)>) ()
pKind, llvm::orc::SymbolState, std::function<void (llvm::DenseMap<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> >, llvm::DenseMapInfo<llvm::orc::JITDylib*, void>, llvm::detail::DenseMapPair<llvm::orc::JITDylib*, llvm::DenseSet<llvm::orc::SymbolStringPtr, llvm::DenseMapInfo<llvm::orc::SymbolStringPtr, void> > > > const&)>) ()
#31 0x000000000c74e72d in llvm::orc::ExecutionSession::lookup(std::vector<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags>, std::allocator<std::pair<llvm::orc::JITDylib*, llvm::orc::JITDylibLookupFlags> > > const&, llvm::orc::SymbolStringPtr, llvm::orc::SymbolState) ()

#32 0x000000000c79ab14 in llvm::orc::LLJIT::lookupLinkerMangled(llvm::orc::JITDylib&, llvm::orc::SymbolStringPtr) ()
#33 0x0000000006101cb6 in llvm::orc::LLJIT::lookupLinkerMangled (Name=..., JD=..., this=0x7f73c65fa280)
    at /home/disk5/sr-deps/thirdparty-20240201/installed/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h:120

#34 llvm::orc::LLJIT::lookup (UnmangledName=..., JD=..., this=0x7f73c65fa280)
    at /home/disk5/sr-deps/thirdparty-20240201/installed/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h:132
#35 llvm::orc::LLJIT::lookup (UnmangledName=..., this=0x7f73c65fa280)
    at /home/disk5/sr-deps/thirdparty-20240201/installed/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h:137
#36 starrocks::JITEngine::Engine::get_compiled_func (this=<optimized out>, function=...)
    at /home/disk2/fangzhuhe/starrocks/be/src/exprs/jit/jit_engine.cpp:447
#37 0x0000000006104771 in starrocks::JITEngine::compile_scalar_function (context=context@entry=0x7f73c690ab00,
    func_cache=func_cache@entry=0x7f73c6566d20, expr=0x7f73c6120b00, uncompilable_exprs=...)
    at /home/disk2/fangzhuhe/starrocks/be/src/exprs/jit/jit_engine.cpp:186
#38 0x0000000006111414 in starrocks::JITExpr::prepare (this=0x7f73be7a4a00, state=0x7f756c13a100, context=0x7f73c690ab00)
    at /home/disk2/fangzhuhe/starrocks/be/src/exprs/jit/jit_expr.cpp:67
#39 0x0000000006115fe3 in starrocks::ExprContext::prepare (this=0x7f73c690ab00, state=state@entry=0x7f756c13a100)
    at /home/disk2/fangzhuhe/starrocks/be/src/exprs/expr_context.cpp:72
#40 0x0000000006117be1 in starrocks::Expr::prepare (ctxs=..., state=state@entry=0x7f756c13a100)
    at /home/disk2/fangzhuhe/starrocks/be/src/exprs/expr.cpp:512
#41 0x000000000550361d in starrocks::pipeline::ProjectOperatorFactory::prepare (this=0x7f73c6303810, state=0x7f756c13a100)
    at /home/disk2/fangzhuhe/starrocks/be/src/exec/pipeline/project_operator.cpp:102
#42 0x00000000054e61b4 in starrocks::pipeline::Pipeline::prepare (state=0x7f756c13a100, this=<optimized out>)
    at /home/disk2/fangzhuhe/starrocks/be/src/exec/pipeline/pipeline.h:75
#43 starrocks::pipeline::FragmentContext::prepare_all_pipelines (this=0x7f756c131510)
    at /home/disk2/fangzhuhe/starrocks/be/src/exec/pipeline/fragment_context.h:107
#44 starrocks::pipeline::FragmentExecutor::_prepare_pipeline_driver (this=this@entry=0x7f76aca9f260,
    exec_env=exec_env@entry=0xd968e20 <starrocks::ExecEnv::GetInstance()::s_exec_env>, request=...)
    at /home/disk2/fangzhuhe/starrocks/be/src/exec/pipeline/fragment_executor.cpp:581
#45 0x00000000054e6c54 in starrocks::pipeline::FragmentExecutor::prepare (this=this@entry=0x7f76aca9f260,
    exec_env=0xd968e20 <starrocks::ExecEnv::GetInstance()::s_exec_env>, common_request=..., unique_request=...)
    at /home/disk2/fangzhuhe/starrocks/be/src/exec/pipeline/fragment_executor.cpp:725
#46 0x0000000007b93b6b in starrocks::PInternalServiceImplBase<starrocks::PInternalService>::_exec_plan_fragment_by_pipeline (
    this=this@entry=0x7ffc98d74720, t_common_param=..., t_unique_request=...)
    at /home/disk2/fangzhuhe/starrocks/be/src/service/internal_service.cpp:441
#47 0x0000000007b9c371 in starrocks::PInternalServiceImplBase<starrocks::PInternalService>::_exec_plan_fragment (this=0x7ffc98d74720,
    cntl=<optimized out>, request=<optimized out>) at /home/disk2/fangzhuhe/starrocks/be/src/service/internal_service.cpp:423
#48 0x0000000007bacf6d in starrocks::PInternalServiceImplBase<starrocks::PInternalService>::_exec_plan_fragment (this=<optimized out>,
    cntl_base=<optimized out>, request=<optimized out>, response=0x7f73ffc51a80, done=<optimized out>)
    at /home/disk2/fangzhuhe/starrocks/be/src/service/internal_service.cpp:306
#49 0x0000000007a5d08d in std::function<void ()>::operator()() const (this=0x7f76acaa0a38)
    at /home/disk5/sr-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
#50 starrocks::PriorityThreadPool::work_thread (this=0x7f778bd45500, thread_id=14)
    at /home/disk2/fangzhuhe/starrocks/be/src/util/priority_thread_pool.hpp:198
#51 0x0000000008c94c67 in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:179
#52 0x00007f778ea41ea5 in start_thread () from /lib64/libpthread.so.0
#53 0x00007f778e76ab0d in clone () from /lib64/libc.so.6
```

related in https://github.com/starrocks/starrocks/blob/60c908cf5ec1995a64ff69d38c8ea7e91d4058d7/be/src/exprs/jit/jit_engine.cpp#L381

**Comment by EugeneZelenko** [comment]
@fzhedu: Could you please elaborate?

**Comment by lhames** [comment]
It's quite unusual to see a crash inside dlsym. What string is being dlsym'd when the crash happens?
