### ISSUE TITLE
[clang++-11] clang: error: clang frontend command failed due to signal (use -v to see invocation)

### ISSUE THREAD

**Issue by yangke-anban** [llvm/llvm-project#85045]
clang++-11 crashed when compiling header files in qtbase 
(clang++-12, clang++-14 don't have this problem)

Env: Ubuntu 20.04 x86_64
Command:
```
mkdir qt && cd qt
git clone --branch dev --depth 5000 git://code.qt.io/qt/qtbase.git
cd qtbase && git checkout 0804109d686e0a99ab0de0f1c70e3422183c6e98
cd .. && tar xvf include.tar.gz  # see attachment
```
replace the path in include directory to absolute file path  corresponding with your linux
e.g.
suppose your path to include directory is at /home/mypath/qt/
replace `/home/yangke/Program/Saryn/qt/qtbase/xxx/xxx.h`  in *.h in extracted directory
with your own path: `/home/mypath/qt/qtbase/xxx/xxx.h`
for example,
```
cd ./include
find . -name *.h |xargs sed -i "s/yangke\/Program\/Saryn/mypath/g"
```
Reproduce crash!
```
clang++-11 -c ./qtbase/src/corelib/tools/qmap.h -I./include
```

```
...
some header not found error info
...
Stack dump:
0.	Program arguments: /usr/bin/clang++-11 -c /home/yangke/Program/Saryn/qt/qtbase/src/corelib/tools/qmap.h -I./include 
1.	/home/yangke/Program/Saryn/qt/qtbase/src/corelib/tools/qmap.h:807:2: current parser token ';'
2.	/home/yangke/Program/Saryn/qt/qtbase/src/corelib/tools/qmap.h:187:1: parsing struct/union/class body 'QMap'
/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7f532f44842f]
/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x50)[0x7f532f446790]
/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15CleanupOnSignalEm+0xdd)[0x7f532f447b7d]
/lib/x86_64-linux-gnu/libLLVM-11.so.1(+0x9edc80)[0x7f532f38fc80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f5336501420]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser27ParseLexedMethodDeclarationERNS0_27LateParsedMethodDeclarationE+0x638)[0x7f53342535d8]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser28ParseLexedMethodDeclarationsERNS0_12ParsingClassE+0x3a)[0x7f5334252c2a]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser27ParseCXXMemberSpecificationENS_14SourceLocationES1_RNS0_25ParsedAttributesWithRangeEjPNS_4DeclE+0x9a4)[0x7f533427bb84]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser19ParseClassSpecifierENS_3tok9TokenKindENS_14SourceLocationERNS_8DeclSpecERKNS0_18ParsedTemplateInfoENS_15AccessSpecifierEbNS0_15DeclSpecContextERNS0_25ParsedAttributesWithRangeE+0x136d)[0x7f533427965d]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser26ParseDeclarationSpecifiersERNS_8DeclSpecERKNS0_18ParsedTemplateInfoENS_15AccessSpecifierENS0_15DeclSpecContextEPNS0_18LateParsedAttrListE+0x3cd)[0x7f533425e75d]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser35ParseSingleDeclarationAfterTemplateENS_17DeclaratorContextERKNS0_18ParsedTemplateInfoERNS_21ParsingDeclRAIIObjectERNS_14SourceLocationERNS_16ParsedAttributesENS_15AccessSpecifierE+0x336)[0x7f53342e0a36]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser40ParseTemplateDeclarationOrSpecializationENS_17DeclaratorContextERNS_14SourceLocationERNS_16ParsedAttributesENS_15AccessSpecifierE+0x488)[0x7f53342e0098]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser36ParseDeclarationStartingWithTemplateENS_17DeclaratorContextERNS_14SourceLocationERNS_16ParsedAttributesENS_15AccessSpecifierE+0xe4)[0x7f53342dfab4]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser16ParseDeclarationENS_17DeclaratorContextERNS_14SourceLocationERNS0_25ParsedAttributesWithRangeEPS2_+0x293)[0x7f533425dd73]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser24ParseExternalDeclarationERNS0_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0x1ef)[0x7f53342ee71f]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb+0x4eb)[0x7f53342ed52b]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang8ParseASTERNS_4SemaEbb+0x1fd)[0x7f533424ff8d]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang14FrontendAction7ExecuteEv+0x48)[0x7f533581a5c8]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x861)[0x7f53357d08c1]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x5e0)[0x7f533587ff50]
/usr/bin/clang++-11(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x94f)[0x4125ff]
/usr/bin/clang++-11[0x410a3e]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(+0x1bbe992)[0x7f5335504992]
/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xdd)[0x7f532f38fa8d]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x13f)[0x7f5335503ebf]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x2df)[0x7f53354dbccf]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x77)[0x7f53354dbe77]
/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0xdc)[0x7f53354ef9cc]
/usr/bin/clang++-11(main+0x2533)[0x4104e3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f532e486083]
/usr/bin/clang++-11(_start+0x2e)[0x40dcde]
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Ubuntu clang version 11.0.0-2~ubuntu20.04.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: Error generating preprocessed source(s).
```
Call Stack by GDB:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5cf95d8 in clang::Parser::ParseLexedMethodDeclaration(clang::Parser::LateParsedMethodDeclaration&) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
(gdb) bt
#0  0x00007ffff5cf95d8 in clang::Parser::ParseLexedMethodDeclaration(clang::Parser::LateParsedMethodDeclaration&) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#1  0x00007ffff5cf8c2a in clang::Parser::ParseLexedMethodDeclarations(clang::Parser::ParsingClass&) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#2  0x00007ffff5d21b84 in clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::Parser::ParsedAttributesWithRange&, unsigned int, clang::Decl*) ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#3  0x00007ffff5d1f65d in clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::Parser::ParsedAttributesWithRange&) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#4  0x00007ffff5d0475d in clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#5  0x00007ffff5d86a36 in clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#6  0x00007ffff5d86098 in clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#7  0x00007ffff5d85ab4 in clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#8  0x00007ffff5d03d73 in clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#9  0x00007ffff5d9471f in clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#10 0x00007ffff5d9352b in clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#11 0x00007ffff5cf5f8d in clang::ParseAST(clang::Sema&, bool, bool) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#12 0x00007ffff72c05c8 in clang::FrontendAction::Execute() () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#13 0x00007ffff72768c1 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#14 0x00007ffff7325f50 in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#15 0x00000000004125ff in cc1_main(llvm::ArrayRef<char const*>, char const*, void*) ()
#16 0x0000000000410a3e in ?? ()
#17 0x00007ffff6faa992 in ?? () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#18 0x00007ffff0e35a8d in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) () from /lib/x86_64-linux-gnu/libLLVM-11.so.1
#19 0x00007ffff6fa9ebf in clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const
    () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#20 0x00007ffff6f81ccf in clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const () from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#21 0x00007ffff6f81e77 in clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#22 0x00007ffff6f959cc in clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) ()
   from /lib/x86_64-linux-gnu/libclang-cpp.so.11
#23 0x00000000004104e3 in main ()

```

**Comment by dtcxzyw** [comment]
clang-11 is no longer maintained. Please use clang-18 or later.

Feel free to reopen this issue if you can reproduce this with the current trunk :)
