### ISSUE TITLE
test/python/dialects/transform_interpreter.py fails with PyMlirTransformOptions is non-copyable

### ISSUE THREAD

**Issue by rengolin** [llvm/llvm-project#90193]
New check-out, new build, trunk as of today (`74a5e7784b`):
```
$ ninja check-mlir
 98% [87:88/88] 686.8/s, 0.127s Running the MLIR regression tests
FAIL: MLIR :: python/dialects/transform_interpreter.py (1 of 2328)
******************** TEST 'MLIR :: python/dialects/transform_interpreter.py' FAILED ********************
Exit Code: 2

Command Output (stdout):
--
# RUN: at line 1
/usr/bin/python3.10 /home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py | /home/rengolin/devel/llvm/linalg-named-ops/build/bin/FileCheck /home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py
# executed command: /usr/bin/python3.10 /home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py
# .---command stderr------------
# | Traceback (most recent call last):
# |   File "/home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py", line 4, in <module>
# |     from mlir.dialects.transform import interpreter as interp
# |   File "/home/rengolin/devel/llvm/linalg-named-ops/build/tools/mlir/python_packages/mlir_core/mlir/dialects/transform/interpreter/__init__.py", line 6, in <module>
# |     from ...._mlir_libs import _mlirTransformInterpreter as _cextTransformInterpreter
# | ImportError: return_value_policy = copy, but type (anonymous namespace)::PyMlirTransformOptions is non-copyable!
# `-----------------------------
# error: command failed with exit status: 1
# executed command: /home/rengolin/devel/llvm/linalg-named-ops/build/bin/FileCheck /home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py
# .---command stderr------------
# | FileCheck error: '<stdin>' is empty.
# | FileCheck command line:  /home/rengolin/devel/llvm/linalg-named-ops/build/bin/FileCheck /home/rengolin/devel/llvm/linalg-named-ops/mlir/test/python/dialects/transform_interpreter.py
# `-----------------------------
# error: command failed with exit status: 2

--

********************
********************
Failed Tests (1):
  MLIR :: python/dialects/transform_interpreter.py
```

I only see this on my local Ubuntu install (AMD), not on Arch (Intel), not on Rocky (Intel/AMD).

@ftynse

**Comment by ftynse** [comment]
Hmm, what's your C++ compiler? This did pass on buildbots that are also running Ubuntu.

**Comment by ftynse** [comment]
As a semi-blind guess, try if this helps:

```patch
diff --git a/mlir/lib/Bindings/Python/TransformInterpreter.cpp b/mlir/lib/Bindings/Python/TransformInterpreter.cpp
index f6b4532b1b6b..d35eb2415f01 100644
--- a/mlir/lib/Bindings/Python/TransformInterpreter.cpp
+++ b/mlir/lib/Bindings/Python/TransformInterpreter.cpp
@@ -37,7 +37,7 @@ struct PyMlirTransformOptions {
 
 static void populateTransformInterpreterSubmodule(py::module &m) {
   py::class_<PyMlirTransformOptions>(m, "TransformOptions", py::module_local())
-      .def(py::init())
+      .def(py::init(), py::return_value_policy::move)
       .def_property(
           "expensive_checks",
           [](const PyMlirTransformOptions &self) {
```

**Comment by rengolin** [comment]
> Hmm, what's your C++ compiler? This did pass on buildbots that are also running Ubuntu.

clang 14 ubuntu, running through ccache.

> As a semi-blind guess, try if this helps:

it did not. :(

Let me finish my current task and I'll look further into this.

**Comment by rengolin** [comment]
I don't know much how this works, so take what I'll say with salt.

So, with the line added, and still the same error, I looked elsewhere to see if there was another place requesting copy semantics and found none. A full grep returns `move`, `take_ownership` and `reference` for the `py::cast` variations.

Then I went into the usage in the Python file that imports the shared object. There is only one use in that test:
```python
def transform_options():
    options = interp.TransformOptions()
    options.expensive_checks = False
    options.enforce_single_top_level_transform_op = True
    ...
```

I commented out that test and the import is still failing on the same place, so it's something on the import side?

**Comment by ftynse** [comment]
There's a trampoline here: https://github.com/llvm/llvm-project/blob/main/mlir/python/mlir/dialects/transform/interpreter/__init__.py#L17-L32, maybe it decides to copy for some reason, but I'm puzzled why it's only on a subset of systems.

**Comment by rengolin** [comment]
> There's a trampoline here: https://github.com/llvm/llvm-project/blob/main/mlir/python/mlir/dialects/transform/interpreter/__init__.py#L17-L32, maybe it decides to copy for some reason, but I'm puzzled why it's only on a subset of systems.

Commented out the whole file, still the same issue.

This is my CMake line:
```
cmake -G Ninja -DLLVM_ENABLE_ASSERTIONS=True \
    -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_USE_LINKER=lld \
    -DLLVM_PARALLEL_LINK_JOBS=4 -DLLVM_ENABLE_PROJECTS="mlir" -DLLVM_LIT_ARGS="-sv" \
    -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_INSTALL_PREFIX=install -DLLVM_CCACHE_BUILD=ON \
    -DMLIR_INCLUDE_INTEGRATION_TESTS=ON -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_TESTS=True \
    ../lvm
```

**Comment by rengolin** [comment]
Disabling `-DMLIR_ENABLE_BINDINGS_PYTHON=ON` obviously "fixes" the build, so I'll use for my other stuff from now on. But I still want to understand what's going on here. I have a worktree for this in separate that I'll look over the next few days,

**Comment by rengolin** [comment]
Just confirmed on my Arch, Python `3.11`, the test passes without problems. Could it be a version issue?

```bash
# Arch (works)
$ clang --version
clang version 17.0.6
$ python3 --version
Python 3.11.8
$ uname -sr
Linux 6.6.28-1-lts
```
```bash
# Ubuntu (doesn't)
$ python3 --version
Python 3.10.12
$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1.1
$ uname -sr
Linux 5.15.0-105-generic
```
```bash
# Both
cmake -G Ninja -DLLVM_ENABLE_ASSERTIONS=True \
               -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_USE_LINKER=lld \
               -DLLVM_PARALLEL_LINK_JOBS=4 -DLLVM_ENABLE_PROJECTS="mlir" -DLLVM_LIT_ARGS="-sv" \
               -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_INSTALL_PREFIX=install -DLLVM_CCACHE_BUILD=ON \
               -DMLIR_INCLUDE_INTEGRATION_TESTS=ON -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
               ../llvm
```

**Comment by ftynse** [comment]
I do think it's a version problem, maybe some implementation/library detail, but I'd like to understand how specifically they differ. Could you also provide pybind11 versions?

**Comment by rengolin** [comment]
Ubuntu (broken):
`pybind11              2.9.1`
Arch (working):
`pybind11              2.12.0`

**Comment by christopherbate** [comment]
On my system (Ubuntu 22, Python 3.10) I also observe this error on current tip-of-main when pip has installed `pybind11==2.9.1`.

In my case, doing `pip install --upgrade -r mlir/python/requirements.txt` fixes it since `pip` will install `pybind11==2.10.3`.

Therefore, we may need to update the minimum pybind11 version in `requirements.txt`.

**Comment by dnsampaio** [comment]
Hi, same problem here. Ubuntu 22
python3.10
pybind11-2.13.6

Forcing pip to reinstall using pybind11==2.10.3 did not solve my problem either.
